### ISSUE TITLE
vs studio fails on startup

### ISSUE THREAD

**Issue by bluelight1324** [microsoft/PTVS#8027] opened 2024-10-15 02:22 UTC
**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1. started vs studio thats it
2.
3.

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.24138.2

Microsoft.VisualStudio.CommonIDE.Solutions.HResultExtensions+WrapperCOMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2221] ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2221]
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudioTools.Project.ProjectNode.SetCurrentConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by StellaHuang95** [comment] 2024-10-28 22:04
Thanks for reporting the issue. This is a dupe of https://github.com/microsoft/PTVS/issues/7930. Is your code in a public repo or could you provide code samples that help us repro this issue? Does this repro constantly for you? Could you also share more detailed repro steps? Thanks!

**Comment by judej** [comment] 2024-11-21 18:10
Hi @bluelight1324, this has been reported to the Visual Studio team. The problem is corruption in the .vs folder. Could you please delete the .vs folder in your project folder and see if the problem disappears?

When you delete the .vs folder, VS will rebuild it automatically when VS is restarted. 

If this does not work, please reopen the issue. Thanks for raising this issue.

jude

**Closed by judej** 2024-11-21 18:10 UTC
Labels: waiting for response
