### ISSUE TITLE
Intellisense forgets imports during editing

### ISSUE THREAD

**Issue by niwax** [microsoft/PTVS#7017] opened 2022-05-25 17:45 UTC
**Describe the bug**
When a project is first opened, imports work as expected both from inside the same project as well as installed packages:
![image](https://user-images.githubusercontent.com/6018292/170326595-018e9bbe-a7f7-47ea-a841-8b3f0bb856a9.png)

After an hour or two of work, they are marked as not resolved and other functionality like "Go to definition" is also broken. Only builtin packages are not impacted:
![image](https://user-images.githubusercontent.com/6018292/170326756-fe500847-3bed-4aa6-9a1f-acfacb6285fb.png)

The behaviour extends to the entire solution, including opening and closing files. After restarting VS, everything works again.

**Steps to Reproduce**
Unfortunately, I haven't been able to find a consistent trigger for this behaviour. It happens regardless of whether the project has been run, whether a lot of files are edited or VS is simply sitting idle.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 17.2.2
PTVS version: 17.0.22089.1
Python version: 3.8 and 3.9

**Comment by niwax** [comment] 2022-06-20 10:19
I just found out that this issue persist even through reloading the project, eg. after a Git pull. Only restarting Visual Studio fixes it temporarily.

Unfortunately, it has now also started happening as often as every five minutes.

**Comment by StellaHuang95** [comment] 2023-01-18 01:26
dupe of  https://github.com/microsoft/PTVS/issues/7068

**Closed by StellaHuang95** 2023-01-18 01:26 UTC
Labels: bug
