### ISSUE TITLE
VS 15 Preview 4 test adapter not discovering tests

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#1544] opened 2016-08-15 22:31 UTC
VS 15 Build 25615.00
Data Science workload

Add New Item, Unit Test
Save project, close and reload solution, restart VS...  I was never able to get the tests detected.  I made sure it wasn't a case of wrong active interpreter (ie. tests run with startup file set to the test & F5).

[Microsoft.VisualStudio.Default.err.txt](https://github.com/Microsoft/PTVS/files/419092/Microsoft.VisualStudio.Default.err.txt)

**Comment by zooba** [comment] 2016-08-15 22:47
When I repro'd this, the analyzer process was stuck loading the DB for unresolved module imports, which was blocking any other analysis. Not sure whether this is the cause, but it may be related.

**Comment by zooba** [comment] 2016-08-15 22:59
There's actually a `FileNotFoundException` being raised somewhere in the process of getting the tests back from the analyzer. I can't seem to break at it.

**Comment by zooba** [comment] 2016-08-15 23:14
Okay, so the problem is we have to install an absolutely minimal extension into the TestWindow\Extensions folder for this to work properly. Right now, it isn't finding our test adapter from the out-of-proc process, and there are too many dependencies to make it find it.

I guess this is a recent change to VS 15 that's affected us. Probably won't be fixed for the next Preview.

**Closed** 2016-08-16 20:54 UTC
Labels: bug, regression, Test Adapter
