### ISSUE TITLE
.pyd module compiled with visual studio and pybind11 cannot be imported in visual studio python but can be in a python interpreter

### ISSUE THREAD

**Issue by MisesEnForce** [Microsoft/PTVS#3168] opened 2017-10-17 09:02 UTC
Hello,

I use python 2-17.14 32bits.

I tried the section "Creating bindings for a simple function" from http://pybind11.readthedocs.io/en/master/basics.html#compiling-the-test-cases and it worked like a charm :  I can import the module from a python interpreter, and using the add function. Success.
Now I added a python project to the MVS solution compiling the previous pyd module, and tried an "import NameOfTheModule" and it doesn't work : it gives me green underlining with an error

![image](https://user-images.githubusercontent.com/5349602/31655528-72d3b480-b329-11e7-9fc1-59ac74b12297.png)

I have of course added the directory containing the .pyd file to the search paths in the python visual studio project

What am I doing wrong ?

**Comment by zooba** [comment] 2017-10-17 15:14
That ought to be enough, so it's hard to say what is not working. (If you're not on the latest version of Visual Studio 2017 though then it's likely because of bugs we have fixed - so I'm not surprised that VS 2015 would fail, and if your VS 2017 notification flag ![image](https://user-images.githubusercontent.com/1693688/31673004-e8263382-b312-11e7-84e0-f8e3f36e5765.png) has a number or is yellow then you have updates waiting.)

If you're already on the latest, then with that project open can you go to Tools, Python, Diagnostic Info and either post the contents as a [gist](https://gist.github.com) and link it here, or email as an attachment to ptvshelp@microsoft.com? It should contain logging information that we'll need to see what's going on.

You could also look at [this blog](https://blogs.msdn.microsoft.com/pythonengineering/2017/08/25/python-updates-in-visual-studio-15-4-preview-1/) for the secret feature to disable the completion database (coming for real in a later update, but there's a preview in the current one). This _shouldn't_ have any impact on a search path reference, but it might.

**Comment by MisesEnForce** [comment] 2017-10-17 19:49
Thx for your answer. Actually this was at work, I just reproduced exactly the same solution @home on my machine with my mvs 2015 last update, and no problem. Had the green underlying, but only until "intellisense" finish it's job. This last step doesn't go well with my mvs 2015 from work apparently. Will investigate further.

**Comment by zooba** [comment] 2017-10-17 22:15
Okay. Just so you're aware, we are only fixing critical bugs in Python support in VS 2015 these days. So if we can't reproduce it in the latest VS 2017, we'll close this issue.

**Comment by MisesEnForce** [comment] 2017-10-18 08:49
Ok, thx for the information. Side question : have you heard of issues around "from Toto import *" with python in visual studio 2015 ?

**Comment by zooba** [comment] 2017-10-18 17:29
@MisesEnForce It should be the same directory, which is taken from the Working Directory property in the project.

The best practice for referencing the pyd file while developing is to use a Search Path. In VS 2017, you can add a project reference and we will automatically keep the search path updated. For VS 2015, you will need to add a reference to the .pyd file directly for IntelliSense, and that should also add a search path for debugging.

I'm aware of a number of IntelliSense issues in VS 2015, but I have no way to know which one you are referring to in this case. Besides, since we are not fixing those issues anymore, I am most interested in issues in the latest update of VS 2017 (with the feature flag I mentioned above turned on).

**Comment by huguesv** [comment] 2017-12-14 17:27
I hope you were able to make progress. If not, feel free to open a new issue.

**Closed by huguesv** 2017-12-14 17:27 UTC
