### ISSUE TITLE
Visual Studio 17.3.0 can detect the wrong Python version in Conda environment if another package contains the word "Python"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7137] opened 2022-08-24 17:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-1730-can-detect-the-wron/10118876)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Whatever was before 17.3.0]
Visual Studio 17.3.0 thinks TEST's Python version is 3.8, as expected:
`conda create  --yes --name TEST --channel conda-forge python=3.8`

&nbsp;

Visual Studio 17.3.0 thinks Python's version  is 1.0.4 and the debugger refuses to launch because it doesn't support that version of Python, etc. `1.0.4` is the version of **msgpack-python**:
`conda install --yes --name TEST --channel conda-forge msgpack-python`

&nbsp;

It is my guess that something has changed where whatever parses a Conda environment just searches for the first (alphabetically sorted) package that contains the word 'python' and uses that package's version as the version of Python. My guess is based on the fact that `msgpack-python` sorts before `python`.
This issue only started happening after updating to 17.3.0

---
#### Feedback Bot on 8/15/2022, 07:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-08-24 19:55
I think your analysis is spot on.

I remember making this change a while back because there was an existing bug when detecting python version in conda environments. It sounds like there's a different bug now that wasn't caught by my testing. I will attempt to repro this today. If the problem is what you guessed, should be an easy fix.

**Comment by AdamYoblick** [comment] 2022-08-24 21:53
Yep, your guess was correct. 😄 

I made a bad assumption and thought running `conda list -n <envName> "python" --json` would do an exact match on that python string, but it includes everything that contains "python". Then I do indeed take the first result.
I will modify the code to look for a package with a name exactly matching "python" and that should solve the problem.

**Comment by AdamYoblick** [comment] 2022-08-25 19:01
This has been fixed and will be in the next release of VS

**Closed** 2022-08-25 19:01 UTC
Labels: needs investigation
