### ISSUE TITLE
Breakpoints fail to be hit when 'Native Code Debugging' is enabled.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7944] opened 2024-07-05 07:13 UTC
**Describe the bug**

![image](https://github.com/microsoft/PTVS/assets/82852072/22f0cfd5-d223-41e4-8de7-7489e019eecc)

Python installed from VS.

**Steps to Reproduce**

1. Create a Python Application project, add simple Python code.
```
from math import cos, radians
	
# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
		s = make_dot_string(i)
		print(s)
main()
```
2. Enable "Native Code Debugging" in project settings / debug page.
3. Set breakpoint and start debugging.

**Expected behavior**

Breakpoint should be hit.

**Additional context and screenshots**

Breakpoint can not be hit.

![FAILTOHIT](https://github.com/microsoft/PTVS/assets/82852072/173561a3-9884-48f8-be1a-9e4657e1e218)

## Logs

<details>

<summary>Output for <code>Debug</code> in the <code>Output</code> panel 
</summary>

<p>

```
'python.exe' (Win32): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe'. Symbols loaded.
'python.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'python.exe' (Win32): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\vcruntime140.dll'. 
'python.exe' (Win32): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python39.dll'. Symbols loaded.
'python.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'python.exe' (Win32): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\Python\Core\Microsoft.PythonTools.Debugger.Helper.x64.dll'. Symbols loaded.
'python.exe' (Python): Loaded ''. Module was built without symbols.
'python.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
The thread 13480 has exited with code 1788805120 (0x6a9f0000).
'python.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
'python.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'python.exe' (Python): Loaded '<frozen importlib._bootstrap>'. Module was built without symbols.
'python.exe' (Python): Loaded '<frozen importlib._bootstrap_external>'. Module was built without symbols.
'python.exe' (Python): Loaded '<frozen zipimport>'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\encodings\__init__.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\codecs.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\encodings\aliases.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\encodings\utf_8.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\encodings\cp1252.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\encodings\latin_1.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\io.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\abc.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\site.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\os.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\stat.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\_collections_abc.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\ntpath.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\genericpath.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\_sitebuiltins.py'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Lib\_bootlocale.py'. Module was built without symbols.
'python.exe' (Python): Loaded '<string>'. Module was built without symbols.
'python.exe' (Python): Loaded 'C:\Users\vting\source\repos\PythonApplication1\PythonApplication1\PythonApplication1.py'. Module was built without symbols.

```

</p>
</details>

**Comment by StellaHuang95** [comment] 2024-07-17 21:23
This is a dupe of https://github.com/microsoft/PTVS/issues/6900

**Closed by StellaHuang95** 2024-07-17 21:23 UTC
Labels: duplicate
