### ISSUE TITLE
Problem inserting new methods

### ISSUE THREAD

**Issue by IlanHindy** [Microsoft/PTVS#2947] opened 2017-08-26 16:13 UTC
Hi,
from a certain point while programing I encountered the following problem:
I added a method to class
That made the class unrecognized (when I called the method or other methods from the class)
When I changed the names of the file and the class the code recognized the method
This happened for each new method  I tried to declare
In the attached file the class NormalizeData became unrecognized after adding the asStringsList method
(both methods of the class the old and the new became unrecognized)
The other class in the file (Normalize) is recognized by other classes
Ilan

> 
[‏‏Chapter2Normalize.txt](https://github.com/Microsoft/PTVS/files/1253788/Chapter2Normalize.txt)

**Comment by huguesv** [comment] 2017-08-31 00:16
Thanks! This type of issue is often hard to reproduce when you really need it to ;)

**Comment by zooba** [comment] 2017-09-18 18:18
I suspect this is the same issue as #1730, where when you open a multiline block (in that case, `"""` and here I suspect it was `(`) we treat the rest of the file as being within that block and hence, invalid syntax. We may not recover from this quickly enough.

Closing this as a dupe unless we get more information that shows it is a different issue.

**Closed by zooba** 2017-09-18 18:18 UTC
Labels: area:IntelliSense, bug, resolution:duplicate
