### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Repair;ReturnCode:1638;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7309] opened 2023-01-11 19:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10237289)._

---
**在此处描述你的问题**  
  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:Repair;ReturnCode:1638;

---
#### Feedback Bot on 12/22/2022, 01:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-11 20:10
duplicate of #7312

**Closed by StellaHuang95** 2023-01-11 20:10 UTC
Labels: needs triage
