### ISSUE TITLE
VS2022 is not supported with the latest version of Python 3.10 Hint

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6868] opened 2022-01-26 17:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022使用最新版python-310提示不支持/1641530)._

---
[severity:I'm unable to use this version] [regression] [worked-in:VS2019]
VS2022 uses the latest version of python 3.10.0 prompt no longer supports **, python3.9 is 3.10, not 3.1, please do not prompt this, and pip installation package will also prompt no longer support the download of the 3.10 version of the package, please confirm that python3.10 and Python3.1 are not the same version

VS2022 uses the latest version of python 3.10.0 prompt no longer supports **, python3.9 is 3.10, not 3.1, please do not prompt this, and pip installation package will also prompt no longer support the download of the 3.10 version of the package, please confirm that python3.10 and Python3.1 are not the same version

---
#### Feedback Bot on 1/19/2022, 07:04 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-01-26 22:20
Dupe of #6795

**Closed by AdamYoblick** 2022-01-26 22:20 UTC
Labels: needs triage
