### ISSUE TITLE
Python - Code outlining hides entire function signature

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7097] opened 2022-07-27 16:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python---Code-outlining-hides-entire-fun/10096953)._

---
[severity:It's more difficult to complete my work]
When collapsing a python function with the "-" button, it collapses not only the function body, but the function signature as well. Given the following code snippet:

```
def foo():
    x = bar()
    if x:
        baz()
```
I would expect code outlining to collapse it into
```
def foo(): [...]
```
but instead it collapses to
```
def [...]
```
which makes it very difficult to find a particular function in a large file.

---
#### Feedback Bot on 7/17/2022, 08:05 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-07-27 17:21
duplicate of #7032

**Closed** 2022-07-27 18:19 UTC
Labels: needs triage
