### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7268] opened 2022-12-07 19:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10219353)._

---
[severity:I'm unable to use this version]
**Descrivere qui il problema riscontrato**  
  
  
===NON APPORTARE MODIFICHE SOTTO QUESTA RIGA===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 12/1/2022, 06:52 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-12-07 19:56
duplicate of #7238

**Closed by StellaHuang95** 2022-12-07 19:56 UTC
Labels: duplicate
