### ISSUE TITLE
When I write a statement casually and click Run, it shows that the debug adapter failed to start

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7294] opened 2023-01-03 17:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/当我随便写了一条语句，点击运行时，显示未能启动调试适配器/10233289)._

---
![image.png](https://aka.ms/dc/image?name=B897c8a9ee3af4bf48f953a271a788939638069556271371961_20221218-182028-image.png&tid=897c8a9ee3af4bf48f953a271a788939638069556271371961)

As shown in the figure, the program cannot be run

---
#### Feedback Bot on 12/18/2022, 11:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-03 18:02
![image](https://user-images.githubusercontent.com/100439259/210414944-93833add-7851-4863-952b-7d84880bd983.png)
duplicate of https://github.com/microsoft/PTVS/issues/7293

**Closed by StellaHuang95** 2023-01-03 18:02 UTC
Labels: duplicate
