### ISSUE TITLE
When compiling code, an interpretive window appears when hovering over the mouse, which affects the efficiency of writing and how to turn off smart prompts

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7547] opened 2023-04-28 18:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/编译代码时鼠标悬停时出现解释型窗口，影响编写效率，如何关闭智能提示/1698123)._

---
! [image.png] (https://aka.ms/dc/image?name=Ba0f89181d2474ddb9b80ac08bdcb031e637834657077572102_20220321-212145-image.png&tid=a0f89181d2474ddb9b80ac08bdcb031e637834657077572102)

---
#### Feedback Bot on 3/22/2022, 02:28 AM: 

(private comment, text removed)

**Comment by cwebster-99** [comment] 2023-05-02 20:31
Duplicate of https://github.com/microsoft/PTVS/issues/7257. Please upvote in discussion https://github.com/microsoft/PTVS/discussions/7412

**Closed by cwebster-99** 2023-05-02 20:31 UTC
Labels: needs triage
