### ISSUE TITLE
"The reference assemblies for .NETFramework,Version=v4.0 were not found" appeared in Python project. 

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6747] opened 2021-10-08 06:13 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/136506667-0a111b73-4f2e-4a70-9e04-3c5788bffe92.png)

**Steps to Reproduce**

Create a Python Application project.

**Expected behavior**

It should be created successfully without any errors.

**Additional context and screenshots**

An error appears in the error list.

![image](https://user-images.githubusercontent.com/82852072/136506915-c05be372-21c8-4de1-b7c3-224d1a8000e1.png)

**Installation details**

![image](https://user-images.githubusercontent.com/82852072/136507123-f2d70fca-feeb-4401-87d6-9cafc610d3d8.png)

**Comment by AdamYoblick** [comment] 2021-10-08 20:09
Can't seem to repro this on my machine, I never see this error. I was able to repro it on the test VM provided by the CTI team. However, the test VM is win11 while my machine is win10. Going to try to repro on my own win11 VM to verify.

**Comment by int19h** [comment] 2021-10-08 21:16
I suspect this is due to Python .targets importing SDK targets. Grep for `<Import` in BuildTasks\*.targets to see where it does that.

**Comment by dhbusch2** [comment] 2021-11-30 00:52
Hi everyone. I have a brand new install of Visual Studio 2022, and am trying to follow this tutorial:
https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-01-create-project?view=vs-2022

But I am getting the exact error described here. I only created a new Python Application, and this error appears immediately:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	PythonOne	C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217	

Any update on this?

**Comment by AdamYoblick** [comment] 2021-11-30 21:08
Hi @dhbusch2 , this is a known issue. It shouldn't be preventing anyone from running or debugging python scripts, but I know it's ugly. It's in our backlog to fix 😄

**Comment by Rankith** [comment] 2021-12-07 21:40
I just ran into this issue also.  I recently upgraded to windows 11 and a fresh everything.  When I pulled my repo (that was previously being developed on VS 2017 and windows 10) and try to run I get the error mentioned.

However, if I make a completely fresh python django project in VS 2022 it runs just fine.  I can't find a difference in any of the project files that would cause this though.  What should I do to get my repo working?

**Comment by AdamYoblick** [comment] 2021-12-07 22:00
I'm pretty sure this is an issue with the PTVS build and should have nothing to do with your projects. We haven't been able to dig into this yet, but we'll most likely take a look sometime in January.

**Comment by Rankith** [comment] 2021-12-07 22:03
ah didnt realize I ended up on a specific subsection when following links around to track down this issue sorry about that.  Hopefully whatever you guys have to fix for your project will point me in the right direction.  Not being able to find any setting/config files that are different between my "imported" and brand new projects yet having different results is mightily infuriating.

**Comment by AdamYoblick** [comment] 2021-12-07 22:04
Is your existing repo a Django project as well?

**Comment by Rankith** [comment] 2021-12-07 22:08
yup.  Am I just being dumb and not looking at the right spots?  the .pyproj files and .sln files are virtually the same other then a few GUIDs and file references.

**Comment by AdamYoblick** [comment] 2021-12-07 22:15
Can you please share or link to the two pyproj files? If one repros and one doesn't, that would definitely help with our investigation 😄

**Comment by Rankith** [comment] 2021-12-07 22:36
OK I put a zip here with them.
[pyprojfiles.zip](https://github.com/microsoft/PTVS/files/7672043/pyprojfiles.zip)
doesntworkatall.pyproj is the old one I am trying to get working.  Get that error when hitting run or build etc.
runsbutrebuilderrors.pyproj is the new one.  And when verifying things before uploading for you, I noticed that it runs fine and builds fine.  But if I do a rebuild on it it fails with the error:
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1217,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
Done building project "DjangoWebProject1.pyproj" -- FAILED.

**Comment by AdamYoblick** [comment] 2021-12-07 22:49
Thank you! One last question - the build error is annoying and we're certainly going to fix it. But can you still run the program? In all cases I've seen this error, it hasn't prevented the user from running. I just want to make sure that's also the case here.

**Comment by Rankith** [comment] 2021-12-07 22:52
No I can't run the program at all for the doesntworkatall.pyproj file.  Just hitting run generates the error.  Running DOES work on the new django project I made.

**Comment by AdamYoblick** [comment] 2021-12-07 23:24
Ok thank you so much for the repro and the extra information. It sounds like this is more severe than previously indicated. We have some internal tasks that unfortunately have higher priority, but we will look at this as soon as we can :)

**Comment by ttSpace** [comment] 2021-12-31 07:57
I can repro in today's build ```17.1.0 Preview 3.0 [32030.14.main]``` .

**Comment by AdamYoblick** [comment] 2022-01-18 18:39
### Root Cause

I did some digging on this bug and the root cause is as follows: The pyproj files we generate don't specify a .net target framework, so it uses some global default which is v4.0. 4.0 is not supported in VS2022, which is why the error is being shown.

So the fix is just to target a newer (supported) framework in our python tools targets file. This is fixed locally and will be released in the future.

### Workaround

If you don't want to wait for the fix, you can implement the same change I did in your pyproj file, as a workaround. Put this in your pyproj:

```xml
  <PropertyGroup>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>
    <TargetFrameworkMoniker>.NETFramework,Version=$(TargetFrameworkVersion)</TargetFrameworkMoniker>
  </PropertyGroup>
```

**Closed** 2022-01-18 22:02 UTC
Labels: P1, fixed in next version

**Comment by icnocop** [comment] 2022-03-03 23:37
Hi.

Will this fix in Visual Studio 2022 also apply to SQL Server Database Projects files (ie. sqlproj)?

When building on the command line, the following error occurs:

> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [c:\agent\_work\1\s\MySolution\src\MyDatabaseProject\MyDatabaseProject.sqlproj]

When opening the project in Visual Studio 2022 17.1.0, the following message appears:

> The SQL Server project MyDatabaseProject targets .NET Framework 4.0, which is no longer supported.

![image](https://user-images.githubusercontent.com/507649/156670508-c8670d5e-5d28-4248-ab17-72a1beb71225.png)

After adding the following properties to the project file, Visual Studio is able to load the project:

```
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <TargetFrameworkProfile />
```

Thank you.

**Comment by AdamYoblick** [comment] 2022-03-03 23:42
Hi Rami,

This fix was implemented in a targets file specifically for python tools, since this bug was reported for PTVS. I believe there is a bug open somewhere for it to be fixed globally in visual studio, but I'm not sure where that is or what the status of that is. Global VS bugs tend to take longer to fix and roll out, since they usually involve more discussion and oversight. Individual product teams are a bit more agile in that sense.

In the meantime, I would suggest reporting a problem from within visual studio and specify that a sqlproj is experiencing this problem (and maybe include a link to this issue) so the sql team can address this in their product.

**Comment by kevcGIT** [comment] 2022-04-13 18:13
I just did a fresh install of Windows 10 and VS 2022. I have scope studio projects that are hitting this .NET 4.0 error. I have never hit this before on my other device in VS 2022. What can I do to fix this?

**Comment by AdamYoblick** [comment] 2022-04-13 18:17
I'm not sure what scope studio projects are, this repo is for Python Tools in Visual Studio. This issue has been fixed for PTVS.

In any case, see [my comment](https://github.com/microsoft/PTVS/issues/6747#issuecomment-1015704916) for a workaround that might work for whatever else you are using 😄

**Comment by xardasVB** [comment] 2022-05-26 14:22
i have this issue trying yo build my simple python project for azure web app

**Comment by Jicksonjosephabc** [comment] 2022-06-08 06:54
Installed the latest dotnet 6.0.300 in mac. But, while trying to run dotnet test, it throws : : error MSB3644: The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application.

**Comment by Minik1337** [comment] 2022-08-29 21:11
I have finally found a solution to this problem!

If for any reason you are still using .NET Framework version for which there is no SDK, then here is my solution to the problem.

![image](https://user-images.githubusercontent.com/39024297/187297610-92a70372-1b63-4ecb-a989-9776c94bd6b4.png)

This problem is solved by directly downloading the package via NuGet. We go to https://www.nuget.org/ and we are looking for `Microsoft.NET.Framework.Reference.Assemblies`, select the desired version and download the package directly.

![image](https://user-images.githubusercontent.com/39024297/187298141-f6c5ae52-848c-4d92-aa89-67d85d0250e1.png)

Now open .nupkg file as archive, go to `/build/.NETFramework/` and unpacking folder with version in this funny path `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework` (If the folder with the current version already exists, just delete it). Should look like this:

![image](https://user-images.githubusercontent.com/39024297/187299475-3111be8a-7028-4003-a0fe-19b81fd979cc.png)


Everything should work now!

==================================================================================

If you somehow keep a project that uses .NET Framework 2.0 or 3.0 or 3.5, here is the following solution for you!

Open start, type "Windows Features" and check .NET Framework 3.5 (includes .NET 2.0 and 3.0).

![image](https://user-images.githubusercontent.com/39024297/187298941-df82244a-400b-43d1-a638-14dc41621ffc.png)

**IT IS NECESSARY THAT WINDOWS UPDATES ARE ENABLED OTHERWISE IT WILL NOT WORK**

==================================================================================

**Comment by Minik1337** [comment] 2022-08-29 21:12
I have finally found a solution to this problem!

If for any reason you are still using .NET Framework version for which there is no SDK, then here is my solution to the problem.

![image](https://user-images.githubusercontent.com/39024297/187297610-92a70372-1b63-4ecb-a989-9776c94bd6b4.png)

This problem is solved by directly downloading the package via NuGet. We go to https://www.nuget.org/ and we are looking for `Microsoft.NET.Framework.Reference.Assemblies`, select the desired version and download the package directly.

![image](https://user-images.githubusercontent.com/39024297/187298141-f6c5ae52-848c-4d92-aa89-67d85d0250e1.png)

Now open .nupkg file as archive, go to `/build/.NETFramework/` and unpacking folder with version in this funny path `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework` (If the folder with the current version already exists, just delete it). Should look like this:

![image](https://user-images.githubusercontent.com/39024297/187299475-3111be8a-7028-4003-a0fe-19b81fd979cc.png)


Everything should work now!

==================================================================================

If you somehow keep a project that uses .NET Framework 2.0 or 3.0 or 3.5, here is the following solution for you!

Open start, type "Windows Features" and check .NET Framework 3.5 (includes .NET 2.0 and 3.0).

![image](https://user-images.githubusercontent.com/39024297/187298941-df82244a-400b-43d1-a638-14dc41621ffc.png)

**IT IS NECESSARY THAT WINDOWS UPDATES ARE ENABLED OTHERWISE IT WILL NOT WORK**

==================================================================================

**Comment by JulieWasNotAvailable** [comment] 2022-09-12 09:10
Hi! Minik1337, your solution seems like it should work, but for some reason I have a bunch of errors trying to unpack /build/.NETFramework/ into \.NETFramework. And it was also named .NETCore, for some reason.
![image](https://user-images.githubusercontent.com/113335515/189615757-ed0246fe-180f-45f7-875e-2321c0eea324.png)

Could you help me out, please?

**Comment by FixRM** [comment] 2023-03-27 19:21
Hello. Why this issue is closed? It is not fixed at all. I'm currently struggling with SSRS project. It builds perfectly in VS 2022 with this extension: https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftReportProjectsforVisualStudio2022, but fails with `Version=v4.0 were not found` error in CI/CLI. Build somehow works in VS but still doesn't work in CI even using latest VS 2022. I guess there should be any parity between VS/MSBuild builds, no? Why do they behave different? Are any magic CLI parameters for them to work same?

**Comment by AdamYoblick** [comment] 2023-03-30 19:50
@FixRM This issue was for python projects specifically. The issue is fixed in the targets file for PTVS. I'm not sure about SSRS projects.

In any case, please see my root cause comment (https://github.com/microsoft/PTVS/issues/6747#issuecomment-1015704916) for a workaround. You should be able to pass in the `TargetFrameworkVersion` property on the command line (using `/p:TargetFrameworkVersion=xxxxx` or something similar).

And no, msbuild and VS are not exactly the same. :) If you want more a more detailed log of steps that ran, try specifying a binary log path with the `/bl:pathToFile` CLI argument, then you can open the binary log using the [MSBuild Log Viewer](https://msbuildlog.com/)

**Comment by FixRM** [comment] 2023-04-03 05:58
Thanks, @AdamYoblick. It worked

**Comment by Shezorkhan** [comment] 2023-06-27 10:15
![VS_ERROR](https://github.com/microsoft/PTVS/assets/137886639/1da7a7b0-087a-45e2-b4af-f770276e59db)

I'm getting an error during "Build" time. could someone suggest solution.

""""""""""""Severity	Code	Description	Project	File	Line	Suppression State
Error		The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	[AEITagDecoding""""""""""""""""""""]		


Thank you
