### ISSUE TITLE
Python built in methods show up in debugger

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6274] opened 2020-10-03 00:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1206288/python-built-in-methods-show-up-in-debugger.html)._

---
[severity:It's more difficult to complete my work]
I'm Trying to debug a simple python code, and the "locals" window displays built in list methods (append, __ init __ ,etc.)
I couldn't find a toggle in the options to hide built in methods in python in the debugger windows

---
#### Feedback Bot on 10/1/2020, 10:18 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment] 2020-10-03 00:21
This is a good suggestion, the watch window now looks pretty busy/noisy with all of these and it would be nice to have an option to hide them.

**Comment by huguesv** [comment] 2020-10-07 22:15
https://github.com/microsoft/ptvsd/issues/1621#issuecomment-616581823

We can add 4 options to tools/options/python/debugging for 'special', 'class', 'function' and 'protected' with values 'group', 'inline', 'hide'.

**Comment by madav-tech** [comment] 2020-10-11 06:11
Hi, I opened the initial request.
That would be very good, keep in mind that unlike the specification you added I'm not talking about VSCode but about Visual Studio 2019, just making sure you're aware of that

**Comment by madav-tech** [comment] 2020-10-27 08:05
Bump @huguesv

**Comment by judej** [comment] 2021-01-06 23:39
dupe of #6334

**Closed by judej** 2021-01-06 23:39 UTC
Labels: area:Debugger (VSC), enhancement, resolution:duplicate
