### ISSUE TITLE
Search path in 2.2 ignored?

### ISSUE THREAD

**Issue by bergfruehling** [Microsoft/PTVS#665] opened 2015-08-01 13:12 UTC
When I add folders to the search path in a PTVS project, it is not added to the python environment, i.e. it does not show up in sys.path and no modules from these folders are found. I'm using VS 2015 community + PTVS 2.2 on Win 10. I tried both Python 2.7 and Python 3.4 (winpython distribution).

However, it works with VS 2013 + PTVS 2.1 on a Win 7 machine.

**Comment by int19h** [comment] 2015-08-01 19:30
Since you're using WinPython, you have probably set it up as a custom interpreter? If so, check that the "Path environment variable" in interpreter settings is actually set to `PYTHONPATH`.

**Comment by bergfruehling** [comment] 2015-08-02 08:16
Thanks, now it works! In fact, I did not "register" my two python environments (2.7, 3.4), i.e. there was no PYTHONPATH at all. I thought PTVS ignores the PYTHONPATH anyways, in order to support multiple environments better.

I just registered the 2.7 environment and now it works with both version.

**Comment by int19h** [comment] 2015-08-02 08:23
PTVS does not respect the PYTHONPATH that you set (by default; this can also be changed in options). What this property is for, is to tell it which variable _it_ should set (based on your Search Path entries) before it launches python.exe. In other words, which variable the interpreter will be using. So when it's not set, it doesn't set anything. This is actually a bug (#211) in that not setting that property should just default to PYTHONPATH, since that's what it is 99% of the time - since we already have an item to track it, I'll close this one.

**Comment by int19h** [comment] 2015-08-02 08:24
Dupe of #211.

**Closed by int19h** 2015-08-02 08:24 UTC
Labels: duplicate

**Comment by sma202** [comment] 2016-04-21 22:44
how do we get around this?

**Comment by zooba** [comment] 2016-04-21 23:01
Have you tried following the solution in the second post? And are you sure you're having the same issue?
