### ISSUE TITLE
An error appears in the error list after creating a new project

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6562] opened 2021-06-08 08:21 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/121148127-0e808f80-c874-11eb-99e4-e42089f12a66.png)

**Steps to Reproduce**

Create a Python Application project.

**Expected behavior**

It should create successfully.

**Additional context and screenshots**

An error appears in the error list.
![image](https://user-images.githubusercontent.com/82852072/121148852-b8601c00-c874-11eb-8f29-cbc153db501a.png)

**Comment by rchiodo** [comment] 2021-06-08 15:26
I think this would be a bug in the Microsoft.Common.Current... file. Probably a targets file that was installed that has an error in it.

**Comment by rchiodo** [comment] 2021-06-08 15:29
Or perhaps we're referring to one that has other dependencies.

**Comment by rchiodo** [comment] 2021-06-08 15:32
Yeah this is a dupe of this:
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1337398

**Closed by rchiodo** 2021-06-08 15:32 UTC
Labels: needs triage
