### ISSUE TITLE
Python Workload for VS 2022 Pro does not exist on Surface Pro 11 (ARM64)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7985] opened 2024-08-21 17:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-Workload-for-VS-2022-Pro-does-not/10725068)._

---
[severity:I'm unable to use this version]
I just bought a new Surface Pro 11 and now can't use VS Pro 2022 to develop python applications. This is supposed to be an AI-driven device, but it doesn't support one of the primary programming languages used for many AI-driven applications. Is there any kind of simple workaround for this? What is the expected date for the Python Workload for VS Pro 2022 on ARM64? I can't even do non-AI-driven Django apps easily anymore or import/update my existing web apps if I use this device and VS Pro 2022.

---
#### andre.ziegler on 8/17/2024, 05:03 AM: 

(private comment, text removed)
#### Scott Barnard on 8/17/2024, 11:08 AM: 

(private comment, text removed)
#### Feedback Bot on 8/19/2024, 00:19 AM: 

(private comment, text removed)
#### andre.ziegler on 8/19/2024, 00:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-09-10 22:49
dupe of https://github.com/microsoft/PTVS/discussions/7788. Please upvote the discussion item if you'd like to see it being supported. Thanks.

**Closed by StellaHuang95** 2024-09-10 22:49 UTC
Labels: needs repro
