### ISSUE TITLE
Error evaluating expression

### ISSUE THREAD

**Issue by a-j-albert** [Microsoft/PTVS#5260] opened 2019-04-25 07:44 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.9.18254.1

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.PythonTools.Repl.PythonDebugProcessReplEvaluator..ctor(IServiceProvider serviceProvider, PythonProcess process, IThreadIdMapper threadIdMapper)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<AttachProcessAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<OnReadyForInputAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment] 2019-04-25 17:29
Duplicate of https://github.com/Microsoft/PTVS/issues/5260 

This only occurs if legacy debugger is enabled (tools/options/python/debugging) so if you can avoid using legacy debugger, that should avoid this error. You do lose the ability to paste in debug repl though (we've fixed that in dev16).

**Closed by huguesv** 2019-04-25 17:29 UTC
