### ISSUE TITLE
Linting not working with Python 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6625] opened 2021-07-28 22:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Linting-not-working-with-Python/1485968)._

---
[severity:It's more difficult to complete my work]
I am intentionally writing errors and linting does not appear to be working at all in this build of VS 2022.

---
#### Feedback Bot on 7/26/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Jude Kavalam [MSFT] solved on 7/28/2021, 03:49 PM, 0 votes: 

We moved this issue to a relevant GitHub project. Please comment and track it at this URL: https://github.com/microsoft/PTVS/issues/6624

**Comment by greazer** [comment] 2021-07-28 23:11
Dupe of #6624

**Closed** 2021-07-28 23:11 UTC
