### ISSUE TITLE
Debugger issue with files in separate projects with same names

### ISSUE THREAD

**Issue by traits** [Microsoft/PTVS#1292] opened 2016-05-15 15:52 UTC
PTVS 2.2.40315.00, VS 2015 Community Update 1, WinPython 3.4.4.2Qt5

When starting a project from debugger, I'm getting every once in a while spurious breaks in my code without any breakpoints set at the positions in question. These breaks can be quite tenacious and are able to render debugging almost useless.

For the moment I cannot roll back my Python installation - but could it be, that Python packages with dependencies to C/C++ code compiled with the Intel compiler, are responsible? 
As an example, I'm utilizing numpy-1.11.0+mkl-cp34-cp34m-win_amd64.whl and scipy-0.17.1-cp34-cp34m-win_amd64.whl from Gohlkes site (http://www.lfd.uci.edu/~gohlke/pythonlibs/).

Maybe I'm completely wrong, but any help would be appreciated.

**Comment by zooba** [comment] 2016-05-16 16:21
Do you have native debugging enabled?

Alternatively, do any of your Python files have matching names? We use some simple heuristics to figure out where breakpoints are located, and if you have same-named files then in some cases you'll hit breakpoints in either of them instead of the actual one.

**Comment by traits** [comment] 2016-05-16 22:07
No native debugging turned on, but this

> same-named files

seems to be responsible, I had some breakpoints set in the 'wrong' file, clearing them was some kind of remedy. 
But these files are in different projects (albeit the same solution). In my opinion, this should not happen yet on project level and under no circumstances solution-wide.

**Comment by zooba** [comment] 2016-05-17 15:38
Agreed, it's not ideal, though it does enable some situations where breakpoints would otherwise not work at all.

We'll follow up and see if we can improve it.

**Comment by huguesv** [comment] 2017-12-14 19:56
Duplicate of https://github.com/Microsoft/PTVS/issues/176 which we decided to won't fix.

**Closed by huguesv** 2017-12-14 19:56 UTC
Labels: area:Debugger, bug, resolution:duplicate
