### ISSUE TITLE
17.10.3 rollback to 17.6.4 due to error on startup from multi python project solution

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7946] opened 2024-07-10 15:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/17103-rollback-to-1764-due-to-error-/10697120)._

---
[regression] [worked-in:17.6.4]
I migrated from VS2022 version 17.6.4 to 17.10.3. But I rolled back again, since one of my multi-python-project solutions results in an error. See the error report here below.

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Sluiten]

[Expanded Information]
```
Build: 17.0.24064.1

Microsoft.VisualStudio.CommonIDE.Solutions.HResultExtensions+WrapperCOMException (0x8000FFFF): Onherstelbare fout (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222] ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Onherstelbare fout (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) [FindActiveProjectCfg @ SolutionBuildManager.cs:2222]
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudioTools.Project.ProjectNode.SetCurrentConfiguration()
   at Microsoft.PythonTools.Project.PythonProjectNode.SetCurrentConfiguration()
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetMsBuildProperty(String propertyName, Boolean resetCache)
   at Microsoft.VisualStudioTools.Project.ProjectNode.GetProjectProperty(String propertyName, Boolean resetCache)
   at Microsoft.PythonTools.Project.CondaEnvCreateProjectInfoBar.<CheckAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

---
#### Feedback Bot on 7/4/2024, 07:01 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-07-17 21:59
Thanks for reporting the issue. This is a duplicate of https://github.com/microsoft/PTVS/issues/7930. The same issue has been reported a few times, we will investigate further to reproduce and address this issue accordingly.

**Closed by StellaHuang95** 2024-07-17 21:59 UTC
Labels: duplicate
