### ISSUE TITLE
when I try to 'pip install kivy' I cant find anywhere in visual studio kivy and cant import kivy

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7513] opened 2023-04-12 20:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/when-I-try-to-pip-install-kivy-I-cant-/10331403)._

---
[severity:It's more difficult to complete my work]
I have dowloaded the kivy file and tried pip install kivy. 

When i try using kivy in visual studio it wont work.

---
#### Feedback Bot on 4/5/2023, 00:27 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-04-13 22:50
Hi there, this is a duplicate of https://github.com/microsoft/PTVS/issues/7068. Fix is here: https://github.com/microsoft/PTVS/pull/7401

The issue should be fixed in the next version.

**Closed by StellaHuang95** 2023-04-13 22:50 UTC
Labels: needs triage
