### ISSUE TITLE
Auto complete does not work for the sqlite3 module

### ISSUE THREAD

**Issue by Orionsg** [Microsoft/PTVS#1477] opened 2016-07-26 09:28 UTC
Example code:
```
test_db = sqlite3.connect('c:/t/test.db')
rows = test_db.
```
Typing the above, getting to "... test_db." the auto complete drop down list will just state: 
"No completions"

When using similar code inside a class, instead of the "No completions", I sometimes get meaningless, basic suggestions like:
`__bool__, __class__, __delattr__, __dir__, __doc__`

Now, when using the same code in the Visual Studio Python 3.5 interactive window, the auto complete works as expected. 

<b>Version information:</b>
Visual Studio Community 2015, version 14.0.25421.03 Update 3
Python Tools for Visual Studio 2.2.40623.00
Python 3.5.2

**Comment by zooba** [comment] 2016-07-26 16:02
Thanks! This is a known limitation of what our analysis engine is capable of doing - unless the code implementing a function is obvious enough about what it returns, we don't know what it returns (and `sqlite3.connect` is not obvious enough).

In the interactive window, you actually execute the code and open the database, so we can inspect the live object. In the regular editor, we don't run the code that you type (so that it's safe to type for example `shutil.rmtree("C:\\")` - **don't** type that into the interactive window ;) ) so we can't inspect the actual returned value.

Hopefully when type hints are fully supported and there are hint files available for the standard library, issues like this will be resolved. We have other issues tracking that, so I'll close this one.

**Closed by zooba** 2016-07-26 16:02 UTC

**Comment by Orionsg** [comment] 2016-07-27 05:50
Thanks a lot for the detailed explanation!

From just briefly looking at type hinting via a search, It seems that type hinting is still some way off, and thus by implication auto completion in VS for this type of libraries. I think that VS is a great editor to use for Python. The colour coding and fonts are really good, and its great with the interactive pane. 

However, auto complete is what makes PTVS really great. Of course, everyone will claim that the particular module that they are using is important, but database modules in general and sqlite3 in particularly are very essential and widely used in applications. Thus, I find it unfortunate that there are no direct auto complete help in the editor when using them. 

Could there not be a separate thread looking through the library and at least list the methods that are available together with just the name of the parameters -- extensive type information and explanations could be added later as ways to obtain it was devised (e.g. type hinting).

The PyCharm editor does supply a basic auto complete information: 
"execute (self, sql, parameters)    Connection"

For the modules that are supported, I like VS' more extensive information about the method and it's parameters, but until that can be available the above would quite sufficient.

**Comment by zooba** [comment] 2016-07-27 15:25
We do show the name and parameters of methods we can find, the problem is the return type. In your original example, we have no way of knowing the type of `test_db`, so we can't show any methods (alternatively, we can show every single method that exists on every single object, which I hope is obviously a bad idea :) ).

Other issues are taking priority right now, but when we support type hints you'll be able to use the files from [typeshed](https://github.com/python/typeshed/) to get all the information for the standard library.

**Comment by Orionsg** [comment] 2016-07-27 16:45
I guess that PyCharm must then be using typeshed as well. However, I find VS a much nicer IDE, which I am also using for other languages.

Thanks for clarifying. 
I look forward to the type hints support.
