### ISSUE TITLE
ModuleNotFoundError in Output window for pytest in project.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5548] opened 2019-08-07 07:45 UTC
**Steps to Reproduce**
1.Create python application named PythonApplication3
2.Right click in project and select New->New Folder, renamed folder as testing
3.Right click in testing folder and select Add->New item->Python Unit test
4.Make sure test1.py should be added under testing folder
5.Right click in project and select Properties ->Test, and change Test Framework to "Pytest"

**Expected behavior**
no any error happened and test1 could be found in Test Explorer
**Actual behavior**
ModuleNotFoundError happened
![image](https://user-images.githubusercontent.com/39871640/62604120-efd4a900-b929-11e9-8173-9ad53cd5fb99.png)

**Solution**: If I delete the default python file(PythonApplication3.py) when I created the project,  tests could be found in Test Explorer and no errors

**Test environment**:
![image](https://user-images.githubusercontent.com/39871640/62604338-6e314b00-b92a-11e9-96c6-377669f2ec5a.png)

**Comment by huguesv** [comment] 2019-08-07 22:32
Duplicate of https://github.com/microsoft/PTVS/issues/5461

**Closed by huguesv** 2019-08-07 22:32 UTC
Labels: area:Test Adapter, needs triage
