### ISSUE TITLE
It jump to breakpoint directly when pressing F10 or F11

### ISSUE THREAD

**Issue by xiaofeng0123** [Microsoft/PTVS#5259] opened 2019-04-25 06:59 UTC
VS Version: 16.1.0 Preview 3.0 [28824.243.d16.1stg]
Python Tool Version: 16.1.19113.1

Repro step:
1. Create a python application
2. Input below code :
```
from math import cos, radians
def make_dot_string(x):
    rad = radians(x)                            
    numspaces = int(20 * cos(radians(x)) + 20)   
    st = ' ' * numspaces + 'o'  
    return st
def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
        print(s)
main()
```
3. Set a breakpoint on "for" line
4. Press F10 or F11

Actual Result:
It jump to breakpoint directly
![image](https://user-images.githubusercontent.com/41426540/56715410-3252eb00-676a-11e9-98ba-dbb7faf47f60.png)

Expect Result:
It should stop on "from math import cos, radians" line

**Comment by huguesv** [comment] 2019-04-25 17:19
Duplicate of https://github.com/Microsoft/PTVS/issues/5193

**Closed by huguesv** 2019-04-25 17:19 UTC
