### ISSUE TITLE
how to set drive and directory for my .py files

### ISSUE THREAD

**Issue by durbinjw** [Microsoft/PTVS#1021] opened 2015-12-08 17:12 UTC
being new at this, I am still asking very basic questions.

How do I set the the drive and directory location for my files?  The tutorial just says enter some code into a file in the "current directory", but I have not found where that can be specified.  I am running VS 2015 Update 1 and PTVS 2.2.2.

Jim

**Comment by zooba** [comment] 2015-12-08 21:30
Basic questions are fine. In this case, it depends on how you're handling the code files.

If you've created a Python project, right-clicking the project and selecting Properties, then Debug will give you a field where you can set the Working Directory (by default it will be the directory containing the `.pyproj` file). When you start running the code with F5 it will be in that directory.

If you're using a `.py` file on its own without a project, the "Start with/without Debugging" commands should start in the directory that contains the file.

In the interactive window, it will depend on a few other things (and frankly it's not very obvious - I'm working on improving this for our next release already). To check which directory it's in, type `import os; os.getcwd()`, and then you can use `os.chdir(r"C:\Path")` to change it.

So in brief: if there's a project we start in the project directory (and you can customize it); if there's a file we start in the file's directory; if there's no file then you should check using the `os` module.

**Comment by durbinjw** [comment] 2015-12-09 17:32
Thanks

That helps.

It seems that you are a primary developer of PTVS.  I really appreciate your giving me some attention.

May I suggest that a default User Source directory setting be added to Tools | Options | Python Tools | EnvironMentOptions. I see that there are Environment Settings for Path, Windows Path, and Library Path, but they are disabled and point to python.exe, pythonw.exe, and lib, which I am pretty sure should not be changed.  I would like to be able to have all of my projects and .py in a directory H:\Python on this system.

Re the directory settings for python projects.  the code was able import fibo.py from H:\Python on this system after entering H:\Python in the project properties | Debug dialog in the Run | Search Paths: entry.  A search of the C Drive found c:\Users\Jim\AppData\Local\Temporary Projects\PythonApplication1\PythonApplication1.pyproj  and a search of the entire C drive found 
20 more files in c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplatesCache\Python\ in multiple subdirectories.  I am not sure whether that was what you were point me to.

I have only completed 4 sections of the Python tutorial and expect there will be further questions.  I have some significant projects in mind, and think that the Sets features will be of great help when analyzing large amounts of data with some advanced mathematics.  I will be wanting to produce graphic displays of the results.

I am a long time developer of applications with the majority of my experience being with C, C#, and Visual Basic using Visual Studio.  My current orientation is toward two areas; Public Health Laboratory Information Systems, and Gravity / Relativity research.

I am receiving email notifications of answers with your real(?) name and assume you would prefer keeping it out of these posts.  

Thanks again.

Jim

**Comment by durbinjw** [comment] 2015-12-11 00:22
It is getting better but still not quite what I am expecting:  I think there is probably some documentation that I have not found yet that describes the usage of environment and its settings.  If you could point me in that direction, it would reduce my questions.

I found that in PythonEnvironment | Configure, I can add, remove, and configure an environment.  I see that there is a  Path environment variable.  The tool tip says that it is is used to specify search paths that should be added to sys.path.  I set this to H:\Python and clicked the Apply button.  I am expecting two things:

1.  Sys.path should now show H:\Python
2.  Typing 'import f' autocompletion should show fibo1 as being in that directory.

Neither expectation is correct.

1.  How do I make H:\Python always be the working directory?
2.  How do i get import to show the list of .py files that are in that directory and allow me to select one or more of them?
3.  Where is PYTHONPATH and how do I set it so that it sticks?

Jim

**Comment by int19h** [comment] 2015-12-11 00:51
Path environment variable is the _name_ of the environment variable that this particular Python uses for PYTHONPATH. In other words, this is the variable that PTVS will set when you specify a custrom path. Normally, it should be "PYTHONPATH" :)

Custom search path is defined on a per-project basis. If you look in Solution Explorer, the project has a Search Paths node; that has a context menu to add entries. You can also add them in project properties.

Note though that search path is different from current working directory - it's only used by `import`, and not by other filesystem functions etc. As Steve has noted above, the working directory is set via Working Directory textbox on the Debugging tab in project properties.

(Side note: as Microsoft employees, we all use our real names for GitHub accounts, and it's public in the profile, so don't worry about that.)

**Comment by durbinjw** [comment] 2015-12-11 22:32
I am still having difficulty.  Maybe this series of screen shots will help.  In the interactive window, I am expecting to see fibo1 listed.  What am I missing?  Why isn't fibo1 included in the list of functions shown?  

Here is what I see in the interactive window when attempting to import fibo1
![interactive window](https://cloud.githubusercontent.com/assets/4181451/11756952/55a63d82-a012-11e5-9398-317b7cd1481c.png)

Here is the Windows environment setup showing PYTHONPATH is pointed to the H:\Python directory.

![windows environment setup](https://cloud.githubusercontent.com/assets/4181451/11756968/7be0ae06-a012-11e5-9b35-ba19891c2519.png)

Here is the JimPython environment configuration

![jimpython configuration](https://cloud.githubusercontent.com/assets/4181451/11757010/c8263448-a012-11e5-90fb-0ba3c1cc425a.png)

Here is the windows explorer view of the H:\Python directory

![python directory contents on h drive](https://cloud.githubusercontent.com/assets/4181451/11757023/ec45df36-a012-11e5-8edd-5e6244a204df.png)

And finally, this is the contents of the fibo1.py file - copied from the tutorial.

![fibo1 py contents](https://cloud.githubusercontent.com/assets/4181451/11757038/09f5c56e-a013-11e5-95cc-cb7e1556c782.png)

**Comment by int19h** [comment] 2015-12-11 23:41
Make sure that you open the REPL window after you open the project (if you already had it opened, reset it). It won't transparently change the working directory, to avoid magic state changes.

Also, the completions are not always 100% correct (though they should generally be more correct in the REPL). Try running the import regardless, and see if that works.

With respect to `PYTHONPATH`, note that the value that `PYTHONPATH` is set to globally doesn't actually matter - PTVS will override it with the current search path for the project with default settings:

![image](https://cloud.githubusercontent.com/assets/1175142/11758175/d3d4644a-a01c-11e5-9378-81e1c3da9d96.png)

If you want your global `PYTHONPATH` setting to be utilized, uncheck the "Ignore system-wide PYTHONPATH variables" option in this dialog.

**Comment by durbinjw** [comment] 2015-12-12 00:17
I am too new to even understand your answer. I do not have a project to open, I am attempting to go directly to the Interactive window.  Does a project have to be created and opened before going to the interactive window?  By REPL do you mean the interactive window?  I unchecked that box in the Python tools dialog.  In the interactive (REPL?) window, import fibo1 returns "ImportError: No module named 'fibo1'.  I created a new Python Application in VS and in the PythoneApplication1.py window, import fibo1 returns nothing, but fibo1 is underlined, and placing the cursor over it shows "fibo1: <unknown type> Unable to resolve "fibo1": IntelliSense may be missing for this module.

**Comment by int19h** [comment] 2015-12-12 00:29
Sorry for the confusion. Yes, a REPL is an informal (and non-VS-specific) term for what's properly called Python Interactive tool window in VS.

If you have created a new Python Application via File -> New Project, then you do have a project - you should be seeing it in Solution Explorer tool window (on the right by default). If you have closed and reopened VS since you've created it, then you'll need to reopen the project as well - you should see it in the list of recent projects under File -> Recent Projects and Solutions.

When you do have a single project open, the Interactive window should pick up the working directory from it if you reset it (using the toolbar button in that window). From there you should be able to import modules _from your project_ (i.e. if it contains fibo1.py, then it should be importable).

I think my mistake was assuming that this is what you're really trying to do - importing a module that is a part of your project. If it's really a completely separate thing in its own directory, then you will need to set `sys.path` accordingly, either via `PYTHONPATH` or directly. The simplest way to do so is to run this in the REPL:
```py
import sys
sys.path.append(r'H:\Python')
```
(This might not update Intellisense immediately, but your `import` should still work when you run it.)

The problem is that you'll need to do it every time you reset the window, or quit VS. Setting `PYTHONPATH` in Windows environment variable settings will allow you to specify it globally in a persistent way. To make PTVS see the new value, make sure that the checkbox is unchecked, and then restart VS (in general, processes don't see global changes in environment variables on Windows that happen after the process has been started; this also applies to `PATH` etc). After that, your import should work. Again, the code completion might not show the module in the list right away; just try to type it manually and see if it works when you run it.

However, my recommendation is to use a project, and put the file there.

**Comment by LeeRuns** [comment] 2016-10-04 14:11
I'm fairly comfortable with python.  It's not my best language, but I have setup basic django websites, performed data analysis. etc..my point being I get python, but when i run it in VS I always hit problems.  I actually prefer linux programming environment, but the server tools, and sql object explorers are really nice so I want to be able to run python in visual studio.

Right now I don't think that VS is actually picking up all of the files in the project I created when I hit "F5".  They are all in the same directory.  That directory contains the pyproj file.
1. _how do i run just one of the python files?_
2. _how do i run all of the files?_
3. _how do i run only some of the files?_
4. _how should i add new .py modules so that they are automatically included when i hit F5?_

here it is in windows explorer:
![image](https://cloud.githubusercontent.com/assets/15914558/19076657/f38150e4-8a06-11e6-8639-4a954d90bae3.png)

here it is in the solution explorer
![image](https://cloud.githubusercontent.com/assets/15914558/19076714/268f32d0-8a07-11e6-9b1d-aa119cfc66b7.png)

I always seem to have an easier time running python outside of visual studio than inside of visual studio, so clearly there are some issues with my comprehension as to how the PTVS differs from python.

**Comment by zooba** [comment] 2016-10-04 17:31
One easy way to run any single file is to right-click it (either in Solution Explorer on in the editor) and select "Start without debugging" or "Start with debugging".

Currently this does not allow you to specify arguments (we have a feature request for that part), so if you are repeatedly specifying command line arguments you can put those in Project Properties (right click the project, select Properties and then the Debug tab). You can right-click any file in Solution Explorer and "Set as startup script", which will then let you run that file with F5 (or Ctrl+F5 without debugging) and the arguments will be passed through.

If you need more search paths (e.g. setting `PYTHONPATH`), you can right click Search Paths and add them there. Those will be used no matter how you start running the script.

**Closed** 2016-12-27 19:12 UTC
Labels: question
