### ISSUE TITLE
Make navigation bar work with Python symbols

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7661] opened 2023-06-30 14:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Make-navigation-bar-work-with-Python-sym/10390671)._

---
The navigation bar is invaluable for C++ and C# projects. It is very useful to be able to see the list of projects, scopes, and symbols (callable unit, class, field, etc.) available, and to be able to navigate to those symbols by using a few dropdown menus.

This would be incredibly useful for Python as well.

Curiously, GitHub (which is a Microsoft service/product, and is tied closely to Visual Studio) has a symbol navigator that works with Python source code files.

[Here is a video](https://aka.ms/dc/file?name=B3ee5c3bfe9384dd9965854c56e46754c638222654196122072_Recording_2023-06-13_230253.mp4&tid=3ee5c3bfe9384dd9965854c56e46754c638222654196122072) that demonstrates the current behaviour of the navigation bar with Python source code files.

---
#### Feedback Bot on 6/13/2023, 10:31 PM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment] 2023-06-30 17:01
Hi there, thanks for bringing up the issue. We have added this to our backlog as an enhancement and is tracked here: https://github.com/microsoft/PTVS/issues/6551. Feel free to please feel free to share any additional thoughts or ideas to the ticket. Thank you! Closing as duplicate of https://github.com/microsoft/PTVS/issues/6551

**Closed by StellaHuang95** 2023-06-30 17:01 UTC
Labels: needs triage
