### ISSUE TITLE
Intellisense not working in XAML Editor with IronPython

### ISSUE THREAD

**Issue by warcreap** [Microsoft/PTVS#3002] opened 2017-09-06 14:02 UTC
Hello,

i freshly installed VS2017 Professional yesterday. Today I noticed, that IntelliSense is not working in XAML-Files within an IronPython project. I checked, whether it does work in C#-Projects, and it does.

```
Version Info:
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02053

Installierte Version: Professional

Visual Basic 2017   00370-10001-07431-AA643
Visual C# 2017   00370-10001-07431-AA643
Visual C++ 2017   00370-10001-07431-AA643
Visual F# 4.1   00370-10001-07431-AA643
Allgemeine Azure-Tools   1.10
Application Insights-Tools für Visual Studio-Paket   8.8.00712.1
ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET Core Razor Language Services   1.0
ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
Azure App Service-Tools v3.0.0   15.0.30728.0
Cookiecutter   3.0.17208.1
GitHub.VisualStudio   2.2.0.10
JavaScript-Sprachdienst   2.0
JavaScript Project System   2.0
JavaScript UWP-Projektsystem   2.0
Microsoft Azure-Tools   2.9
Microsoft Continuous Delivery-Tools für Visual Studio   0.3
Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0
Microsoft Visual C++-Assistenten   1.0
Node.js Tools   1.0.0.0
NuGet-Paket-Manager   4.3.1
Office Developer Tools für Visual Studio 2017 – DEU   15.0.26712
Python   3.0.17208.1
Python – Django-Unterstützung   3.0.17208.1
Python – IronPython-Unterstützung   3.0.17208.1
Python – Unterstützung für die Profilerstellung   3.0.17208.1
Python – UWP-Unterstützung   3.0.17208.1
SQL Server Data Tools   15.1.61707.200
TypeScript   2.3.4.0
VC-Paket für Microsoft Visual Studio   1.0
Visual Studio-Tools für Apache Cordova   15.120.6728.1
Visual Studio-Tools für CMake   1.0
Visual Studio Code Debug Adapter Host Package   1.0
Visual Studio Tools für universelle Windows-Apps   15.0.26730.08
Workflow Manager Tools 1.0   1.0
```

I am running Windows 7, if it does matter.

Am I maybe missing a Module, or something?

Any help would be appreciated! Thanks.

**Comment by huguesv** [comment] 2017-09-06 16:13
We discovered this recently too, and are not sure why it doesn't work.
Closing as duplicate of https://github.com/Microsoft/PTVS/issues/2943

**Closed by huguesv** 2017-09-06 16:13 UTC
Labels: duplicate
