### ISSUE TITLE
Missing navigation bar -- 2022 Preview 3, Python project.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6707] opened 2021-09-01 22:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Missing-navigation-bar----2022-Preview-3/1516770)._

---
When I have a Python file open in the text editor, the navigation bar does not appear.
I did tick the Navigation Bar item in Tools/Options/Text Editor/(All Languges and Python).
I also opened a C++ file and the navigation bar does appear there.
Version 17.0.0 Preview 3.1.

---
#### Feedback Bot on 8/30/2021, 00:58 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by rchiodo** [comment] 2021-09-01 22:06
Dupe of #6551

**Closed by rchiodo** 2021-09-01 22:06 UTC
