### ISSUE TITLE
VS2022 ERROR,找不到.NETFramework,Version4.0 - VS2022 Error, failed to find .NETFramework,Version4.0

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6835] opened 2021-12-30 00:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS2022-ERROR找不到NETFrameworkVersion40/1591410)._

---
[regression] [worked-in:VS2019]
在升级到2022版后，在问启动项目的情况下，错误列表窗口显示：
错误		找不到 .NETFramework,Version=v4.0 的引用程序集。要解决此问题，请为此框架版本安装开发人员工具包(SDK/目标包)或者重新定向应用程序。可在 https://aka.ms/msbuild/developerpacks 处下载 .NET Framework 开发人员工具包	PythonApplication1	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217

目前我用的windows11。因为系统集成了net framework4.0，并且VS2022无法支持net framework4.0。我也无法安装这个补丁

---
#### Tracy Wang [MSFT] on 11/22/2021, 01:26 AM: 

<p>Translated by Bing:<br>
After upgrading to version 2022, when asked to start the project, the error list window displays:</p>
<p>Error Cannot find the reference assembly for .NETFramework,Version=v4.0. To solve this problem, please install the developer kit (SDK/target package) or redirect the application for this framework version. You can download the .NET Framework Developer Toolkit PythonApplication1 at <a target='_blank' href="https://aka.ms/msbuild/developerpacks">https://aka.ms/msbuild/developerpacks</a> C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion .targets 1217</p>
<p>Currently I use windows11. Because the system integrates net framework 4.0, and VS2022 cannot support net framework 4.0. I can’t install this patch either.</p>

#### Feedback Bot on 11/22/2021, 02:22 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### 3326564077@qq.com on 11/22/2021, 11:10 PM: 

<p><img src="https://aka.ms/dc/image?name=B21ba82886de54e32895a1083ddf4c24f637732482064886512_20211123-151007-image.png&amp;tid=21ba82886de54e32895a1083ddf4c24f637732482064886512" alt="image.png"></p>

#### 3326564077@qq.com on 11/22/2021, 11:14 PM: 

<p><img src="https://aka.ms/dc/image?name=B8826a9d815cc42d7bc16b0a472bddef1637732484128197595_20211123-151333-image.png&amp;tid=8826a9d815cc42d7bc16b0a472bddef1637732484128197595" alt="image.png"></p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-01-05 22:22
Dupe of #6747

**Closed** 2022-01-05 23:15 UTC

**Comment by JulieWasNotAvailable** [comment] 2022-09-12 08:07
I have the same problem, but I can't open images from [3326564077@qq.com](mailto:3326564077@qq.com) 
What should I do?
