### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7208] opened 2022-11-01 18:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10181158)._

---
[regression]
**Describe your issue here**  
  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 10/25/2022, 06:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-01 20:27
duplicate of #7197

**Closed by StellaHuang95** 2022-11-01 20:27 UTC
Labels: needs triage
