### ISSUE TITLE
No Completion in IronPython environment when referencing a C# library (VS2019)

### ISSUE THREAD

**Issue by odkken** [microsoft/PTVS#5934] opened 2019-12-11 02:44 UTC
C# code:

```C#
namespace InterpTest
{
    public class SomeLibrary
    {
        public void PrintSomething(string something)
        {
            Console.WriteLine(something);
        }
    }
}
```

Python code:

```python
import clr
clr.AddReference('InterpTest')

import InterpTest
lib = InterpTest.SomeLibrary()

lib.PrintSomething("onetwothree")
```

The code runs as expected, but no autocomplete is offered either on any of the last 3 lines.  This feature would be extremely useful and allow our team of ~50 people to switch from F# to python for our interactive repl environment.

**Comment by judej** [comment] 2019-12-11 23:36
This is a dupe of #5027

**Closed by judej** 2019-12-11 23:36 UTC
Labels: resolution:duplicate
