### ISSUE TITLE
VS crashes while creating a virtual environment.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6904] opened 2022-03-07 06:06 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/156975836-92372f26-7c98-4bd0-b391-dbb486ba7495.png)

**Steps to Reproduce**

1. Create a Python Application project.
2. Create virtual environment.

**Expected behavior**

The virtual environment was successfully installed.

**Additional context and screenshots**

VS crashes while creating a virtual environment.

![creating_virtualenv](https://user-images.githubusercontent.com/82852072/156978286-e35187fb-ac35-4404-aa92-a7280c4d5b80.gif)

Here is the .NET exception I am pulling from the Event Manager.
<details>
<p>

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.PythonTools.LanguageServerClient.FileWatcher.Listener+<OnFileChanged>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.PythonTools.LanguageServerClient.FileWatcher.Listener+<OnFileChanged_Sync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

</p>
</details>

**Comment by ttSpace** [comment] 2022-03-10 06:15
I can repro this in today's build.

<img src=https://user-images.githubusercontent.com/82852072/157600701-ec703b9a-86d1-4739-80e0-251204e9b17b.png width=649 height=352>

**Comment by ttSpace** [comment] 2022-03-14 05:55
I had the same problem with my build today.

<img src=https://user-images.githubusercontent.com/82852072/158112694-25afd91a-4790-4a57-b701-c336ed39e1e9.png width=407 height=349>

**Comment by AdamYoblick** [comment] 2022-03-14 13:44
Ok thanks, will take a look
________________________________

**Comment by AdamYoblick** [comment] 2022-03-16 22:13
@ijoosong Can you please try to repro this for us? Thanks 😄

**Comment by ijoosong** [comment] 2022-03-16 22:41
I was able to repro it using 17.2 preview 2.0 and python 3.9.4
17.1 worked just fine.

**Comment by AdamYoblick** [comment] 2022-03-16 22:43
Thank you, I will switch to this task right now then, since this is more important than what I'm currently working on.

**Comment by AdamYoblick** [comment] 2022-03-21 18:41
@ttSpace This has been fixed locally, can you please confirm if you see it again in builds after tomorrow? Thank you!

**Comment by ttSpace** [comment] 2022-03-22 06:03
@AdamYoblick In today's build, I can still repro this. I'll confirm in a new build tomorrow.

![image](https://user-images.githubusercontent.com/82852072/159416637-6d7d5ac6-a44a-45f5-86ce-ac110251b6e5.png)

**Comment by ttSpace** [comment] 2022-03-24 06:25
@AdamYoblick  In today's build, I can't reproduce this. The virtual environment can be created successfully.

![image](https://user-images.githubusercontent.com/82852072/159854542-7614e4a3-649a-48a5-938f-bd2e8228b355.png)

**Comment by AdamYoblick** [comment] 2022-03-24 13:21
Great, thank you!!!
________________________________

**Comment by AdamYoblick** [comment] 2022-03-24 19:59
I was able to reproduce this again locally with a similar cause but in a different place. I will get it fixed.

**Comment by ttSpace** [comment] 2022-03-25 06:12
@AdamYoblick  In today's build ```17.2.0 Preview 3.0 [32324.294.main] ```, Python Package ```17.0.22080.2 ```. Sometimes it succeeds, but sometimes it crashes.

**Comment by AdamYoblick** [comment] 2022-03-25 12:55
Thank you. I found another codepath in which this occurs, so I'm in the middle of fixing it. I'll reply back when the fix is in so you can verify. 😄

**Comment by AdamYoblick** [comment] 2022-03-30 20:26
This has been fixed by https://github.com/microsoft/PTVS/pull/6938.

@ttSpace I will reply back once this gets merged into Visual Studio main, and if you could verify that the problem doesn't repro after that, I'd appreciate it. I will leave this bug open until you verify that it's fixed.

**Comment by AdamYoblick** [comment] 2022-03-31 05:43
@ttspace I fixed this locally and there's a Visual Studio PR with a build that should have it fixed as well. Can you please verify this is fixed in the build at https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/389872?

**Closed** 2022-03-31 18:40 UTC
Labels: bug, P0, fixed in next version

**Comment by ttSpace** [comment] 2022-04-01 06:52
@AdamYoblick  I didn't repro the problem in this build from the link.

> @ttSpace I fixed this locally and there's a Visual Studio PR with a build that should have it fixed as well. Can you please verify this is fixed in the build at https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/389872?
