### ISSUE TITLE
Launching PyPy interpreter crashes Visual Studio

### ISSUE THREAD

**Issue by moigagoo** [Microsoft/PTVS#45] opened 2015-04-24 08:47 UTC
I am using Visual Studio 2015 CTP with PTVS 2.2 Beta, PyPy3 2.4.

Going to Python Environments and calling the pypy interpreter crashes VS.

**Comment by moigagoo** [comment] 2015-04-24 08:50
The debugger doesn't work with pypy as well, but I think it's connected to this issue.

**Comment by zooba** [comment] 2015-04-24 15:17
When you say "calling the PyPy interpreter" what are you clicking on to do that? Can you walk me through step by step what you're doing so I can try it on my own machine?

**Comment by moigagoo** [comment] 2015-04-24 18:26
I'm clicking this: http://i.imgur.com/djrXRdo.png and instantly getting this: http://i.imgur.com/Ser50di.png

I will be happy to provide any additional information and send you the logs if you tell me what information you need and where I can find the logs.

---

My setup:
- Windows 10 TP 10061
- VS 2015 CTP
- PTVS 2.2 Beta
- PyPy3 2.4.0 (32 bit)
- The projects involved are (probably unnecessary, but I'll list them just in case):
    - https://bitbucket.org/moigagoo/sloth-ci
    - https://bitbucket.org/moigagoo/sloth-ci-extensions
    - https://bitbucket.org/moigagoo/sloth-ci-validators

**Comment by zooba** [comment] 2015-04-24 18:31
I think that may be fixed in a later version of PTVS, as I'm not seeing that issue now. We have a newer release back at [CodePlex](https://pytools.codeplex.com/releases/view/113962) that probably fixes this.

The debugger not working is more of a concern, though we have also made some improvements to that in the release I linked, so it may already be fixed. Can you try that dev build and let us know?

**Comment by moigagoo** [comment] 2015-04-24 18:45
I've installed the new version. The issue persists.

The debugger doesn't close instantly now though, but rather an error is shown: http://i.imgur.com/Fcfeghr.png Which is progress, I think :-)

**Comment by moigagoo** [comment] 2015-04-24 18:59
Just noticed that calling a regular Python interpreter crashes VS as well, at least with the new PTVS version.

**Comment by zooba** [comment] 2015-04-24 22:07
Ah, okay, that's the stackless issue. We've got details about how to fix it (they've changed their API at some point), but haven't gotten there yet. The original support was contributed - we don't actually have anyone on the team who's familiar enough with stackless to just get it right.

As for the crash, can you put the text from Tools - Python Tools - Diagnostic Info into a gist or email it to ptvshelp@microsoft.com? There should be details about the crash in there.

**Comment by moigagoo** [comment] 2015-04-25 05:42
Here you go https://gist.github.com/moigagoo/f50c230459d8fcff45d1

I've reported the stackless issue as a separate .

**Comment by zooba** [comment] 2015-04-28 03:33
Thanks for the separate issue. Unfortunately, there isn't enough information in the log to figure out what the problem is - a `Win32Exception` basically means that the cause is not obvious and probably means you have some sort of local corruption (as opposed to a coding error).

If you add a custom environment and set the interpreter path to Notepad, does the problem still occur? There may be some sort of policy restriction configured on launching programs.

**Closed** 2016-12-16 22:32 UTC
