### ISSUE TITLE
python语句中补全会替换后面字符，导致代码出错

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7072] opened 2022-07-06 18:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python语句中补全会替换后面字符，导致代码出错/10081048)._

---
[severity:It's more difficult to complete my work]
```py
def a(arg):
    d[arg]
```
当我在语句中间使用代码补全时，补全的代码总是会吧后面的代码替换
如本例所示，d是一个字典，当我在d[]中间输入key并使用补全时，']'不见了

---
#### Feedback Bot on 6/27/2022, 01:33 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-07-06 18:42
Translation: When I use code completion in the middle of a statement, the completed code always replaces the following code
As in this example, d is a dictionary, when I enter the key in the middle of d[] and use completion, the ']' is gone

This is a duplicate of #6786

**Closed** 2022-07-06 21:27 UTC
Labels: needs triage
