### ISSUE TITLE
Suggestions prompted by Delete/Backspace impede workflow 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/PTVS#7597] opened 2023-05-10 19:10 UTC
Whenever a Delete or Backspace key is pressed anywhere in Python code, a pop-up with useless suggestions comes up, full of things like and, assert, etc. The only way out is Esc, which needs to be done every time a line is deleted or similar action is taken. Sometimes, when typing/deleting, a quick Enter inserts one of those nonsensical "suggestions" into the code and more needs to be deleted.

**Comment by cwebster-99** [comment] 2023-05-10 19:11
Ref https://github.com/microsoft/PTVS/issues/7594

**Comment by StellaHuang95** [comment] 2023-05-10 21:06
Closing it as a duplicate of the discussion at https://github.com/microsoft/PTVS/discussions/7334

**Closed by StellaHuang95** 2023-05-10 21:06 UTC
Labels: needs triage

**Comment by excubo-jg** [comment] 2023-05-11 07:38
No. This is not a duplicate. #7334 is about shutting down autocomplete, this one is about non-sensical completions in a specific case. 

If one hits backspace in pos 2 these are the utterly worthless suggestions that are being made: 
![image](https://github.com/microsoft/PTVS/assets/52322342/1a5e63c2-0fb5-43f5-80d5-6510d4fa0ae5)

To add insult to injury, you can hit backspace in pos 3 for the same suggestions to be entered in then pos 2. It is illegal to have code beginning at that position in python. 

Or does Microsoft imply forcing the user to hit Esc after using delete/backspace is by design?

An ensuing nuisance which is not mentioned is that if one does not pay attention imports for weird symbols are inserted for whacky autocompletions which do not get removed when the whacky stuff is deleted. Which if unnoticed leads to confusion in code reviews.

The chap in 7594 is spot on - please fix these obvious bugs. Especially the broken workflow in his last point is :facepalm:

**Comment by StellaHuang95** [comment] 2023-05-11 16:52
Thanks for clarifying. I will reopen it:)

**Comment by StellaHuang95** [comment] 2023-06-10 00:23
Some findings that may be related to the issue:
1. Pylance provides suggestion(`completionItem.sortText`) on how data is supposed to be sorted. but client may not follow it.
2. Client seems to send completion request by deletion (e.g. Backspace or Delete keys), which is inconsistent with what vscode does. 

One example request client sends when user hits backspace:
```json
 "params": {
    "context": {
      "_vs_invokeKind": 2,
      "triggerKind": 1,
      "triggerCharacter": " "
    }
```

**Comment by excubo-jg** [comment] 2023-06-15 13:53
In Version 17.7.0 Preview 2.0 Backspace does not remove an indent level but one character. E.g. to remove a tab one has to hit Backspace 4 times... Could this please be changed to align with industry standards?

**Comment by StellaHuang95** [comment] 2023-06-23 16:57
Sent a PR on the pylance side to fix the issue, waiting for it to go through.

**Comment by StellaHuang95** [comment] 2023-06-26 16:28
Should be fixed after pylance releases the next stable version that includes this change, which might be a few weeks from now.
