### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by mnidza** [Microsoft/PTVS#4266] opened 2018-05-27 17:52 UTC
[Window Title]
devenv.exe <br/>

[Main Instruction]
An unexpected error occurred <br/>

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker. <br/>

[Expanded Information] <br/>

```
Build: 15.7.18131.1

System.InvalidOperationException: Collection was modified after the enumerator was instantiated.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Intellisense.LocationTracker.CanTranslateFrom(Int32 version)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetNavigationsAsync>d__174.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.UIThread.<>c__DisplayClass18_0`1.<<InvokeTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Navigation.DropDownBarClient.<RefreshNavigationsFromAnalysisEntry>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Navigation.DropDownBarClient.<Microsoft-PythonTools-Editor-IPythonTextBufferInfoEventSink-PythonTextBufferEventAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
 <br/>
 <br/>
[Visual Studio Info]
 <br/>
Microsoft Visual Studio Enterprise 2017  <br/>
Version 15.7.2 <br/>
VisualStudio.15.Release/15.7.2+27703.2018 <br/>
Microsoft .NET Framework <br/>
Version 4.7.03056 <br/>

Installed Version: Enterprise <br/>

Visual C++ 2017   00369-60000-00001-AA834 <br/>
Microsoft Visual C++ 2017 <br/>

Application Insights Tools for Visual Studio Package   8.12.10405.1 <br/>
Application Insights Tools for Visual Studio <br/>

ASP.NET and Web Tools 2017   15.0.40511.0 <br/>
ASP.NET and Web Tools 2017 <br/>

ASP.NET Core Razor Language Services   15.7.31476 <br/>
Provides languages services for ASP.NET Core Razor. <br/>

ASP.NET Web Frameworks and Tools 2017   5.2.60419.0 <br/>
For additional information, visit https://www.asp.net/ <br/>

Azure App Service Tools v3.0.0   15.0.40424.0 <br/>
Azure App Service Tools v3.0.0 <br/>

C# Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074 <br/>
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. <br/>

Common Azure Tools   1.10 <br/>
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools. <br/>

Image Watch   1.0 <br/>

JavaScript Language Service   2.0 <br/>
JavaScript Language Service <br/>

JavaScript Project System   2.0 <br/>
JavaScript Project System <br/>

JavaScript UWP Project System   2.0 <br/>
JavaScript UWP Project System <br/>

Microsoft Continuous Delivery Tools for Visual Studio   0.3 <br/>
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE. <br/>

Microsoft JVM Debugger   1.0 <br/>
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines <br/>

Microsoft MI-Based Debugger   1.0 <br/>
Provides support for connecting Visual Studio to MI compatible debuggers <br/>

Microsoft Visual C++ Wizards   1.0 <br/>
Microsoft Visual C++ Wizards <br/>

Microsoft Visual Studio Tools for Containers   1.1 <br/>
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container. <br/>

Microsoft Visual Studio VC Package   1.0 <br/>
Microsoft Visual Studio VC Package <br/>

NuGet Package Manager   4.6.0 <br/>
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/. <br/>

ProjectServicesPackage Extension   1.0 <br/>
ProjectServicesPackage Visual Studio Extension Detailed Info <br/>

Python   15.7.18131.1 <br/>
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers. <br/>

Python - IronPython support   15.7.18131.1 <br/>
Provides templates and integration for IronPython-based projects. <br/>

Python - Profiling support   15.7.18131.1 <br/>
Profiling support for Python projects. <br/>

ResourcePackage Extension   1.0 <br/>
ResourcePackage Visual Studio Extension Detailed Info <br/>

SQL Server Data Tools   15.1.61804.210 <br/>
Microsoft SQL Server Data Tools <br/>

TypeScript Tools   15.7.20419.2003 <br/>
TypeScript Tools for Microsoft Visual Studio <br/>

Visual Basic Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074 <br/>
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used. <br/>

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 56f97a8dd4353d897336941f3e644423b87c794f. <br/>
Microsoft Visual F# Tools 10.1 for F# 4.1 <br/>

Visual Studio Code Debug Adapter Host Package   1.0 <br/>
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio <br/>

Visual Studio Tools for CMake   1.0 <br/>
Visual Studio Tools for CMake <br/>

Visual Studio Tools for Universal Windows Apps   15.0.27703.2018 <br/>
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit. <br/>

Windows Machine Learning Generator Extension   1.0 <br/>
Windows Machine Learning Visual Studio Extension Detailed Info <br/>

**Comment by huguesv** [comment] 2018-05-29 17:23
Thanks! Closing as a duplicate of https://github.com/Microsoft/PTVS/issues/4176

**Closed by huguesv** 2018-05-29 17:23 UTC
Labels: resolution:duplicate
