### ISSUE TITLE
Debugging unit test failed

### ISSUE THREAD

**Issue by int19h** [Microsoft/PTVS#1915] opened 2016-12-02 20:57 UTC
Tried to debug a unit test with a breakpoint, got:
```
------ Run test started ------
Error occurred connecting to debuggee.
========== Run test finished: 0 run (0:00:47.076) ==========
```
Trying to do that again worked, so this is not a consistent repro. Possibly, some kind of timeout?

Several unit tests have been run in this VS session before, but this was the first one that I tried to debug.

**Comment by huguesv** [comment] 2017-05-02 23:51
Duplicate of https://github.com/Microsoft/PTVS/issues/921

**Closed by huguesv** 2017-05-02 23:51 UTC
Labels: bug, Debugger, regression, Test Adapter
