### ISSUE TITLE
PackageId;CPython39.Exe.x64;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7355] opened 2023-01-31 18:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId;CPython39Exex64;/10253279)._

---
[regression] [worked-in:17.4.1.1]
**Describe your issue here**  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64; PackageAction:Install; ReturnCode:1603;

---
#### Feedback Bot on 1/15/2023, 07:00 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-31 21:25
dupe of https://github.com/microsoft/PTVS/issues/7359

**Closed by StellaHuang95** 2023-01-31 21:25 UTC
Labels: needs triage
