### ISSUE TITLE
[code editor][python] The name of class or method can not be seen when the outline is closed

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7192] opened 2022-10-19 12:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/code-editorpython-The-name-of-class-/10156572)._

---
[severity:I'm unable to use this version] [regression] [worked-in:not sure but may be released in Apr]
Hi,

I am writing the code in python with Visual studio 2022, 17.3.4

The name of class can not be seen when I close the outline.
![image.png](https://aka.ms/dc/image?name=B4bc89cf732a04e51899d82db2c49202a637995815257304060_20220924-105841-image.png&tid=4bc89cf732a04e51899d82db2c49202a637995815257304060)

![image.png](https://aka.ms/dc/image?name=B3457b75042fd45d3b8889884c9fb3a7b637995815445598957_20220924-105901-image.png&tid=3457b75042fd45d3b8889884c9fb3a7b637995815445598957)

My expectation is
"class **tmp:** ..."
"tmp:" should be kept.

I think the previous version of VS2022 kept the name.

Please let me know if this issue is expected and the way to realize my expectation.

Thank you

---
#### Feedback Bot on 9/25/2022, 08:11 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-10-19 16:28
duplicate of #7032

**Closed** 2022-10-19 17:45 UTC
Labels: duplicate
