### ISSUE TITLE
"Settings Module" Django project's setting has stopped working

### ISSUE THREAD

**Issue by MilovanovM** [Microsoft/PTVS#2529] opened 2017-05-11 11:33 UTC
I've just installed VS2017 with Python Tools and noticed that if I have a value in "Settings Module" (the tab "Django" in project's properties), then the setting is not applied for "migrate" command.
However, the settings is applied to "runserver" command.
There is no such issue in VS2015 with Python Tools.

**Comment by zooba** [comment] 2017-05-11 16:42
I think this _might_ be a duplicate of #2305, but probably need to dig a little deeper to be sure.

**Comment by zooba** [comment] 2017-05-30 23:27
Yep, same as #2305

**Closed by zooba** 2017-05-30 23:27 UTC
Labels: bug, Build, regression
