### ISSUE TITLE
Python environment is 3.12 but visual studio displays Python 3.1

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7964] opened 2024-07-31 21:29 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-environment-is-312-but-visual-st/10707631)._

---
[severity:It bothers me. A fix would be nice]
Python version: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)];
Visual studio version: Microsoft Visual Studio Community 2022 (64 Bit) - Current, Version 17.10.4

In my python project, visual studio shows that my current python environment is 3.1 in places where red arrows point to. This is quite strange.

![Screenshot.png](https://aka.ms/dc/image?name=Bfa8a70e3eb424d5baa26b9c5810a7350638572349185973864_Screenshot.png&tid=fa8a70e3eb424d5baa26b9c5810a7350638572349185973864)

---
#### Feedback Bot on 7/22/2024, 06:20 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-08-01 00:36
Thanks for reporting the issue. Closing as a duplicate of https://github.com/microsoft/PTVS/issues/7923

**Closed by StellaHuang95** 2024-08-01 00:36 UTC
Labels: duplicate
