### ISSUE TITLE
Python hit tab to accept Intellisense recommendation removes parenthese

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6806] opened 2021-12-01 17:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-hit-tab-to-accept-Intellisense-re/1592425)._

---
This works in C#, but in Python if you have this

firstPass = True

Then you start to type this

if (firstPa

Intellisense suggests firstPass

---
#### Feedback Bot on 11/22/2021, 10:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2021-12-08 23:15
Need to see if this repros in vscode to see if it's pylance or VS?

**Comment by StellaHuang95** [comment] 2022-06-06 20:54
duplicate of #6786

**Closed by StellaHuang95** 2022-06-06 20:54 UTC
Labels: P2
