### ISSUE TITLE
System.NotSupportedException: version 4 is no longer in memory

### ISSUE THREAD

**Issue by Jawschamp** [microsoft/PTVS#6100] opened 2020-04-29 02:41 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.5.20041.1

System.NotSupportedException: version 4 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceLocation loc, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.TaskProviderItem.CreateSquiggleSpan(SimpleTagger`1 tagger)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```
![image](https://user-images.githubusercontent.com/38185563/80556390-48504880-8988-11ea-8c1e-bce442dc559e.png)

**Comment by huguesv** [comment] 2020-07-06 20:10
We have a few of these filed. I'll close this one as duplicate of https://github.com/microsoft/PTVS/issues/5725

**Closed by huguesv** 2020-07-06 20:10 UTC
Labels: area:IntelliSense, area:Legacy Language Support, bug
