### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:DownloadPackage;ReturnCode:0x80072ee2;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7242] opened 2022-11-30 16:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10202318)._

---
[regression]
**在此处描述你的问题**  
  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:DownloadPackage;ReturnCode:0x80072ee2;

---
#### Feedback Bot on 11/16/2022, 00:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 17:57
duplicate of https://github.com/microsoft/PTVS/issues/7228

**Closed by StellaHuang95** 2022-11-30 17:57 UTC
Labels: duplicate
