### ISSUE TITLE
PackageId:Microsoft.Net.Core.SDK.2.1;PackageAction:Install;ReturnCode:1638;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7000] opened 2022-05-11 16:24 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:MicrosoftNetCoreSDK21;Pac/10027658)._

---
want to run Python is Visual studio. modify visual studio, select Python development, got this issue

---
#### Feedback Bot on 4/30/2022, 09:39 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-05-11 18:21
Dupe of https://github.com/microsoft/PTVS/issues/7003

**Closed by AdamYoblick** 2022-05-11 18:21 UTC
Labels: needs triage
