### ISSUE TITLE
Custom task list token in Visual Studio 2022 again doesn't work for Python.

### ISSUE THREAD

**Issue by AbhimanyuVS** [microsoft/PTVS#8114] opened 2024-12-14 01:25 UTC
**Describe the bug**

#7151 is reoccurring.

**Steps to Reproduce**

0. Create a Python project in Visual Studio 2022.
0. Create a source file in the above project.
0. Add a `# TODO` to the source file.

**Expected behaviour**

The task should show up in the task list.

**Additional context and screenshots**

![Image](https://github.com/user-attachments/assets/ced3c323-8876-4952-886e-329cd17217d8)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**

VS Version: 17.12.3
PTVS version: 17.0.24269.5
Python version: 3.10.11
Debugger Type (if applicable): N/A

**Diagnostics file**

[PythonToolsDiagnostics_20241213140530.log](https://github.com/user-attachments/files/18133819/PythonToolsDiagnostics_20241213140530.log)

**Comment by AbhimanyuVS** [comment] 2024-12-16 01:58
@OleKoldRud, sorry, but I am not sure I understood what is happening here.

**Comment by OleKoldRud** [comment] 2024-12-16 06:24
Hi Abhimanyu

Thank you for reaching out.

My guess is, that the problem is difficult to solve.

The story is, that I have an old labtop (Dell XPS) with windows 10, which I used for Python back in 2020.
At that time I used Atom and Python 3.7.

Now I upgrade Python to the newest 3.13, and suddenly I cannot use PIP and import Numpy.
Strangely, it seems like it works from the DOS-prompt; but I cannot make it run from Microsoft VS or the Python window from Python.org.

Another guess is, that my old installation is blocking the upgrade in some way.

The only reason I send this request, was because VS at a point asked me to submit my request.

I guess the real solution is to manage where Python resources are kept and maintained on the PC by Python.org or Microsoft.

My problems are not work related.

Best,
Ole Kold Rud

Fra: Abhimanyu Venkatraman Sheshashayee ***@***.***>
Sendt: 16. december 2024 02:59
Til: microsoft/PTVS ***@***.***>
Cc: OleKoldRud ***@***.***>; Mention ***@***.***>
Emne: Re: [microsoft/PTVS] Custom task list token in Visual Studio 2022 again doesn't work for Python. (Issue #8114)


@OleKoldRud<https://github.com/OleKoldRud>, sorry, but I am not sure I understood what is happening here.

-

**Comment by StellaHuang95** [comment] 2024-12-16 23:08
@OleKoldRud Please open another bug report for your issue. It's better for us to address one issue at a time to ensure efficiency. Thank you!

@AbhimanyuVS I couldn't repro your issue using the latest VS, did you save your file? The hollow yellow bar indicates it's not saved yet.

**Comment by AbhimanyuVS** [comment] 2024-12-17 01:36
@StellaHuang95, yes, I've tried with both saved files and unsaved files. Here is an example with a saved file:

![Image](https://github.com/user-attachments/assets/af3900e5-1395-424b-a54d-231a60cff797)

The task list was working fine for over a year since the last time this issue occurred. Only sometime this past month has the task list stopped working for me.

What other information do you require from my end?

**Comment by StellaHuang95** [comment] 2024-12-17 01:54
Thanks, I was able to find similar issues in our internal issue tracker. Seems like something has changed in the upstream on the LSP client side, and they have fixed in the latest VS version. Could you update your VS to 17.13 and see if that repros? I just tried on Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.13.0 Preview 1.0 and that doesn't repro for me.

**Comment by AbhimanyuVS** [comment] 2024-12-17 02:31
@StellaHuang95, I downloaded and installed the preview build, and the task list is working correctly there.

Do I have to use the preview build if I want to use the task list?

**Closed** 2024-12-17 23:09 UTC
Labels: user responded

**Comment by AbhimanyuVS** [comment] 2024-12-20 06:48
...and, the task list is gone again. This time from the Preview build as well.

I installed GitHub Copilot, to check out the free subscription. That was the only significant change I made.

Now no more task list... ☹️

**Comment by AbhimanyuVS** [comment] 2024-12-20 07:57
...and...

I think my VS2022 is haunted.

The task list showed up again (in the preview build), after I debugged some of the code I've been working on.

Gone one minute, then back the next.

Well, the good news is my task list is back, and I don't have to manually search for my TODOs... 😬

**Comment by AbhimanyuVS** [comment] 2024-12-20 09:18
Task list is gone again. It seems to be showing up and disappearing somewhat randomly. I have no idea what is affecting it.

**Comment by jcouture100** [comment] 2025-03-12 15:19
**Work Around:**  

Since this has been an issue for quite some time, I found and installed the free Visual Studio Addin called "**Menees VS Tools**". It has a Task List and once it is turned on, it finds and lists all of my tasks. I just turn off the VS Task List and display the Menees Task List in its place. It uses the standard Visual Studio Task List tokens found under the "**Tools** -> **Options** -> **Environment** -> **Task List**".  So far, it is working well for me.
