### ISSUE TITLE
Intellisense unknown type - missing return types From scrapped .PYD library 

### ISSUE THREAD

**Issue by jesse82** [microsoft/PTVS#3204] opened 2017-10-23 14:33 UTC
I have built and am tested the newest version of PTVS and with the new code scraping a .PYD file is recognized. Its just that none of the calls from the library have any return types. So any object assigned from them has no Intellisense.

Here we see the imported library "NXOpen" has code completion:
![capture11](https://user-images.githubusercontent.com/26267556/31894595-ebea354e-b7dc-11e7-8859-1905f90c25a7.PNG)

But the object returned from the call is not known:
![capture12](https://user-images.githubusercontent.com/26267556/31894597-ec2a6c72-b7dc-11e7-832f-9759f2fe2dec.PNG)

If some one could give me a hint of where to look in code to debug this I'd be happy to do whatever I can,

Thanks!

**Comment by zooba** [comment] 2017-10-23 16:23
@jesse82 Right now this is by design - we haven't done much work to enable it, and it requires a decent amount of help from the library itself.

You can find the code in [scrape_module.py](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/scrape_module.py), but currently the only way we get a return type is if it is one of our hardcoded ones. We really want to avoid expanding that list.

If the function supports `inspect.signature` then we should be able to enable it again fairly easily (it was disabled because `inspect.signature` isn't quite as helpful as `getfullargspec` for our purposes). Otherwise, our recommended approach is eventually going to be to use a typing stub file (`*.pyi`) - right now, we support stubs in the form of:

```python
def GetSession():
    return SessionType()
```

And hopefully before our next release we'll also support PEP 484 style:

```python
def GetSession() -> SessionType:
    ...
```

(Once I get through my bug backlog this is what I'll be working on over the next couple of weeks :) )

**Comment by jesse82** [comment] 2017-10-26 02:10
So for a .pyi Is this what was generated by the library scrapper that I'm finding in:
USER\AppData\Local\Python Tools\CompletionDB\Debug\15.0-1\Global\PythonCore\3.4\xxxxxxx
?

I did find the function GetSession defined in this file and changed:
`def GetSession(): 
    pass`
to
`def GetSession(): 
    return SessionType()`

and now my code seams to recognize the type.
Which is cool! so is there just a way now I can have the intellisense use my updated pyi instead of the one found in AppData?

If this is not a good method, please tell me, but so far this could work for my purposes.
I have to work with a very large and difficult to use API and the autocompletes are really helpful for me.
So if its just a matter of building up .pyi file as I use it that would be great.

Also, If there is anything I can test with the dev work on PTVS I would be happy to get the latest code and compile, I may not be a good enough coder to help with any of the bugs but I would be happy to help with anything I can.

**Comment by zooba** [comment] 2017-10-26 16:00
In theory, if you put the .pyi file next to the original .py/.pyd then we should just use it and ignore the source (if we don't, that's a bug). I'm not 100% certain whether we'll pick up changes automatically as you edit the file (nice to have, though low priority), but close/reopen project should do it.

Also, if you update to the latest code, you can now use the type annotation syntax for this (at least for installed packages and search paths - not files in your project). We don't support anything from the `typing` module yet, so stick to concrete type names.

And thanks for getting on board so early! It's really encouraging for our team to have people like you helping out. Feel free to keep messing about with those files, and if you find a way to improve `scrape_module.py` then we'll happily accept changes.

**Comment by jesse82** [comment] 2017-10-31 18:02
Hi, thanks for the response.

I have attempted to put the .pyi next too the .pyd but it dosnt seam to use it. My .pyd is found from the search paths, but perhaps I am doing something else wrong with my installation, I will try it on the release version and see if it picks it up.
Also, I have compiled the latest(on Sunday) to try the type annotation but It does not seem to work for me yet.

I have modified the scrape_module.py to better work with the NXOpen library and If you think these changes are useful overall I would be happy to send my version.
However the changes I have made may be too focused on this particular library and may not be a good idea globally...

Fist, I have obtained return types from most function by scanning the docstring, it uses some standard formatting that I have added a short method to parse and fill in.
for example it contains the lines:
`:rtype: float`
or
`n:rtype: :py:class: 'NXOpen.SOMECLASSNAME'`

Additionally the NXOpen libraries are divided into files with underscores for the dot character in the namespace, to get the parse to handle this I needed to add a line:
to the ScrapeState class
`self.module_name = str(self.module_name).replace("_", ".")`

What the file structure looks like for the .pyd is:
NXOpen.pyd (contains Base NXOpen objects)
NXOpen_SubModule.pyd (contains NXOpen.SubModule objects)

With my changes I'm generating full .pyi (with return types!) files for both .pyd files, however intellisense is not using the NXOpen_SubModule.pyi for objects in code written as:
```python
import NXOpen_SubModule
myobj = NXOpen.SubModule.SomeObject
``` 

I have a feeling it has to do with the imports in the .pyi files but If you have any idea of how I could get them to be recognized that would be great

**Comment by zooba** [comment] 2017-10-31 19:39
Scanning the docstring for that format is great, and something we intended to do eventually anyway. Feel free to make a PR with that code.

I don't think the `module_name.replace` code is generally applicable, unfortunately. It's legal and common to put underscores in module names, and these do not imply packages. This seems like a flaw in the NXOpen libraries - there's no reason you can't put .pyd files in regular packages:

```
lib\
    NXOpen\
        __init__.py
        SubModule.pyd
```

In particular, your last code snippet is semantically incorrect (even if it works in CPython currently), since the `NXOpen` name is never defined. You should be using `import NXOpen.SubModule`, and if the NXOpen library forces you to import one name and then use a different one, it's the NXOpen library that is wrong :)

And since you mentioned the .pyi import didn't do what we expected I double checked the code in there and you're right - it's definitely resolving `.pyd` before `.pyi`. I'll fix that.

**Comment by jesse82** [comment] 2017-11-01 17:09
I will work on my scrape_module.py and try and send it this weekend.

As far as the NXOpen library, Its definitely setup wired and uses some tricks in the site_customize.py to load, but I have gotten it working by creating a fake module folder with the __init__.py as you suggested and only copied the .pyi files into it.  And this works really well actually!

I have been searching for any sort of documentation on the return lines of the .pyi but have not found much, do you know of any resources for creating .pyi files?
things like, `return str()` vs `return str` or `return List[str]`
or how to return an Enum

**Comment by zooba** [comment] 2017-11-02 19:20
If you look up PEP 484 and MyPy, you'll find most of the resources for type annotations and .pyi files.

For PTVS, we are simply treating them as normal Python files and analyzing their contents. So where we would look at a function like:

```python
def pick_a_number(x):
    if x > 2:
        return 1
    return 0
```

And determine that the result is `int`, we are just doing exactly the same thing with a .pyi file. However, because it is never going to be executed, you do not have to write working code - as far as our code analysis is concerned, `return int()` is the same as the entire function body above, since we know it will return an instance of `int`. Also `return 0` or `return 42`. So if you want the return type to be `str`, write `return str()` or `return ""` or `return 'I am a string'` and it won't matter - we look at the type and see `str` and ignore the actual value (but if you write `return str` you're _actually_ returning an instance of `type`, so you'll get a different result).

Proper .pyi files do not use return statements - they only use annotations, and the body of each function is ignored. We are paying attention to return statements as well, because it means we don't have to treat .pyi files any different from .py files, so when you get a library that uses type annotations, we will handle those fine without needing a .pyi file. (Currently we don't look at annotations in your own code, only in installed libraries.)

**Comment by jesse82** [comment] 2017-11-02 20:21
ok that makes sense, thanks!

I have been testing and have had some trouble with properties,
the autogenerated .pyi file has created lines like this:
```python
   @property
   def SomeProperty(self):
      'some info'
      return SomeObject()
```

however this is not reconized as a property, VS thinks it is callable
I found that if I changed the properties to be:
`SomeProperty = SomeObject()`
Then VS intellisense picks it up ok (but I loose my 'some info in the intellisense hint)

**Comment by turtlestacker** [comment] 2020-09-17 11:07
> I have built and am tested the newest version of PTVS and with the new code scraping a .PYD file is recognized. Its just that none of the calls from the library have any return types. So any object assigned from them has no Intellisense.
> 
> Here we see the imported library "NXOpen" has code completion:
> ![capture11](https://user-images.githubusercontent.com/26267556/31894595-ebea354e-b7dc-11e7-8859-1905f90c25a7.PNG)
> 
> But the object returned from the call is not known:
> ![capture12](https://user-images.githubusercontent.com/26267556/31894597-ec2a6c72-b7dc-11e7-832f-9759f2fe2dec.PNG)
> 
> If some one could give me a hint of where to look in code to debug this I'd be happy to do whatever I can,
> 
> Thanks!



> Hi, thanks for the response.
> 
> I have attempted to put the .pyi next too the .pyd but it dosnt seam to use it. My .pyd is found from the search paths, but perhaps I am doing something else wrong with my installation, I will try it on the release version and see if it picks it up.
> Also, I have compiled the latest(on Sunday) to try the type annotation but It does not seem to work for me yet.
> 
> I have modified the scrape_module.py to better work with the NXOpen library and If you think these changes are useful overall I would be happy to send my version.
> However the changes I have made may be too focused on this particular library and may not be a good idea globally...
> 
> Fist, I have obtained return types from most function by scanning the docstring, it uses some standard formatting that I have added a short method to parse and fill in.
> for example it contains the lines:
> `:rtype: float`
> or
> `n:rtype: :py:class: 'NXOpen.SOMECLASSNAME'`
> 
> Additionally the NXOpen libraries are divided into files with underscores for the dot character in the namespace, to get the parse to handle this I needed to add a line:
> to the ScrapeState class
> `self.module_name = str(self.module_name).replace("_", ".")`
> 
> What the file structure looks like for the .pyd is:
> NXOpen.pyd (contains Base NXOpen objects)
> NXOpen_SubModule.pyd (contains NXOpen.SubModule objects)
> 
> With my changes I'm generating full .pyi (with return types!) files for both .pyd files, however intellisense is not using the NXOpen_SubModule.pyi for objects in code written as:
> 
> ```python
> import NXOpen_SubModule
> myobj = NXOpen.SubModule.SomeObject
> ```
> 
> I have a feeling it has to do with the imports in the .pyi files but If you have any idea of how I could get them to be recognized that would be great



> ok that makes sense, thanks!
> 
> I have been testing and have had some trouble with properties,
> the autogenerated .pyi file has created lines like this:
> 
> ```python
>    @property
>    def SomeProperty(self):
>       'some info'
>       return SomeObject()
> ```
> 
> however this is not reconized as a property, VS thinks it is callable
> I found that if I changed the properties to be:
> `SomeProperty = SomeObject()`
> Then VS intellisense picks it up ok (but I loose my 'some info in the intellisense hint)

Apologies for the necroposting.  I am currently banging my head against the absence of intellisense for NXOpen - do you still have the code you produced for this or shall I setabout reinventing ;-)

**Closed** 2021-07-28 22:12 UTC
Labels: area:Code Intelligence, area:Legacy Language Support, enhancement
