### ISSUE TITLE
How can i use mixed debugging with Python Environments

### ISSUE THREAD

**Issue by Fogrunner** [microsoft/PTVS#7182] opened 2022-10-06 12:26 UTC
**Describe your question**
[A clear and concise description of your question or what you want help with]

Hello.

I succeed to run mixed debugging without environments.

My VS 2022 used Anaconda's  python (3.7 version), if i do not setup evironments.

In this case working well, both Python and C++ code coulde be debugging.

However, after i made my own environment with python 3.9. 

It is not possible to debug both. 

If i turn off 'Enable native code debugging' option in Python project, i could debug Python code. But, i can not debug  C++ code.

What am i missing?

**What have you tried?**
[Have you already searched online? What solutions have you tried?]

**Additional context**
[Add any other information or screenshots that would help us provide you with a better answer]

**Comment by Fogrunner** [comment] 2022-10-06 14:49
I have test it in VS2022 and VS2019.
Both are the same resulting. 

I have test as like below

- Make new environment : failed
- Make anaconda environment : failed
- Make new environment as default : failed
- Using default Python interpreter 3.1 : failed
- Using default Python interpreter 3.7 : succeed
- Using default Python interpreter 3.9 : failed

**Comment by Fogrunner** [comment] 2022-10-06 16:02
I found this article #5623 (Thanks [int19h](https://github.com/int19h))

After copying python.exe, python_e.exe to my env folder, it seems to be worked.

But, in case of 3.9 might has another matter. It does not work even i did what i do above.

**Comment by StellaHuang95** [comment] 2023-02-24 02:20
duplicate of https://github.com/microsoft/PTVS/issues/7260

**Closed by StellaHuang95** 2023-02-24 02:20 UTC
Labels: needs investigation
