### ISSUE TITLE
reportMissingModuleSource in apps.py of an empty Django project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7531] opened 2023-04-25 18:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/reportMissingModuleSource-in-appspy-of-/10344850)._

---
[severity:I'm unable to use this version]
I've just installed Visual Studio 2022 and created an empty Django project. I'm getting a lot of error messages when creating the virtual environment (see attached screenshot). Are these messages "normal"? However, I can run the server.

When I create my first app (HelloDjangoApp), when updating views.py, I have, among others (see screenshot),
reportMissingModuleSource Import "django.ashortcuts" could not be resolved from source.

After having followed the differents steps of the tutorial, I can't run the server anymore. message: "cannot imprt 'url' from 'django.conf.urls'" (see sceenshot)

It seems there is some problem regarding packages resolution. But, I do not see what to do...

---
#### Feedback Bot on 4/20/2023, 07:47 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-04-25 20:01
Duplicate of https://github.com/microsoft/PTVS/issues/7068. Fix is here: https://github.com/microsoft/PTVS/pull/7401

The issue should be fixed in the next version.

**Closed by StellaHuang95** 2023-04-25 20:01 UTC
Labels: fixed in next version
