### ISSUE TITLE
Debugger loading performance is slow.

### ISSUE THREAD

**Issue by carthach** [microsoft/PTVS#4344] opened 2018-06-08 15:30 UTC
Mixed mode debugging (Python/Native Debugging) takes an awful amount of time to load each python file (see below).Is there any tips to speed this up in any way?

Btw it's fine when you attach to the C++ processmanually (after starting without debugging). 

'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\subprocess.py'. Module was built without symbols.
'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\signal.py'. Module was built without symbols.
'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\threading.py'. Module was built without symbols.
'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\traceback.py'. Module was built without symbols.
'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\urllib\__init__.py'. Module was built without symbols.
'TestHost.exe' (Python): Loaded 'C:\Users\carthach\Dev\cpython\Lib\urllib\parse.py'. Module was built without symbols.

**Comment by huguesv** [comment] 2019-06-26 00:33
Closing as dupe of https://github.com/microsoft/PTVS/issues/4929, which had a bit more discussion/info.

**Closed by huguesv** 2019-06-26 00:33 UTC
Labels: area:Debugger, enhancement, tenet:Performance
