### ISSUE TITLE
Prepare Visual Studio to Handle Python Version 3.12

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7740] opened 2023-10-26 14:19 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Prepare-Visual-Studio-to-Handle-Python-V/10481415)._

---
As of September 19, the Python Foundation "strongly encourage[s] maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities." ([source](https://www.python.org/downloads/release/python-3120rc3/))

As Visual Studio is a professional tool for programmers, I believe it is appropriate for Visual Studio to handle new version updates, especially for major releases of any supported language. 

---
#### Feedback Bot on 10/2/2023, 09:49 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment] 2023-10-31 20:35
Thank you for your suggestion. Closing as a dupe of https://github.com/microsoft/PTVS/issues/7565

**Closed by StellaHuang95** 2023-10-31 20:35 UTC
Labels: duplicate

**Comment by Captain-Quack** [comment] 2023-11-05 19:25
Is there an ETA as to when 3.12 might be fully supported?
