### ISSUE TITLE
Can not open definitions in peek view.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6532] opened 2021-05-28 07:26 UTC
**Environment**
![image](https://user-images.githubusercontent.com/59192491/119945786-7f988b00-bfc8-11eb-873b-36c28b30ab8a.png)

**Steps to Reproduce**
1. Check "Enable mouse click to perform Go to Definition" and check "Open definition in peek view" (Tools/Options/Text Editor)
2. CTRL + Click to peek definition

**Actual result**
Can not open definitions in peek view.
![image](https://user-images.githubusercontent.com/59192491/119946165-eb7af380-bfc8-11eb-9736-1df73cefc6fd.png)

**Comment by rchiodo** [comment] 2021-06-02 16:21
This seems like it would be a VS bug. We don't handle the peek definition support.

**Comment by rchiodo** [comment] 2021-06-22 20:39
Root cause was in the platform code. Same fix as for #6541

**Comment by rchiodo** [comment] 2021-07-30 20:57
Should be fixed

**Closed by rchiodo** 2021-07-30 20:57 UTC
