### ISSUE TITLE
Can we have a way to remove all suggestions in the code for both the editor and the iPython interactive windows?  I waste more time navigating around this that I do coding.

### ISSUE THREAD

**Issue by ptallarico** [microsoft/PTVS#7492] opened 2023-04-05 21:37 UTC
**Describe the feature you are requesting**
[A clear and concise description of the feature you are requesting]

**Reasons for requesting this feature**
[Why do you want this feature? How is it beneficial to you and others?]

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered]

**Additional context**
[Add any other context or screenshots about the feature request here]

**Comment by AdamYoblick** [comment] 2023-04-06 18:15
Duplicate of https://github.com/microsoft/PTVS/discussions/7334

**Closed by AdamYoblick** 2023-04-06 18:15 UTC
Labels: enhancement, duplicate
