### ISSUE TITLE
Python intellisense removes code

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6833] opened 2021-12-30 00:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-intellisense-removes-code/1597247)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.0.1]
If there isn't a space after equals sing, the intellicode removes part of the code.
"dicM1[a]=dic" (intellicode suggestion and press Enter)=> "dicM1[dicPalEnFichero"
See attached files, the sequence is: bug1.png, press Enter, bug2.png

But if there is a space in: "dicM1[a]= dic" everything it's ok (intellicode suggestion and press Enter)=> "dicM1[a]= dicPalEnFichero"

In VS 16.8 (I think, or 16.9) this doesn't happened.

---
#### Feedback Bot on 11/28/2021, 11:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Chris Smith on 12/18/2021, 02:06 AM: 

<p>This might be the same as <a target='_blank' href="https://developercommunity.visualstudio.com/t/Intellisense-overwrites-where-is-should/1587098">https://developercommunity.visualstudio.com/t/Intellisense-overwrites-where-is-should/1587098</a></p>

---
### Original Solutions
(no solutions)

**Comment by blackhammer941** [comment] 2021-12-30 19:14
I have the same problem I try to solve it a lot and search but nothing found if u fix it tell me plz

**Comment by blackhammer941** [comment] 2021-12-30 19:14
> _This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-intellisense-removes-code/1597247)._
> 
> [severity:It's more difficult to complete my work] [regression] [worked-in:17.0.1] If there isn't a space after equals sing, the intellicode removes part of the code. "dicM1[a]=dic" (intellicode suggestion and press Enter)=> "dicM1[dicPalEnFichero" See attached files, the sequence is: bug1.png, press Enter, bug2.png
> 
> But if there is a space in: "dicM1[a]= dic" everything it's ok (intellicode suggestion and press Enter)=> "dicM1[a]= dicPalEnFichero"
> 
> In VS 16.8 (I think, or 16.9) this doesn't happened.
> 
> ### Original Comments
> #### Feedback Bot on 11/28/2021, 11:02 PM:
> We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.
> 
> #### Chris Smith on 12/18/2021, 02:06 AM:
> This might be the same as https://developercommunity.visualstudio.com/t/Intellisense-overwrites-where-is-should/1587098
> 
> ### Original Solutions
> (no solutions)
I have the same problem I try to solve it a lot and search but nothing found if u fix it tell me plz

**Comment by blackhammer941** [comment] 2021-12-30 19:14
I have the same problem I try to solve it a lot and search but nothing found if u fix it tell me plz

**Comment by AdamYoblick** [comment] 2022-01-05 23:10
Seems related to https://github.com/microsoft/PTVS/issues/6786

**Comment by xtedx** [comment] 2022-01-10 12:07
yes! happens to me too. i was about to submit a bug and found this. vs2022 17.0.4 on windows11
in django project, i didn't know adding a space was the workaround but i had to give up using vs2022 for django as it is very counter productive

**Comment by blackhammer941** [comment] 2022-01-10 13:03
> yes! happens to me too. i was about to submit a bug and found this. vs2022 17.0.4 on windows11 in django project, i didn't know adding a space was the workaround but i had to give up using vs2022 for django as it is very counter productive

yeh i did giveup too in vs2022 but i start use jetbrain pycharm its better than visual by alot and i get a year free with the education email😊

**Comment by AdamYoblick** [comment] 2022-04-27 19:53
Closing as duplicate of #6786

**Closed by AdamYoblick** 2022-04-27 19:53 UTC
Labels: P1
