### ISSUE TITLE
Cannot debug Python unit test

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7034] opened 2022-06-08 16:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Cannot-debug-Python-unit-test/10061739)._

---
I've got a Python project with unit tests (via the standard unittest framework). Previously I was able to debug unit tests using the default Python 3.9 installed via VS2022. But it stopped working. When I stat debugging a test from the Test Explorer, the Output window shows :
```
Building Test Projects
========== Starting test run ==========
cd C:\Projects\KOOP\STOP\Ontwikkeling-STOP-Speeltuin\STOP\speeltuin\
set PYTHONPATH=C:\Projects\KOOP\STOP\Ontwikkeling-STOP-Speeltuin\STOP\speeltuin;C:\Projects\KOOP\STOP\Ontwikkeling-STOP-Speeltuin\STOP\speeltuin\
"C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe" "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\EXTENSIONS\MICROSOFT\PYTHON\CORE\visualstudio_py_testlauncher.py" -t test_proces_consolidatie.Test_proces_consolideren.test_Fout_Tijdreis_Array -r 58154
Connected to socket
Connection event fired
========== Test run finished: 1 Tests (0 Passed, 1 Failed, 0 Skipped) run in 1.8 sec ==========
```
but the debugger does not stop at any breakpoint. If I choose not to debug but run the test from the Test Explorer, the python code is executed correctly.

Restarting VS2022 or deleting __pycache__ does not help in any way. There must be a problem with VS2022. This is extremely annoying as the test fails and I have modern tools to find out what's happening.

---
#### Feedback Bot on 6/5/2022, 08:02 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by int19h** [comment] 2022-06-15 17:34
Dupe of https://github.com/microsoft/PTVS/issues/6796

**Closed by int19h** 2022-06-15 17:34 UTC
Labels: bug, P2
