### ISSUE TITLE
How to get PyLint working for IronPython

### ISSUE THREAD

**Issue by matthewsheeran** [microsoft/PTVS#1046] opened 2016-01-04 04:03 UTC
PyLint doesn't work with IronPython.  The only possible inconvenient work around may be to constantly switch between CPython and IronPython Interpreter choices in a PVTS Project to perform PyLint.

This a VERY MAJOR shortcoming of PVTS for IronPython .NET CLR Development.

Any plans, advice, working alternative Lint-er configuration suggestions would be much appreciated.
(And don't insist that PyLint works in IronPython as it doesn't and has merely been left as an (attempted) installable to IronPython for possible future implementation)).

WE as a COMMUNITY need to come with a workable solution to this PROBLEM and I am happy to help and submit a working code improvement for a working IronPython Lint-er with assistance.

I am using the latest IronPython 2.7.5 (though my CPython is 2.7.X due to an ArcGIS/ArcPy 10.2.X dependency.)

Kind Regards,
Matthew.

**Comment by matthewsheeran** [comment] 2016-01-04 05:50
There is a very very simple but unobvious solution here: enable an additional option for PyLint allowing one to specify an alternative installed Python environment (my CPython in this case) from which to run PyLint instance!
Anyone up for this very minor change guys?
Or anyone who can point in the right direction to add this dropdown or checkbox?
Regards,
Matt.

**Comment by crwilcox** [comment] 2016-01-05 19:47
@matthewsheeran:

Thanks for submitting this issue. Upon some research on my side it seems the issue is that PyLint doesn't work great from IronPython. At least some post on SO seem to make me think that.

That being said, with VS 2015, PTVS 2.2.2, IronPython 2.7.5, and Latest PyLint installed using `ipy.exe -X:FullFrames -m pip install pylint` I was able to get pylint going on the commandline.

	>"C:\Program Files (x86)\IronPython 2.7\Scripts\pylint.exe" PythonApplication1.py

It does seem though we aren't correctly running pylint from VS though. I am using it following the instructions in our docs and notice the following in the output tab indicating we are not running with -X:Frames.

	Unhandled exception:
	Traceback (most recent call last):
	  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 175, in run_module
	  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 81, in _run_module_code
	  File "C:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 72, in _run_code
	  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\pylint\lint.py", line 42, in <module>
	  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\six.py", line 701, in <module>
	  File "C:\Program Files (x86)\IronPython 2.7\lib\site-packages\six.py", line 692, in exec_
	AttributeError: 'module' object has no attribute '_getframe'
	
I am going to rename this to reflect the bug that seems to  exists.

Thanks!
Chris

**Comment by int19h** [comment] 2016-01-05 20:28
As a workaround, you can find `PythonRunPyLintCommand` in `Microsoft.PythonTools.targets`, and add `-X:Frames` to arguments there. The problem is that it will then not work with regular CPythoh, which doesn't know what that argument is.

The fundamental issue here is that PyLint support is based on an extensibility mechanism that we have that allows you to define arbitrary project commands that are backed by Python code, and that mechanism does not allow for interpreter-specific command line arguments. Basically, the interpreter has to be CPython-compatible for it to work, and IronPython isn't by default. 

I suppose one possibility would be to inject `-X:Frames` into the argument list for IronPython, but that doesn't really solve the problem in general, because it has some other `-X` switches of similar compat nature, and because there are other implementations that may also have this problem but require different switches altogether (e.g. Jython?). 

The best solution all around would be for PyLint to stop depending on `_getframe`, or at least depend on it conditionally - it's inherently an implementation-specific API.

**Comment by zooba** [comment] 2016-01-08 23:03
It's actually just using `six`, which uses `_getframe` to implement the `reraise` function that is probably unused and could be omitted. See [six issue 135](https://bitbucket.org/gutworth/six/issues/135/have-a-fallback-for-sys_getframe-usage-in) and encourage the developers to fix it there.

As for the "checkbox" to use a different interpreter, unfortunately that is actually very complicated. However, I am thinking about finding a way to distribute a private version of Python with PTVS that can be used for running tools without relying on user configuration.

**Comment by matthewsheeran** [comment] 2016-03-22 10:43
I couldn't get it to work for me. 
So the easiest option for me for now is to use a separate regular CPython install as a second interpreter to switch to and run pylint in VS or from command line or GUI etc. and meanwhile get on with real development work rather than stuffing around with the tools. 
Python has its niceties but also its quirks. 
But do let me know if the situation changes definitively as I am sure it will eventually..
Kind Regards and thanks for the help,
Matthew.

**Comment by denfromufa** [comment] 2016-09-14 03:33
We are looking into enabling pylint support in pythonnet. I'm thinking of using reflection to build up pure python "skeletons" of .NET types used in ironpython/pythonnet so that pylint and other tools recognize it properly. Switching interpreter is very easy in PTVS by using environments. I'm surprised that no one tried this approach even for jython/py4j.

**Comment by matthewsheeran** [comment] 2017-03-21 11:34
I will forward to seeing this working one day and glad no one has closed this ticket which can stay open until then..

**Comment by gramster** [comment] 2019-11-20 17:47
Closing this; we are not going to do any work to support IronPython; usage is too low and there are alternatives that work with Python 3.

**Closed by gramster** 2019-11-20 17:47 UTC
Labels: area:Project System, enhancement
