### ISSUE TITLE
Import tensorflow module in PTVS is very slow

### ISSUE THREAD

**Issue by lixiaoquan** [Microsoft/PTVS#2797] opened 2017-07-13 07:48 UTC
It takes about 10 seconds to finish "Step Over" to this line

"import tensorflow as if"

It take even longer to execute 

"from tensorflow.contrib import learn"

My script behaves normally when executed in command line. Version of tensorflow is 1.2.1.

PTVS 2.2.2 Visual studio Ultimate 2013.

**Comment by huguesv** [comment] 2017-07-13 20:43
It's because you are running under the python debugger, which has significant overhead.

We are tracking general debugger performance improvements in https://github.com/Microsoft/PTVS/issues/749

One alternative would be to run without debugging (use CTRL-F5 instead of F5) and then later debug->attach to process when you need the debugger.

I tried the mixed-mode debugger (native code debugging option in project settings/debug) to see how it compares to the python debugger, and it turns out that for those tensorflow import statements, it's much slower.

**Comment by syagev** [comment] 2017-07-23 11:05
Shouldn't the debugger be comparable in performance to `pdb`? Running a module that has just `import keras` without debugging takes 2 seconds. Running the same module using `python -m pdb test_module.py` also takes about 2 seconds. Debugging the module via PTVS indeed takes about 10 seconds.

**Comment by int19h** [comment] 2017-07-23 23:59
To clarify, are you using pure Python debugging, or mixed native/Python? Symbols are only relevant if you're using mixed-mode, as Python itself doesn't have that concept.

**Comment by syagev** [comment] 2017-07-24 01:45
Just bad use of terminology on my side then..
Native debugging is turned off.

**Comment by denfromufa** [comment] 2017-07-24 04:04
tf import is one order slower with python debugger, and 2 orders slower with mixed-mode debugger. PTVS 2017, python 3.5, 64-bit with debug symbols and debug binaries from python.org. i think this is a big deal.

**Comment by zooba** [comment] 2017-07-24 16:14
We have performance work to do, we're fully aware of that. Imports are particularly bad because we currently trace the entire process, and they are the slowest part of Python in many programs already. However, it's not as big a deal as the issues we have been fixing, which interrupt or block actions completely, rather than simply slowing them down.

This is a duplicate of #749.

**Comment by int19h** [comment] 2017-08-08 01:03
Disabling tracing while importing stdlib (as in, everything in lib and site-packages) gives a ~4x improvement on tensorflow, and is a fairly minor change.

**Closed** 2017-08-08 23:42 UTC
Labels: duplicate

**Comment by Venu-prahalad** [comment] 2017-09-21 15:55
I have installed ptvs 2.2.6 on vs 2015. Import tensor flow in Debug is slow(up to 5 mins). I see it fixed. How do I get this fix on my local machine? Should I wait for next update? If so when is it planned?

**Comment by huguesv** [comment] 2017-09-21 18:05
The fix will be in VS 2017 15.4. Sorry but we are not updating VS 2015 anymore.

**Comment by pschaeffer** [comment] 2017-10-16 14:12
I had this problem (with a very different set of code). Starting execution with debugging was very slow. The Ready indicator blinked many times. Turning off 'Enable native code debugging' fixed the problem for me.
