### ISSUE TITLE
Python Code Analyzer Hinders Work

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6106] opened 2020-05-06 07:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1005558/python-code-analyzer-behindert-arbeit.html)._

---
Since yesterday I have the problem that the Python Code Analyzer is behind me to save a file. I get the error message "The file is being accessed by another process"
I have already tried to reinstall VS after radically removing it with the CleanTool. But the problem keeps coming up.
However, only with a single file and only when I work with file output.

The following code is causing the problems:
'''py
filename = "testset_0.svmdata"
f = open(filename, "w")
f.write("SVM Training Set")
f.write("<class> +")
f.write("<set>")
data[0][0].to_csv(f, index = False)
f.write("</set>")
```

I ask for urgent hotfix from the code analyzer. Until then, how can I disable it completely? It completely hinders the work. Not only with VS, but the process continues to work even after ending VS and thus eats unnecessarily resourcen.

---
### Original Comments

#### Visual Studio Feedback System on 4/24/2020, 05:07 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Carsten Fuhrmann on 4/24/2020, 07:51 PM: 

<p>Further try and error with the problem gave me some more information. The Problem is not the code, it's the Project structure.</p><p>There were four projects within the solution and the projects import modules from other projects in this solution via additional search folders pointing to the other Projects.</p><p>When i moved all modules into one Project to avoid the search folders everything works. So the code analyzer seams to stuck with growing numbers of Projects</p>

#### Wade Zhou [MSFT] on 5/6/2020, 02:43 PM: 

<p>thanks for your feedback, I could not repro your issue in the latest vd build, you can install the latest vs build to retry. if this issue still exists, please provide the detailed info to us.</p>

#### Carsten Fuhrmann on 5/6/2020, 03:07 PM: 

<p>Since i restructured the project in order to continue working on it i cannot test it. But i can descripe the Project setup:<br>There was one Solution with 4 Projects. In addition there was another Python module that was not part of the Solution. This module was imported to every project and added to their search path<br></p><p>While Project 1 was just a test project, the Project 2 was imported by Project 3 and 4.</p><p>Project 3 and 4 imported each other. I'm pretty sure that this causes the problem.</p>


---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment] 2020-05-07 23:15
Thanks, this is a duplicate of https://github.com/Microsoft/PTVS/issues/5174

**Closed by huguesv** 2020-05-07 23:15 UTC
