### ISSUE TITLE
Go To All does not work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7095] opened 2022-07-27 07:28 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/181186774-d9fd6c89-6dc1-440f-b983-f1787b9b3bcc.png)

**Steps to Reproduce**

1. Create Python Application and type code.
```
def hello():
    pass
```
2. Edit->Go to->Go To All, type 'hello'.

**Additional context and screenshots**

Can't find the ```hello```.

![image](https://user-images.githubusercontent.com/82852072/181187677-341efa9d-4ce3-40a5-96b4-99a21703f020.png)

![image](https://user-images.githubusercontent.com/82852072/181187529-e0dc0092-341f-4a1e-bc48-092a91ad8604.png)

**Comment by StellaHuang95** [comment] 2022-07-27 17:24
duplicate of #7022, seems still waiting for upstream to fix: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1549408.

**Closed** 2022-07-27 18:19 UTC
Labels: needs triage
