### ISSUE TITLE
UTF-8 Encoding/Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7845] opened 2024-03-06 17:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/UTF-8-EncodingVisual-Studio/10497336)._

---
I'm doing a Web/Django project, in all my templates, I insert the meta charset="utf-8" tag, however every time I run my project, it doesn't render the page, because it accuses a character not contemplated in utf-8 encoding, when I remove the spelling accents, I can render

---
#### Feedback Bot on 10/22/2023, 11:08 PM: 

(private comment, text removed)
#### Feedback Bot on 10/24/2023, 01:45 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-03-06 17:11
Hi there, this should be a dupe of https://github.com/microsoft/PTVS/issues/6784, can you try the following steps and reopen the issue if that doesn't work? Thank you! 

Navigate to File -> Save As -> click the dropdown button next to Save, choose save with encoding -> choose UTF-8 and re-run the script.

**Closed by StellaHuang95** 2024-03-06 17:11 UTC
Labels: needs triage
