### ISSUE TITLE
Visual Studio Python Tests, Debugger not hitting breakpoints

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7796] opened 2023-12-20 21:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-Python-Tests-Debugger-not/10545670)._

---
Breakpoints are disabled when starting pytests from test explorer, but are enabled when starting withe start(debug) button in the top menu. The test case runs as if I started it with Run in test explorer. I have seen similar reports on VS2019, but this is still an issue in latest version of VS2022. I'm using Python 3.12(64 bit) which is not yet supported, but I don't think this is the issue here.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-12-20 21:58
Closing it as a dupe of https://github.com/microsoft/PTVS/issues/6796

**Closed by StellaHuang95** 2023-12-20 21:58 UTC
Labels: duplicate
