### ISSUE TITLE
Problem loading project when opening solution file

### ISSUE THREAD

**Issue by leleftheriades** [microsoft/PTVS#6032] opened 2020-02-26 09:46 UTC
**Descrption**
Project does not load along with solution.

> Morningstar\Morningstar.pyproj : error  : Value cannot be null.
> Parameter name: first

Note: that this is the entirety of the error messages, I don't get any stack trace like the other bug report

**Steps to Reproduce**
I created a solution and added a python project of type "Python Application".
I removed the project from the solution, added it back. 
Closed the solution and re-opened the solution. The project says (unloaded)

My the python environment used in the project is "Python 3.7 (64-bit)". I do not use conda nor do I know what that is

**Configuration information**
VS Version: 16.4.3
PTVS version: 16.4.19310.1
Python version: 3.7
[Diagnostic Info 2020-02-26T113838.txt](https://github.com/microsoft/PTVS/files/4254702/Diagnostic.Info.2020-02-26T113838.txt)

**Comment by huguesv** [comment] 2020-02-28 00:51
Thanks for the report. I could not reproduce using those steps, and I'm not sure what it could be. I see you have other VS extensions, it would be worth a try to disable them to see if that helps. Also, when you get into that state where it doesn't load, does it help to delete the .vs folder (close VS first)?

**Comment by leleftheriades** [comment] 2020-02-28 12:50
I disabled extensions, and deleted the .vs folder. no luck. On top of that, after disabling all extensions the project won't even load when i right click it in the solution explorer and click Reload project.

![Python_load](https://user-images.githubusercontent.com/12971445/75549310-09f5e600-5a38-11ea-8a93-a89b42377ede.png)

Is there a way to get more information on the error?

**Comment by judej** [comment] 2020-12-09 23:36
@leleftheriades, this looks like a corrupt .proj file. Could you try recreating the project file - if you are still having the problem?

**Comment by judej** [comment] 2021-01-05 23:20
Closing issue. Please reopen if this is still an issue
thanks

**Closed by judej** 2021-01-05 23:20 UTC
Labels: needs more info
