### ISSUE TITLE
lightbulb and print on python 3

### ISSUE THREAD

**Issue by huguesv** [Microsoft/PTVS#274] opened 2015-05-29 01:41 UTC
PTVS.Dev.2015-05-28.VS.2015
Python 3.5.0b1 64-bit

On Python 3, we always get a lightbulb on `print`.  Even when you accept it and add the import, the lightbulb doesn't go away.

![print](https://cloud.githubusercontent.com/assets/1696845/7874767/fcd6168a-0568-11e5-84ac-edbcab980824.png)

**Comment by zooba** [comment] 2015-05-29 16:31
I can't reproduce this right now, but I have seen it in the past. Once all the current PRs go in I'll test again with the merged code - a few things have changed here recently.

**Closed** 2015-06-04 18:20 UTC
Labels: bug, Editor, regression
