### ISSUE TITLE
Need python fstring support. It's not rendering correctly

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6706] opened 2021-09-01 17:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Need-python-fstring-support-Its-not-re/1515375)._

---
See the two screens. One from VSCode and the other from VS 2022.
VSCode is able to detect that fstr is being assigned from an interpolated string and renders it as such (The color for "result" is blue/purple instead of green.

VS 2022 is treating the same string as a string. It should be able to detect that it's an interpolated string and render it as such.... similar to what's done for C#.

---
#### Feedback Bot on 8/27/2021, 01:13 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

![image](https://user-images.githubusercontent.com/19672699/131751870-b1eae3ff-136f-4089-b17f-9abfb4607e56.png)

**Comment by hjb417** [comment] 2021-09-06 18:10
Will this be fixed before the VS2022 go live?

**Comment by StellaHuang95** [comment] 2022-07-05 23:12
duplicate of #7024

**Closed by StellaHuang95** 2022-07-05 23:12 UTC
