### ISSUE TITLE
Wrong outlining in python - the name part is not visible

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7055] opened 2022-06-22 21:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Wrong-outlining-in-python---the-name-par/10063060)._

---
[regression] [worked-in:17.2.3]
When upgraded to version 17.2.3 (community) outlining in python stopped working properly. See images.

---
#### Feedback Bot on 6/6/2022, 07:57 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-06-23 16:56
duplicate of #7032

**Closed** 2022-06-23 17:46 UTC
Labels: needs triage
