### ISSUE TITLE
Python type hint break syntax highlight in Visual Studio 2022

### ISSUE THREAD

**Issue by greazer** [microsoft/PTVS#6653] opened 2021-08-04 22:19 UTC
From: https://developercommunity.visualstudio.com/t/Python-type-hint-break-syntax-highlight-/1493478

Looks as though we need to update our textmate language grammar. VS Code doesn't repro this and they do the same thing.

**Comment by rchiodo** [comment] 2021-08-04 22:20
Here's where this code exists:
https://dev.azure.com/devdiv/DevDiv/_git/VS-Platform?path=%2Fsrc%2FEditor%2FTextMate%2FVSWindows%2FSetup%2FStarterkit%2FExtensions%2Fpython%2Fsyntaxes%2FPython.tmLanguage&_a=contents&version=GBmain

**Comment by int19h** [comment] 2021-08-04 23:39
And here's the upstream version:
https://github.com/textmate/python.tmbundle/blob/master/Syntaxes/Python.tmLanguage

**Comment by Cozy-69** [comment] 2021-08-11 08:30
sorry i didn't quite understanding what's going on is there a fix for this issue?

**Comment by rchiodo** [comment] 2021-08-11 15:32
There is not a fix for the issue yet. We believe the problem lies in the tmlanguage file VS ships for Python.

**Comment by rchiodo** [comment] 2021-08-20 16:35
This is pending insertion by the editor team of their latest bits.

**Comment by StellaHuang95** [comment] 2022-08-27 00:03
duplicate of #6782

**Closed by StellaHuang95** 2022-08-27 00:03 UTC
Labels: waiting for upstream
