### ISSUE TITLE
 System.ArgumentException: Path was invalid.  System.ArgumentNullException: 值不能为 null

### ISSUE THREAD

**Issue by NingShenTian** [Microsoft/PTVS#3938] opened 2018-03-22 01:33 UTC
[Window Title]
devenv.exe

[Main Instruction]
发生意外错误

[Content]
请按 Ctrl+C 复制此对话框的内容并向我们的问题跟踪程序报告此错误。

[V] 显示详细信息(D)  [关闭(C)]

[Expanded Information]
```
Build: 15.6.18072.2

System.ArgumentException: Path was invalid
参数名: root ---> System.ArgumentNullException: 值不能为 null。
参数名: uriString
   在 System.Uri..ctor(String uriString, UriKind uriKind)
   在 Microsoft.VisualStudioTools.CommonUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.VisualStudioTools.CommonUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
   在 Microsoft.VisualStudioTools.CommonUtils.GetAbsoluteDirectoryPath(String root, String relativePath)
   在 Microsoft.VisualStudioTools.Project.ProjectNode.get_ProjectHome()
   在 Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProjectHelper>d__144.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__143.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by huguesv** [comment] 2018-03-22 16:47
Thanks for the report. This is a duplicate of https://github.com/Microsoft/PTVS/issues/3820 and has been fixed for 15.7

**Closed by huguesv** 2018-03-22 16:47 UTC
Labels: resolution:duplicate
