### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7248] opened 2022-11-30 16:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10198790)._

---
[severity:It bothers me. A fix would be nice]
**在此处描述你的问题**  
  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 11/13/2022, 07:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 17:59
duplicate of https://github.com/microsoft/PTVS/issues/7238

**Closed by StellaHuang95** 2022-11-30 17:59 UTC
Labels: duplicate
