### ISSUE TITLE
Can't run MPI Python program on MPI Head node from worker node

### ISSUE THREAD

**Issue by michael-sutherland** [Microsoft/PTVS#579] opened 2015-07-10 17:26 UTC
When I try to configure an MPI process to run on the Head node, the form closes with no changes made.

Under Properties/Debug I have MPI Cluster launcher selected.  I can open the "Cluster Selector" form under Run Environment.  "Head Node" is defaulted to localhost.  The pull down lists the MPI head node computer; however, when I select it the form closes.  It appears that some of the fields are very briefly filled in before it closes.

I am using HPC Pack 2012 R2.  The Head node has MS 2012 Server installed and HPC Pack 2012 R2.  My computer is configured as a workstation and is running Windows 7.  I have MSVC 2013 update 4 installed with PTVS 2.1.21008.00 installed.  I can run MPI jobs on the cluster by submitting jobs from the command line.

**Comment by zooba** [comment] 2015-07-10 20:15
I'm looking into this, though I can't promise we'll release a fix as part of 2.1.1 and HPC support has been removed completely from PTVS 2.2.

Submitting jobs from the command line is the best workaround I'm aware of.

**Comment by zooba** [comment] 2015-07-11 20:03
I'm not able to reproduce the problem you're seeing with the Cluster Selector. Would you be able to try the following:

1. Open two instances of Visual Studio.
2. In one VS, open your Python project and get into Properties/Debug.
3. In the other, click Debug, Attach to Process, then select devenv.exe and attach.
4. In the same instance of VS, click Debug, Exceptions and ensure "Thrown" is selected for "Common Language Runtime Exceptions"
5. Back in the VS with the Python project, open Cluster Selector and select your head node from the drop down.

Hopefully at this point the debugger will break and show some exception details. Any information you can provide from here will help us figure out what's going wrong.

You may also see it break on some other exceptions, depending on exactly what's going on at the time. If so, you may need to keep continuing until you can select the problematic item, and possibly disable breaking on some exceptions if they keep getting in the way.

**Comment by michael-sutherland** [comment] 2015-07-13 16:12
I followed the directions to debug and am not hitting a break point.  I see the following in the debug output.  I even tried enabling all  types of exceptions, but didn't hit a break.

The thread 0x64c has exited with code 259 (0x103).
The thread 0x2610 has exited with code 259 (0x103).
The thread 0x2380 has exited with code 259 (0x103).
The thread 0x2078 has exited with code 259 (0x103).
The thread 0x1df0 has exited with code 259 (0x103).
The thread 0x22a4 has exited with code 259 (0x103).

Let me know if there is anything else I can do to get some debug info.

**Comment by zooba** [comment] 2015-07-14 16:33
I don't know that there is anything else you can do. I'll walk through the source code and see if there's anywhere we may be closing the window ourselves, or if there's some other way it's closing without an exception being thrown.

If you're feeling really keen, you can build PTVS from the 2.1 sources (https://github.com/Microsoft/PTVS/tree/v2.1) and step through ClusterSelector.cs (in HpcSupport project) to see if you can narrow down exactly what's breaking. Since I don't have a repro I can't do it myself unfortunately.

**Closed** 2016-12-16 23:35 UTC
