### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7175] opened 2022-09-28 17:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10152716)._

---
**ここで問題について説明してください**  
  
  
===この線から下は編集しないでください===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 9/20/2022, 06:53 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment] 2022-09-28 17:27
Dupe of #7176

**Closed by judej** 2022-09-28 17:27 UTC
Labels: needs triage
