### ISSUE TITLE
NullReferenceException at LocationTracker

### ISSUE THREAD

**Issue by viananth** [Microsoft/PTVS#4234] opened 2018-05-17 22:31 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.7.18116.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceLocation loc, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.LocationTracker.Translate(SourceSpan span, Int32 fromVersion, Int32 toVersion)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<ConvertOutliningTags>d__181.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<>c__DisplayClass13_1.<UpdateTagsAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<UpdateTagsAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.UIThread.<>c__DisplayClass17_0.<<InvokeTask>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger.<Microsoft-PythonTools-Editor-IPythonTextBufferInfoEventSink-PythonTextBufferEventAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by AlexanderSher** [comment] 2018-05-22 22:53
I'm closing this issue as a dupe of #4213 because they have happened in the same version of VS and current implementation of [`LocationTracker.Translate`](https://github.com/karthiknadig/PTVS/blob/699f30e184178e1ecb74db83e01dc9d27feac296/Python/Product/PythonTools/PythonTools/Intellisense/LocationTracker.cs#L324) can't throw `NullReferenceException`:
- GetTextVersion() can't throw NRE because `_snapshot`s always has at least one item. `ITextSnapshot.Version` can be `null` only if text snapshot was created without `ITextVersion`, which AFAIK isn’t possible
- `fromVer` and `toVer` can't be `null` because they are assigned from `snapVer` (which is initialized from `GetTextVersion()`) and loops change text version to the next one only if `ITextVersion.Next != null`. `ITextVersion.Next` isn't assigned from non-null to null.
- `GetLineLocations` issues from bug #4213 were fixed in https://github.com/Microsoft/PTVS/pull/4220.
- `LocationToIndex` checks if `lineLocations` isn’t `null`.
- `Tracking.TrackPositionForwardInTime` and `Tracking.TrackPositionBackwardInTime` shouldn’t throw because code above the calls ensures that `fromVer` and `toVer` are connected with the chain of `Next` properties.

**Closed by AlexanderSher** 2018-05-22 22:53 UTC
Labels: area:IntelliSense, bug, priority:P0, tenet:Reliability
