### ISSUE TITLE
visual studio's ipython interaction is unusable

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7628] opened 2023-05-31 18:48 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/visual-studios-ipython-interaction-is-u/10373903)._

---
[severity:It's more difficult to complete my work]
visual studio's ipython interaction mode has no output. it just in[2]or in[3]......there，without  out[]

---
#### Feedback Bot on 5/24/2023, 06:02 PM: 

(private comment, text removed)
#### Feedback Bot on 5/31/2023, 11:47 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-05-31 18:51
duplicate of https://github.com/microsoft/PTVS/issues/7219

**Closed by StellaHuang95** 2023-05-31 18:51 UTC
Labels: duplicate
