### ISSUE TITLE
Python Tools for Visual Studio has been broken for a long time. PLEASE FIX IT

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6458] opened 2021-03-24 22:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-Tools-for-Visual-Studio-has-been-/1376234)._

---
This problem has been in VS for a long time. There is a reproducer. It makes all recent versions of VS practically useless with mixed C++ and Python solutions, which is one of the main value-adding characteristics of VS that other IDEs don't have. Please bump its priority and get it fixed.

https://github.com/microsoft/PTVS/issues/6305

---
#### Feedback Bot on 3/21/2021, 07:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment] 2021-03-24 22:13
Dupe of #6305

**Closed by greazer** 2021-03-24 22:13 UTC
