### ISSUE TITLE
Errors in open files are shown inconsistently

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7671] opened 2023-07-10 10:10 UTC
**Steps to Reproduce**
1.  Open attached project
2.  3 files are opened with a.py displayed
3.  No errors are reported in the "Error List"
4.  Set Options - Python - Analysis - Diagnostic Mode to "Workspace"
5. The error in c.py is reported in "Error List"
6.  Set Options - Python - Analysis - Diagnostic Mode to "Open files only"
7.  The error message in the "Error List" is removed although c.py is open
8.  Select c.py
9. The error in c.py is reported in "Error List"
10.  Select a.py
11. The error in c.py is still reported in "Error List"

**Expected behavior**
Errors in all open files in the workspace should be reported all the time. [Or to preserve consistency the setting should be renamed to "active file only" and all messages from other files suppressed although that is not preferred]

**Sample Code**
```
[PythonApplication1.zip](https://github.com/microsoft/PTVS/files/12000474/PythonApplication1.zip)

```
![image](https://github.com/microsoft/PTVS/assets/52322342/4cff0950-1301-4e26-b9bb-529c4c415444)

**Comment by StellaHuang95** [comment] 2023-12-13 01:31
I was able to repro this in vscode as well. I've filed an issue with Pylance, and we'll wait to hear what the team has to say about it. https://github.com/microsoft/pylance-release/issues/5249

**Comment by StellaHuang95** [comment] 2023-12-13 01:37
Looks like it's by design. Closing this issue for now as it appears to be beyond the scope of PTVS to address.

**Closed by StellaHuang95** 2023-12-13 01:37 UTC
Labels: waiting for upstream
