### ISSUE TITLE
Import from libraries in python environment not being resolved

### ISSUE THREAD

**Issue by excubo-jg** [microsoft/PTVS#7224] opened 2022-11-19 11:03 UTC
![image](https://user-images.githubusercontent.com/52322342/202847198-bd787f1b-2915-4fac-8029-e496749bc97b.png)

Libraries listed in the Python environment get flagged with "import could not be resolved", libraries not listed in the Python Environment do not. 

The Libraries can bei imported in cli as shown in the screen shot, codes executes without problem as well

**Expected behavior**
I'd expect these libraries to not get flagged

VS Version: Version 17.5.0 Preview 1.0

**Comment by StellaHuang95** [comment] 2022-11-21 18:06
duplicate of https://github.com/microsoft/PTVS/issues/7068

**Comment by judej** [comment] 2022-11-21 18:48
closing dupe

**Closed by judej** 2022-11-21 18:48 UTC
Labels: duplicate
