### ISSUE TITLE
Please don't touch my python

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7699] opened 2023-08-16 16:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Please-dont-touch-my-python/10433180)._

---
I have manually installed python. But on rollback from 17.6.5 to 17.3.5 it was removed in order to install private version inside VS and as result I didn't have anymore python for myself. I had to manually remove VS python and reinstall python I need.
Similar issue I had when upgraded from 17.3.5 to 17.7.0 Preview 6 - there was a recommendation about out of support python. 3.9.13 is fine for me and my company. If VS need a new python put in private silently and make it use from that place, but don't touch client python versions.

---
#### Feedback Bot on 8/8/2023, 01:58 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-08-23 21:15
Thanks for the issue. This appears to be a duplicate of the issue discussed in  https://github.com/microsoft/PTVS/issues/7439#issuecomment-1462635889. The workaround is not to install the python interpreter through the VS installer. We've marked this component as out of support so it should always be unchecked by default. This should help preventing this from happening again.

**Closed by StellaHuang95** 2023-08-23 21:15 UTC
Labels: needs triage
