### ISSUE TITLE
"Python was not found; run without arguments to install from the Microsoft Store..." appeared in Python project.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7052] opened 2022-06-17 06:19 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/174236582-37a8f6d3-20ce-4632-b3ba-2ea6d68350ba.png)

Python from VS.

**Steps to Reproduce**

1. Create a Python Application.

**Additional context and screenshots**

![image](https://user-images.githubusercontent.com/82852072/174236857-383c7830-60db-4fb0-befc-43196701286d.png)

## Logs

<details>

<summary>Output for <code>General</code> in the <code>Output</code> panel 
</summary>

<p>

```
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
AssignProcessToJobObject: (87) The parameter is incorrect.


Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
```
</p>

**Comment by int19h** [comment] 2022-06-17 15:46
Which Python environment is displayed as active in Solution Explorer?

**Comment by AdamYoblick** [comment] 2022-06-17 18:40
Yeah I'm curious if python was actually installed at all. The email says the Python that came with VS was used, which should be Python 3.9 64-bit, but this error is showing that maybe the Python 3.9 checkbox wasn't checked when the workload was installed?

**Comment by ttSpace** [comment] 2022-06-20 02:02
![image](https://user-images.githubusercontent.com/82852072/174512007-499a2853-af1f-407f-a904-755eb69f3a07.png)

Python installed from VS.

![image](https://user-images.githubusercontent.com/82852072/174509273-63a72fd4-9c91-4908-97d5-c74d97d5effd.png)

**Comment by ttSpace** [comment] 2022-06-20 06:27
I can repro this in today's build.

![image](https://user-images.githubusercontent.com/82852072/174538096-baa959ce-b2e3-40de-9131-e60beaabf4a9.png)

## Logs

<details>

<summary>Output for <code>General</code> in the <code>Output</code> panel 
</summary>

<p>

```
Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90PPython was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90PPython was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90PAssignProcessToJobObject: (87) The parameter is incorrect.
```
</p>

**Comment by AdamYoblick** [comment] 2022-06-20 15:13
I think this is an issue with the VS installer not cleaning up registry keys properly. We've seen things like this in the past.

Can you verify that the following folder exists on your machine? `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64`
This is where VS installs python.

If python isn't there, there might be stale registry keys that VS uses to check for existing installations. To fix the registry, do the following:

1. Run Start -> regedit
2. Delete `Computer\HKEY_CURRENT_USER\Software\Python` (this will mess up any other python installs you have)
3. Delete `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Python` (this will mess up any other python installs you have)
4. Run VS again and modify your installation. Python 3.9 should now be unchecked. Check it and click on Modify and it will be installed.
5. Now verify that the following registry entry exists: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.9`
6. Verify that the installed python is actually on disk at `C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64`

I did these steps and I was able to run python applications using the python that comes with VS.

**Comment by ttSpace** [comment] 2022-06-21 02:00
@AdamYoblick I didn't do anything else, python is here.

![image](https://user-images.githubusercontent.com/82852072/174697663-b10eaa96-f6f0-4e4c-9add-9055fba8fe15.png)

1. ```Computer\HKEY_CURRENT_USER\Software\Python``` does not exist.

![image](https://user-images.githubusercontent.com/82852072/174698673-a7f37161-85ba-489d-96ac-1729220c23b2.png)

2. ```Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Python\PythonCore\3.9``` It exists.

![image](https://user-images.githubusercontent.com/82852072/174699239-8ff23637-0470-4523-945b-142209cedf3a.png)

**Comment by AdamYoblick** [comment] 2022-06-22 22:20
I'm not able to repro this. I uninstalled all other pythons I had, made sure the registry entries were deleted, then installed Python 3.9 from the Visual Studio installer. When I run on the latest int preview it works just fine.

![image](https://user-images.githubusercontent.com/29436557/175162736-f203744d-def3-40e6-8e18-a514aea87752.png)

![image](https://user-images.githubusercontent.com/29436557/175162944-7621022c-c7b9-4bda-bf51-e25a51aedb31.png)

**Comment by AdamYoblick** [comment] 2022-06-23 22:26
Actually I take that back, I am able to repro this when creating a new project. Will look into it.

**Comment by AdamYoblick** [comment] 2022-06-23 22:26
This is a dupe of https://github.com/microsoft/PTVS/issues/7050, going to close this one out as a dupe.

**Closed by AdamYoblick** 2022-06-23 22:26 UTC
Labels: waiting for response

**Comment by perfectans** [comment] 2022-10-06 07:10
[[Solved] Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases](https://perfectans.net/python-was-not-found-run-without-arguments-to-install-from-the-microsoft-store-or-disable-this-shortcut-from-settings-manage-app-execution-aliases/)
