### ISSUE TITLE
The mixed-mode debugger was not end process automatically.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6545] opened 2021-05-31 06:49 UTC
**Environment**
![image](https://user-images.githubusercontent.com/59192491/120150423-a00d5300-c21d-11eb-9812-5adb8cf37f96.png)

**Steps to Reproduce**
1. Create new project: Visual C++ > Windows Desktop > Windows Console Application
2. Add below code in default file
```
#include <iostream>
#include <string>
using namespace std;
int main()
{
	string name;
	cout << "Please enter your name:";
	cin >> name;
	cout << "Hello, " << name << "!";
    return 0;
}
```
3. Ctrl + F5 to starting running
4. Select Debug > Attach to Process …
5. In the dialog that appears, select the appropriate process
6. Use Select… button to open the "Select Code Type" dialog in which you can select Python
	a. Select OK to close that dialog
![image](https://user-images.githubusercontent.com/59192491/120150553-c7642000-c21d-11eb-8961-f4ef631cd705.png)
7. Attach to start the debugger
8. Input any key to close the window
9. Observes

**Actual result**
The debug process was not end.
![debug](https://user-images.githubusercontent.com/59192491/120151850-57569980-c21f-11eb-8ec7-85ab5b96c2a6.gif)

**Comment by int19h** [comment] 2021-06-01 17:38
This is not a mixed-mode attach, since only Python is selected in Code Type - it needs to be Python + something else for mixed.

For regular attach-to-PID, the behavior of the existing implementation is to inject some code into the process that starts debugging immediately if it sees the Python runtime DLL already loaded, or else lie dormant until it is loaded (on the assumption that if you're attaching to the process explicitly specifying the Python code type, you expect it to host Python eventually). In this case, though, the native app never loads Python, and so this injected code never stops waiting, and debugging never actually properly starts.

**Comment by greazer** [comment] 2021-06-02 22:23
Closing as by design per @int19h comment.

**Closed by greazer** 2021-06-02 22:23 UTC
Labels: needs triage
