### ISSUE TITLE
Python environment wrongly detected in Visual Studio after IronPython v2.7.8 upgrade

### ISSUE THREAD

**Issue by VinayGupta23** [Microsoft/PTVS#4457] opened 2018-06-28 09:38 UTC
Hi,

I have been using IronPython 2.7.7 with Visual Studio without any problem. For 32-bit, there was `ipy.exe` and 64-bit had `ipy64.exe`.
After updating to IronPython 2.7.8, there was a change where 32-bit was moved to `ipy32.exe` and 64-bit to  `ipy.exe`.
Since then, the Python environment configuration has broken.

## What I tried

1. Repair installation of IronPython 2.7.8
2. Search through registry for manual editing - could not find IronPython paths as per what the [docs say](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio#fix-invalid-environments).

### 32-bit path is wrong:

![image](https://user-images.githubusercontent.com/8874825/42025982-96aa8596-7ae3-11e8-9eaa-6e9139d5ab51.png)

### 64-bit path is wrong:

![image](https://user-images.githubusercontent.com/8874825/42026010-a65b8cba-7ae3-11e8-8fc6-4dd3f4f98d00.png)

#### (No IronPython path options)

![image](https://user-images.githubusercontent.com/8874825/42026177-13ff68ea-7ae4-11e8-8d0e-c6e066235152.png)

![image](https://user-images.githubusercontent.com/8874825/42026134-f8e64380-7ae3-11e8-8773-e0341f1a6d2f.png)

**Comment by huguesv** [comment] 2018-06-28 16:51
You must be on 15.8 Preview, since we don't detect 2.7.8 on 15.7. Can you confirm?

I'm not seeing this behavior. I've tried a clean install of 2.7.8, and also tried installing 2.7.7 and then upgrading to 2.7.8. In both cases, the executables are correct. I clicked on every one of them and checked the bitness matches between the environment window and the version info that is printed in the console.

Can you show the contents of the IronPython install folder with the executables in it?

**Comment by VinayGupta23** [comment] 2018-06-29 05:38
## Visual Studio version

I'm running v15.3.3. Full details:

Microsoft Visual Studio Community 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA662
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA662
Microsoft Visual C# 2017

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

Azure App Service Tools v3.0.0   15.0.30728.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   3.0.17208.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50719.1

NuGet Package Manager   4.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python   3.0.17208.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Django support   3.0.17208.1
Provides templates and integration for the Django web framework.

Python - IronPython support   3.0.17208.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   3.0.17208.1
Profiling support for Python projects.

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

## Python installation

At path: C:\Program Files\IronPython 2.7

![image](https://user-images.githubusercontent.com/8874825/42075067-c0c0b0f4-7b8c-11e8-8a19-3a6d4db93812.png)

**Comment by huguesv** [comment] 2018-06-29 16:29
Folder is as expected, and things should work fine on 15.8, in which we've added detection of IronPython 2.7.8.

For now, your options are to either go back to IronPython 2.7.7, or add 2.7.8 as a custom environment, or install the 15.8 preview release (which can be done side-by-side with the stable release).

**Comment by huguesv** [comment] 2018-06-29 16:29
Duplicate of https://github.com/Microsoft/PTVS/issues/4092

**Closed by huguesv** 2018-06-29 16:29 UTC
