### ISSUE TITLE
Output is not showing in ipython interactive window

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7768] opened 2023-11-27 19:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Output-is-not-showing-in-ipython-interac/10519653)._

---
[severity:It's more difficult to complete my work]
I am trying to run some lines of code using ipython in interactive window but output is not showing. I crated a new conda environment because I think previous conda environments caused this. But issue remain same after installing new conda environment

---
#### Feedback Bot on 11/19/2023, 06:23 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-11-29 23:11
This is a dupe of https://github.com/microsoft/PTVS/issues/7219.

**Closed by StellaHuang95** 2023-11-29 23:11 UTC
Labels: duplicate
