### ISSUE TITLE
VS2022 cannot recognise python packages installed and reporting missing import error.

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/PTVS#6874] opened 2022-01-30 17:22 UTC
<img width="502" alt="image" src="https://user-images.githubusercontent.com/53593544/151710036-4f55b7fc-a678-4619-9bc6-ec3f27bd0de5.png">

I think the intellisense database is not responding any more in VS2022.
Please provide me a fix

**Comment by soumesh2002** [comment] 2022-01-30 17:23
Above screenshot, I have already installed pygame package but VS cannot be able to recognise the module

**Comment by AdamYoblick** [comment] 2022-02-09 23:38
Pretty sure this is a dupe of #6713 . If you restart Visual Studio (or re open the solution), do the errors go away?

**Comment by AdamYoblick** [comment] 2022-02-23 21:48
Hi @soumesh2002 , no you don't have to restart VS after every python module installation. That was just a workaround I was aware of until the bug is fixed. This is a dupe of https://github.com/microsoft/PTVS/issues/6713, so I'm going to close this out. Please refer to the linked issue for any updates. This is in our backlog to fix, but we have other tasks with higher priority unfortunately. Thank you for your patience.

**Closed by AdamYoblick** 2022-02-23 21:48 UTC
Labels: waiting for response
