### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7287] opened 2022-12-22 21:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10232207)._

---
**Sorununuzu burada açıklayın**  
  
  
===BU SATIRIN ALTINI DÜZENLEMEYİN===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 12/15/2022, 05:04 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-12-23 01:13
duplicate of https://github.com/microsoft/PTVS/issues/7238

**Closed by StellaHuang95** 2022-12-23 01:13 UTC
Labels: needs triage
