### ISSUE TITLE
.NET Framework build error reported for .pyproj

### ISSUE THREAD

**Issue by vsfeedback** [Microsoft/PTVS#6771] opened 2021-10-27 23:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-Framework-build-error-reported-for-/1555955)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:16.11]
When building solution with mainly C# projects, but also some Python .pyproj projects.

Error The reference assemblies for . NETFramework,Version=v4.0 were not found. 
To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks
<ProjectName> C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets 1217

---
#### Feedback Bot on 10/17/2021, 11:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by judej** [comment] 2021-11-03 22:26
dupe of #6747

**Closed as completed by judej** 2021-11-03 22:26 UTC
