### ISSUE TITLE
Intellisense doesn't work.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6895] opened 2022-02-28 06:34 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/155933700-0a869023-513d-4573-8f15-753ee5e8d676.png)

**Steps to Reproduce**
1. Create a Python Application.
2. Type ```import```
(FYI: https://docs.microsoft.com/en-us/visualstudio/python/editing-python-code-in-visual-studio?view=vs-2022 )

**Expected behavior**
 
As you type, your completion list should open and prompt for your input accordingly. 

**Additional context and screenshots**

Nothing came up.

![image](https://user-images.githubusercontent.com/82852072/155934887-32c45b6a-a131-4d2d-8017-f9f442f9bcb1.png)

**Comment by AdamYoblick** [comment] 2022-03-01 23:58
Looks like autocomplete is completely broken in the latest version of PTVS with latest pylance. I've confirmed that this isn't a pylance issue, since the same version of pylance works in VSCode. Also, nothing has changed in PTVS that would have broken this, so if I had to guess, I'd say something in VS changed - either LSP related or intellicode/intellisense related and we need to respond to the change, maybe a package update or something similar hopefully.

I will reach out to the LSP team and go from there. 😄

**Comment by ttSpace** [comment] 2022-03-02 09:01
In today's build ```17.2.0 Preview 2.0 [32301.385.main] ```, IntelliSense works.

![image](https://user-images.githubusercontent.com/82852072/156308827-b9153367-f22e-49b7-811a-c9b2423f662e.png)

**Comment by AdamYoblick** [comment] 2022-03-02 23:07
The fix has been merged to main by the LSP team at https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/VS/pullrequest/382745. We can confirm this works on our next CTI test run.

**Closed** 2022-03-02 23:06 UTC
Labels: needs investigation
