### ISSUE TITLE
Python 3.8 support for Visual Studio 2019

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/PTVS#6360] opened 2021-01-21 18:32 UTC
Python 3.8 is still not supported in Visual Studio 2019 IDE
Some of features are not supported as there is a warning when I create a new Python file in Visual Studio that my current Python is not supported in IDE(i.e. 3.8.5)

Visual Studio Code is a good alternative but Visual Studio 2019 is a better option for Python because it's a IDE

**Comment by AdamYoblick** [comment] 2021-01-27 00:17
Dupe of #5822

**Closed by AdamYoblick** 2021-01-27 00:17 UTC
Labels: enhancement, needs triage

**Comment by alexolog** [comment] 2021-01-30 06:39
> Dupe of #5822

Which has been open for 15 months without a peep from Microsoft.

For the record:
3.7 has been out of support for 7 months.
3.8 will go out of support in April.

**Comment by VladPutinEu** [comment] 2021-03-19 03:15
> > Dupe of #5822
> 
> Which has been open for 15 months without a peep from Microsoft.
> 
> For the record:
> 3.7 has been out of support for 7 months.
> 3.8 will go out of support in April.

Visual Studio is stuck on Python 3.7.8 which is currently only on security updates. The security updates will go away on January 27, 2023 (2 years and 3 months). 

The EOL dates are here:
https://endoflife.date/python
https://devguide.python.org/#status-of-python-branches
