### ISSUE TITLE
Attach to process; remote python debugging Qualifier -- remember previous?

### ISSUE THREAD

**Issue by abrownsword** [Microsoft/PTVS#847] opened 2015-09-25 21:15 UTC
It would be really great if the Attach to Process dialog, when set to Remote Python Debugging, would remember previous Qualifier values.  I'm constantly having to retype the same lengthy URL (or having to remember to copy it before entering the debugger).  Better yet the Available Processes window could be set up to look for particular servers.

**Comment by int19h** [comment] 2015-09-29 09:10
Dupe of #245

**Closed by int19h** 2015-09-29 09:10 UTC
