### ISSUE TITLE
Collapse to definitions is broken in VS 2022

### ISSUE THREAD

**Issue by niwax** [microsoft/PTVS#7016] opened 2022-05-25 11:47 UTC
**Describe the bug**
Since the upgrade from VS 2019 to 2022, "Collapse to definitions" does nothing in Python files. Clicking the [-] icon next to a class or function, or using the "toggle all" function collapses classes down to class[...] and functions to def[...], which is completely useless. The combination of both makes larger Python files pretty much impossible to navigate.

(I could swear it showed an "Unavailable for this file" error once, but as of now there is no response at all)

**Steps to Reproduce**
Pressing either Ctrl-M Ctrl-O, or using the edit menu in any Python file.

**Expected behavior**
Classes and functions are collapsed to their definitions "class XXX:" or "def XXX:" as they are in other languages or in VS 2019.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 17.2.2
PTVS version: 17.0.22089.1
Python version: 3.8 and 3.9

**Comment by BckHWP** [comment] 2022-05-25 19:27
I have same isssue.

**Comment by StellaHuang95** [comment] 2022-06-10 00:32
Going to close it out since it's a duplicate of #7032. Please comment and track it at this [link](https://github.com/microsoft/PTVS/issues/7032). Thank you.

**Closed by StellaHuang95** 2022-06-10 00:32 UTC
Labels: needs investigation
