### ISSUE TITLE
Prompt packages missing after create virtual environment successfully.

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#4952] opened 2018-12-29 09:02 UTC
VS Version: 28424.114.d16.0stg
Python Tool Version: 16.0.18354.1

Repro step:
1. Create "Polls Django Web Project"
2. Add virtual environment env
3.Wait for a few seconds and open manage.py file

Packages missing about virtual env  prompted in the top of vs, but packages of virtual environment "env" are installed successfully and displayed in the PE list, so packages should not be prompted for missing.
![image](https://user-images.githubusercontent.com/39871640/50536024-1019d980-0b8b-11e9-8a96-40dd66f1ff9c.png)

**Comment by huguesv** [comment] 2019-01-08 17:45
Duplicate of https://github.com/Microsoft/PTVS/issues/4945

**Closed by huguesv** 2019-01-08 17:45 UTC
