### ISSUE TITLE
reportMissingImports malfunction

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7380] opened 2023-02-06 19:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/reportMissingImports-malfunction/10259392)._

---
reports missing python module that is already installed in the current python environment in use (not global)

---
#### Feedback Bot on 1/23/2023, 10:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-02-07 23:25
dupe of #7068

**Closed by StellaHuang95** 2023-02-07 23:25 UTC
Labels: bug
