### ISSUE TITLE
Interactive Window is hang after entering '$reset' command

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7368] opened 2023-02-01 08:01 UTC
**Environment**
![image](https://user-images.githubusercontent.com/59192491/215983146-8c1b7265-2d5a-49d8-8a12-e167c381c09f.png)

**Steps to Reproduce**
1.Create a new project
2.Open a Interactive Window
3.Type '$help' to get REPL commands list
4.Type '$reset' and Enter

**Actual behavior**
![Python Interactive is hang](https://user-images.githubusercontent.com/59192491/215984765-c1e1e543-0655-4a41-8d1f-6eba83caa54f.gif)

**Comment by StellaHuang95** [comment] 2023-02-01 17:49
This will be handled as duplicate of https://github.com/microsoft/PTVS/issues/7064

**Closed by StellaHuang95** 2023-02-01 17:49 UTC
Labels: needs triage
