### ISSUE TITLE
Visual Studio does not support Python 3.12 officially 

### ISSUE THREAD

**Issue by youssefanjjar** [microsoft/PTVS#7977] opened 2024-08-11 12:46 UTC
Please add support for Python 3.12 in Visual Studio. This will enable developers to utilize the latest features and ensure compatibility with the broader Python ecosystem.

**Comment by debonte** [comment] 2024-08-11 22:55
Duplicate of https://github.com/microsoft/PTVS/issues/7769

**Closed by debonte** 2024-08-11 22:55 UTC
Labels: enhancement, needs repro
