### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by scott-xu** [microsoft/PTVS#5739] opened 2019-09-18 01:59 UTC
**Describe the bug**
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.2.19178.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.Tagging.SimpleTagger`1.UpdateBatchSpan(ITrackingSpan snapshotSpan)
   at Microsoft.VisualStudio.Text.Tagging.SimpleTagger`1.<>c__DisplayClass11_0.<RemoveTagSpans>b__0(TrackingTagSpan`1 tagSpan)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Microsoft.VisualStudio.Text.Tagging.SimpleTagger`1.RemoveTagSpans(Predicate`1 match)
   at Microsoft.PythonTools.Intellisense.TaskProvider.<RefreshAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.TaskProvider.Refresh()
```

**Steps to Reproduce**
1. Ctrl+Shift+F search a string from a folder
2. Click the matched py file from "find result" window

**Expected behavior**
open the py file

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/1913505/65099037-f579e000-d9f9-11e9-9558-0842bf86aa37.png)

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.2.5
PTVS version: 16.2.19178
Python version: IronPython 2.7.9
Debugger Type (if applicable): New debugger

**Diagnostics file**
N/A

**Comment by huguesv** [comment] 2019-09-18 20:30
Thanks. Should be fixed in 16.3, which will release soon.

Duplicate of https://github.com/microsoft/PTVS/issues/5368

**Closed by huguesv** 2019-09-18 20:30 UTC
Labels: needs triage
