### ISSUE TITLE
Editor Extension Error

### ISSUE THREAD

**Issue by dragoljub** [Microsoft/PTVS#495] opened 2015-06-20 01:34 UTC
I'm getting this error when opening up a pytvs solution in VS 2013 Ultimate on RC 2.2  
<entry>
    <record>877</record>
    <time>2015/06/20 01:32:04.782</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.Intellisense.SmartTagSource.AddImportTags(ISmartTagSession session, IList`1 smartTagActionSets)&#x000D;&#x000A;   at Microsoft.PythonTools.Intellisense.SmartTagSource.AugmentSmartTagSession(ISmartTagSession session, IList`1 smartTagActionSets)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.SmartTagSession.Recalculate()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.SmartTagSession.Start()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultSmartTagController.CreateSmartTagSessionsForTags(SnapshotSpan span)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultSmartTagController.OnTagAggregator_TagsChanged(Object sender, TagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>

**Comment by int19h** [comment] 2015-06-20 02:31
This is a dupe of #402 - already fixed in RC2.

**Closed by int19h** 2015-06-20 02:31 UTC
