### ISSUE TITLE
list pop() inside __next__ fails in debugger

### ISSUE THREAD

**Issue by rwarford** [Microsoft/PTVS#2073] opened 2017-01-13 17:19 UTC
See notes in the following code sample.  

Visual Studio 12.0.40629.00 Update 5
PTVS 2.2.31124.00
Python 3.4.4

```
class A():
    def __iter__(self):
        self.l = [1, 2]
        return self

    def __next__(self):
        if not self.l:
            raise StopIteration

        return self.l.pop()  # Set breakpoint here and pop always returns 2

for n in A():
    print(n) # Set breakpoint here (but NOT inside __next__) and the code works as expected.
```

**Comment by patrys** [comment] 2018-06-29 09:18
Even though this was reported first I think this issue should be marked as a duplicate of #3512 as that's where the discussion takes place.

**Comment by huguesv** [comment] 2018-10-30 20:00
This now works properly with ptvsd 4.x

**Closed by huguesv** 2018-10-30 20:00 UTC
Labels: area:Debugger, bug, priority:P1, resolution:investigate
