### ISSUE TITLE
Incorrect brace matching in Visual Studio editor for Python

### ISSUE THREAD

**Issue by dan31** [Microsoft/PTVS#5191] opened 2019-03-23 09:36 UTC
Hilighting the open brace doesn't always work with nested braces and newlines involved.

This behaviour is easy to reproduce in Visual Studio Professional 2017 Version 15.9.9. Please watch the hilight of the opening brace when the closing brace is matched.

![image](https://user-images.githubusercontent.com/7162535/54864403-246b0e00-4d57-11e9-9dcd-c66f690b60e5.png)

![image](https://user-images.githubusercontent.com/7162535/54864411-44023680-4d57-11e9-813a-4ebcf26feed9.png)

```
def more (self):
    return (
        (self.idx < self.lo_idx) or (self.hi_idx < self.idx) or
        (self.ts <self.lo_ts) or (self.hi_ts < self.ts))
```

I remember this has always been an issue with open brace matching.

**Comment by huguesv** [comment] 2019-03-24 18:56
Duplicate of https://github.com/Microsoft/PTVS/issues/4072

**Closed by huguesv** 2019-03-24 18:56 UTC
