### ISSUE TITLE
python3.12 is not supported on visual studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7759] opened 2023-11-20 02:05 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python312-is-not-supported-on-visual-st/10516510)._

---
Hello,

Heres my configuration :
windows 11 professionnal insider
visual studio 2022
python3.12
I get the message : some features is unavilable because python3.12 is unsupported on visual studio 2022

Could you please update visual studio 2022 python support to support python 3.12 ?

Best regards

Battant

---
#### Feedback Bot on 11/16/2023, 00:59 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Tajnology** [comment] 2023-11-23 23:31
> it is possible to disable the warning somehow? until python 3.12 is supported

If you want it to go away, you can open the .pyproj and change the Interpreter Version from 0.0 to 3.12. The real question is, why the !@#$ does a warning spam alert windows, when it should be relegated to the output section?? It's the worst use of alert windows I've seen since the 00s.

**Comment by tsikaad** [comment] 2023-11-24 18:54
it's very boring! Can you stop it from repeating again and again and again...

**Comment by cwebster-99** [comment] 2023-11-29 22:08
Duplicate of https://github.com/microsoft/PTVS/issues/7565

**Comment by AdamYoblick** [comment] 2023-11-29 23:08
Going to close this out as a dupe.

**Closed by AdamYoblick** 2023-11-29 23:08 UTC
Labels: needs triage

**Comment by nichervanessa** [comment] 2023-12-28 23:39
Can anyone help us we have the same problem in VS Studio pro 22

**Comment by AdamYoblick** [comment] 2023-12-29 04:54
> Can anyone help us we have the same problem in VS Studio pro 22

This issue is closed as a duplicate. Please use the linked issue for all updates. 

Thank you!

**Comment by valiram12** [comment] 2024-05-01 19:49
i want to thank Microsoft for the worst ide software i ever imagined could exist.

**Comment by AdamYoblick** [comment] 2024-05-01 20:27
> i want to thank Microsoft for the worst ide software i ever imagined could exist. 

Thanks for the constructive feedback 😄 

Adding support for a new python version is actually much more work than you might be aware of. 

Besides normal version checking there is debugger support, profiler support (which can get quite complicated since Python internals have changed significantly), mixed mode debugging (which is a separate thing from normal debugging), amongst other things. 

We are a very small team, so we have to do things in order of importance. Right now, Python 3.11 is much more widely used than Python 3.12, so we tend to lean that way when we have a choice. 

We will continue to listen to feedback and fix things where we can. I agree that the modal popup window is silly, I believe that's very old code. The error message should probably be moved to the output window or an info bar at the top. 

Thank you!

**Comment by jiataocai** [comment] 2024-10-27 03:54
the warning is still there, what is the progress?

**Comment by ctgreno1** [comment] 2024-10-31 00:37
It's just an info bar up top that you can dismiss.  No more modal.
