### ISSUE TITLE
Python debugging broken. E_INVALIDARG appears in several places

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6510] opened 2021-05-19 22:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-debugging-broken-E_INVALIDARG-ap/1425131)._

---
This is the same as the following issue which was never fixed. Please reopen and fix asap. It has rendered python development in Visual Studio completely useless.

https://developercommunity.visualstudio.com/t/ptvs-1675-debugging-broken-and-throws-e-invalidarg/1213708

---
#### Feedback Bot on 5/19/2021, 02:17 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by greazer** [comment] 2021-05-19 22:46
Sorry for the problems you're having here. However, we are unable to reproduce the problem but it appears it should have been fixed in Visual Studio 16.9.x. Please verify this is the build of VS you're using and also let us know what version of Python you have. Closing for now, but please reopen with the additional information. 

Thanks!

**Closed by greazer** 2021-05-19 22:46 UTC
