### ISSUE TITLE
Bug in Python 2.7 interactive

### ISSUE THREAD

**Issue by cweining** [Microsoft/PTVS#445] opened 2015-06-16 22:47 UTC
This is from Microsoft Connect bug filed in TFS - 1138969

code that uses "while" followed by any code that stops execution will cause first iteration of prompt to be displaced n,blank spaces. 
any further iterations function normally. Same code run in command window works fine without resulting in same behavior. 

```
>>> x = 5 
>>> while x > 0: 
... a = raw_input('get input: ') 
... x -= 1 
... 
get input: 8 
get input: 7 
get input: 6 
get input: 5 
get input: 4
```

**Comment by zooba** [comment] 2015-06-17 16:48
Fixed the formatted in the bug, but it's unclear what the issue is, so I suspect some info was lost in the transfer.

In any case, this is wontfix for 2.2.

**Closed** 2017-09-15 22:16 UTC
Labels: area:REPL, bug, resolution:wontfix
