### ISSUE TITLE
Test framework info bar is not shown after unload and reload the python project

### ISSUE THREAD

**Issue by xiaofeng0123** [microsoft/PTVS#5804] opened 2019-10-08 07:47 UTC
VS Version: 16.4.0 Preview 3.0 [29407.136.master]
Python Tool Version: 16.4.19275.1

**Steps to Reproduce**
1. Create a python application
2.Select "Property" page, select "Test" to set "Test Framework" to "pytest"
3.Unload and reload the python project
4.Open python file

**Expected behavior**
Test framework info bar should be shown after unload and reload the python project 

**Actual behavior**
Test framework info bar is not shown. 

Note:
Info bar is shown if close and reopen the VS

**Comment by RaymonGulati1** [comment] 2019-10-22 22:12
I've looked into this and the issue is that the "test" properties page doesn't save the data change before the project is unloaded. When the project is loaded again, the original data is loaded and the info bar will not be shown. This is a issue with all the property tabs, including General and debug. 

The "info bar is shown if close and reopen the VS" is because a save dialogue pops up asking the user to save the data. If the user saves the data, then the next time the solution is opened, the info bar will be displayed.

Closed as a low priority because it's an uncommon scenario and there is a very easy workaround: press "Control + S" to save the data or close the properties page before unloading the project.

**Closed by RaymonGulati1** 2019-10-22 22:12 UTC
Labels: area:Project System, bug
