### ISSUE TITLE
Clarify removed DB message in environments window

### ISSUE THREAD

**Issue by Yezoxant** [Microsoft/PTVS#3884] opened 2018-03-15 17:48 UTC
Whenever i try to refresh the completion db in visual studio it starts and then suddenly at analyzing standard library it quits and then i can click the button again. What i've tried so far.
- Repairing visual studio
- Deleting the python tools folder in appdata/local
- Reinstalling python 3.6

Btw i need python 3.6 64 bit for tensorflow.
[Diagnostic Info 2018-03-15T184628.txt](https://github.com/Microsoft/PTVS/files/1816493/Diagnostic.Info.2018-03-15T184628.txt)

**Comment by huguesv** [comment] 2018-03-15 18:15
Thanks for the report. It looks like you are hitting 1, possibly 2 known issues for which we have a fixes ready to be released in a minor 15.6.x update.

From the log, there this crash: https://github.com/Microsoft/PTVS/issues/3863

For Python 3.6, there was this major regression too: https://github.com/Microsoft/PTVS/issues/3853

Until that fix is out, I would recommend you try the "Use new IntelliSense" which you can enable in Tools/Options/Python/Experimental page. This should bypass the known errors and still give you completions.

**Comment by Yezoxant** [comment] 2018-03-15 18:39
unfortunately the recommendation you give didnt solve the issue. Is there any other way i could fix it?
Added a new version of the diagnostics
[Diagnostic Info 2018-03-15T193617.txt](https://github.com/Microsoft/PTVS/files/1816666/Diagnostic.Info.2018-03-15T193617.txt)

**Comment by zooba** [comment] 2018-03-15 19:00
When you say it didn't fix it, do you mean that the refresh failed again?

With the experimental option enabled, you shouldn't even be able to refresh any more. Make sure you restart Visual Studio after changing the option.

**Comment by Yezoxant** [comment] 2018-03-15 19:07
Well I followed what you said right now and then it says the database is disabled.
So when i click the reactivate intellisense database in my next session button, and I restart visual studio again, then i can refresh the db but the option in the experimental section is disabled.

**Comment by zooba** [comment] 2018-03-15 19:15
The new feature is that you can have IntelliSense without needing the database any more, so please don't reactivate it :) That's meant to help people who are having too much trouble with the new design that they need to switch back (which, as you've discovered, isn't a great idea until we release the next update to 15.6).

**Comment by Yezoxant** [comment] 2018-03-15 19:44
Well that means i gotta code without intelliSense right now?

**Comment by huguesv** [comment] 2018-03-15 20:44
You should get IntelliSense completions when "New style IntelliSense" is enabled (VS restart required after changing that option).

**Comment by zooba** [comment] 2018-03-15 22:19
> that means i gotta code without intelliSense right now?

It shouldn't do, unless you're not getting any IntelliSense with the new option enabled. In that case, we should take a look at your logs to see what's going wrong there. (The first set of logs you provided did not have the new option enabled.)

**Comment by the0dark0one** [comment] 2018-03-16 01:47
I am experiencing the same issue. I added the python development tools yesterday and immediately noticed that visual studio wasn't underlining anything.  I tried disabling the new option and using the intellisense DB but then I experienced the same error where refreshing halts in the middle.  I've attached my python diagnostic file.
[Diagnostic Info 2018-03-15T184525.txt](https://github.com/Microsoft/PTVS/files/1817668/Diagnostic.Info.2018-03-15T184525.txt)

**Comment by Yezoxant** [comment] 2018-03-16 09:17
![visualstudiobugs](https://user-images.githubusercontent.com/14781084/37512687-1cb58150-2903-11e8-87b7-0a4aad568e84.png)
I've added a photo with what i got right now. I restarted everything, PC visual studio and project and now some of the libraries are found by IntelliSense.

**Comment by zooba** [comment] 2018-03-16 16:37
On re-reading, we probably should have worded that message better... it should say "_only_ click the link below if you are having trouble". Sorry for that

**Closed** 2018-03-16 22:34 UTC
Labels: area:Environments, bug, priority:P0
