### ISSUE TITLE
LiveShare: Cannot  perform "Go to definition" via Ctrl+click on client

### ISSUE THREAD

**Issue by xiaofeng0123** [Microsoft/PTVS#5281] opened 2019-05-05 09:37 UTC
VS Version: 16.1.0 Preview 4.0 [28904.22.d16.1stg]
Python Tool Version: 16.1.19121.1

Repro step:
1. Type below code
    import decimal
    decimal.Decimal()
2. Ctrl+click on ‘Decimal' on client

Actual Result:
It doesn't go to the definition on client. On host, it can go to the definition.

Expect Result:
It should jump to the definition of the method on client.

**Comment by huguesv** [comment] 2019-05-06 18:22
This is a feature not supported by LiveShare.

I filed internal issue 888095

Closing since that's out of our control and not a bug.

**Closed by huguesv** 2019-05-06 18:22 UTC
Labels: upstream: vs
