### ISSUE TITLE
Task List Bugs

### ISSUE THREAD

**Issue by AdamYoblick** [microsoft/PTVS#7394] opened 2023-02-09 22:24 UTC
Some task list bugs found by Stella. Note that you won't be able to repro these until https://github.com/microsoft/pyrx/pull/2899 gets merged and a new version of pylance is released so you can consume it with a local PTVS build.

Repro steps:
1. Create a new Python project PythonApplication1.
2. Type `# TODO: this is task 1 from project 1` in PythonApplication1.py
3. Create another .py file PythonApplication12.py and type `# TODO: this is task 2 from project 1`
4. Open TaskList window, switch between the two .py files and observe the task lists.

Existing behavior is that the `# TODO: this is task 1 from project 1` shows up twice in the list. 
![task list](https://user-images.githubusercontent.com/100439259/211956694-3a0b056c-1d44-4369-a160-9b0943aeafca.gif)

I have also noticed that if I close this project and open another Python project, the tasks from the first project will remain on the task list, so this is what shows when I open the second project.
![image](https://user-images.githubusercontent.com/100439259/211956988-92596c6b-d5b6-48b5-936c-ff8464a6154e.png)

_Originally posted by @StellaHuang95 in https://github.com/microsoft/pyrx/issues/2899#issuecomment-1379708911_

**Comment by StellaHuang95** [comment] 2023-10-03 21:16
The cause is similar to this one: https://github.com/microsoft/PTVS/issues/7534. Should be fixed once that fix is in.

**Closed** 2023-10-05 18:09 UTC
Labels: bug, P2
