### ISSUE TITLE
using Anaconda unresolved import

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7361] opened 2023-01-31 18:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/using-Anaconda-unresolved-import/10262121)._

---
[severity:It's more difficult to complete my work]
Using current Anaconda.
installed package using "pip install ibapi" in Anaconda
created solution in Visual Studio Community with Anaconda as python environment.
But I get "cannot be resolved" on import statements from ibapi in VSCommunity
For example, "import ibapi"

I do not have this problem in Visual Studio Code.

---
#### Feedback Bot on 1/26/2023, 05:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-31 22:20
duplicate of https://github.com/microsoft/PTVS/issues/7068

**Closed by StellaHuang95** 2023-01-31 22:20 UTC
Labels: needs triage
