### ISSUE TITLE
Recurring Error Every Time I launch Visual Studio 2022

### ISSUE THREAD

**Issue by tom123277** [microsoft/PTVS#7270] opened 2022-12-12 16:25 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 17.0.22263.6

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\CompSci\development\modelling_project\Lib'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<GetModulesInLib>d__1.MoveNext()
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<>c__DisplayClass0_0.<HasModuleAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Interpreter.PackageManagerFactoryExtensions.<HasModuleAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Environments.AddVirtualEnvironmentView.<UpdateInterpreterAsync>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

**Comment by StellaHuang95** [comment] 2023-02-14 00:55
Hi @tom123277 , could you provide the repro steps so that we can further investigate? Thanks! This also looks like duplicate of https://github.com/microsoft/PTVS/issues/7291

**Comment by StellaHuang95** [comment] 2023-03-15 19:03
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊

**Closed by StellaHuang95** 2023-03-15 19:03 UTC
Labels: waiting for response
