### ISSUE TITLE
Python new method doesn't update list of methods on top right hand corner

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6824] opened 2021-12-15 17:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-new-method-doesnt-update-list-of/1604009)._

---
The only way I have found to reload the list is to close the file and reopen it.

Maybe there is a text changed event that can monitor for def [method name]():

It isn't major, but I have to do a search for new methods and that is if I remember the method name (5 minutes ago is sometimes purged already).

To duplicate this, add a new method to a class, write some content, and look for the method in the top right hand corner drop down, it won't be there.

If there is a reload method I don't know about please tell me.

Thanks

---
#### Feedback Bot on 12/5/2021, 11:52 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2023-01-26 22:28
Dupe of https://github.com/microsoft/PTVS/issues/6551

**Closed by AdamYoblick** 2023-01-26 22:28 UTC
Labels: P2
