### ISSUE TITLE
Python editor messes up whitespace and line endings, causes numerous merge conflicts

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7954] opened 2024-07-16 18:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-editor-messes-up-whitespace-and-l/10699513)._

---
I urge you not to dismiss this as a cosmetic issue because this is a significant problem that triggers numerous merge conflicts as different people open these messed up files and their IDE's fix the errors silently, including Visual Studio in some cases.

When the source file is set up to use LF line endings, pressing Enter when the caret is not at the very end of the line inserts CRLF. Only Python editor does this - TypeScript and C++ work fine. When the same file is opened in Visual Studio again, it asks whether mixed line endings should be fixed (may also be silent), causing conflicts with other people working with the same source files.

![vs-python-editor-whitespace.png](https://aka.ms/dc/image?name=Bd8724b5e12214867ad35ed8a3c9c65ba638561559088458247_vs-python-editor-whitespace.png&tid=d8724b5e12214867ad35ed8a3c9c65ba638561559088458247)

Similarly, just typing source code inserts those empty indentations, which other editors correct, also causing merge conflicts. Again, TypeScript and C++ editors don't exhibit this behavior.

Please, look into this. I lost count how many times pulling from a repository ended up in a conflict because of these whitespace changes.

---
#### Feedback Bot on 7/9/2024, 06:40 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-07-17 21:11
This is a duplicate of https://github.com/microsoft/PTVS/issues/7598. I agree it could be causing some trouble and definitely needs attention. Meanwhile, can you try navigating to Tools -> Options -> Environment -> Documents and disabling `Check for consistent line ending on load` as a temporary workaround?

**Closed by StellaHuang95** 2024-07-17 21:11 UTC
Labels: duplicate
