### ISSUE TITLE
Visual Studio cannot open WSL folders

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6789] opened 2021-11-16 20:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-cannot-open-WSL-folders/1576661)._

---
Hey, here is the screenshots. This is just a folder that contains python scripts in WSL. As you can see it's just an empty VS instance. There is no files or anything.

---
#### Feedback Bot on 11/9/2021, 10:39 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Samet Samet on 11/11/2021, 06:25 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2021-11-18 23:33
Closing as dupe of https://developercommunity2.visualstudio.com/t/Can-not-open-project-folders-that-are-ba/1310997

**Closed by AdamYoblick** 2021-11-18 23:33 UTC
Labels: needs triage
