### ISSUE TITLE
Visual Studio 2022 intellisense autocomplete erroneous deletions

### ISSUE THREAD

**Issue by cshultz117** [microsoft/PTVS#6885] opened 2022-02-14 11:09 UTC
After selecting auto complete, especially when referencing a member variable or function to an object, intellisense will select either until the next whitespace character or sometimes until end of line for the insert. I have tested the behavior in other versions of visual studio, it appears to be specific to vs 2022.

**Steps to Reproduce**
1. Use tab completion when not at end of line.

**Expected behavior**
auto complete should insert in place, without replacing unnecessary characters after the position of the cursor.

**Additional context and screenshots**
Before using tab complete: 

![w4euF79](https://user-images.githubusercontent.com/38080556/153852789-a8389fc2-69e1-4c1a-8530-2e9bf63da2ed.png)

After tab completing:
![KkV3cvo](https://user-images.githubusercontent.com/38080556/153852863-5d7639f2-7ce6-49c3-a013-ecaad9ba2821.png)

**Comment by AdamYoblick** [comment] 2022-02-15 18:54
Seems related to https://github.com/microsoft/PTVS/issues/6786 and https://github.com/microsoft/PTVS/issues/6833, not sure if they are dupes but definitely related.

**Comment by StellaHuang95** [comment] 2022-06-08 19:42
Should be a duplicate of #6786

**Closed by StellaHuang95** 2022-06-08 19:42 UTC
Labels: needs investigation

**Comment by DanielLigon** [comment] 2022-12-20 16:22
Currently having this issue on a fresh install of Visual Studio 2022 in all languages, mostly just tried the C languages. I can't even edit anything without having to retype the entire line of code because everything gets typed over instead of shifted. Any updates when this might be fixed?
