### ISSUE TITLE
interactive terminal not working properly

### ISSUE THREAD

**Issue by ryan413** [Microsoft/PTVS#1718] opened 2016-10-13 17:10 UTC
It will work when i launch up a fresh instance of VS, but after while (maybe after switching between python environments), when i select text and select send to python (or CTRL+E as I tytpically use), all that happens is a blank line is returned in the interactive terminal.

example:
(interative terminal looks like below)

```
>>>
```

i select text like below and press CTRL+E twice

```
with open('workfile', 'r') as f:
     read_data = f.read()
```

(interactive terminal now looks like this (two lines now but no code ??)

```
>>>
>>>
```

**Comment by ryan413** [comment] 2016-10-13 17:21
while I'm on the subject, when I try to copy paste the above open code in interactive, i get error message because for some reason it doesn't like when I paste in multi-line commands...
```

>>> 
>>> with open(file, 'r') as f:
  File "<stdin>", line 1
    with open(file, 'r') as f:
                             ^
SyntaxError: unexpected EOF while parsing


```

the code works when written manually or one-line:

```
>>> with open(file, 'r') as f:
...     data = f.read()
... 
>>> with open(file, 'r') as f: data = f.read()
... 

```

**Comment by huguesv** [comment] 2016-10-14 19:48
Thanks for reporting this.

I've been able to repro the copy/paste into REPL bug in PTVS 3.0, but not in PTVS 2.2.5 (which I assume is what you are using?).  Send to REPL works fine, but Copy/Paste into REPL gives the parse error.

I haven't yet been able to repro the other bug where Send to REPL is sending empty lines.  When that happens, is there a way to make it work again? Do you have to restart VS?

**Comment by zooba** [comment] 2017-09-15 22:09
This is a duplicate of #2488 (despite being reported first - we'll track with the other one)

**Closed by zooba** 2017-09-15 22:09 UTC
Labels: area:REPL, bug, resolution:wontfix
