### ISSUE TITLE
Python/Native Debugging not available in VS 2022 Preview 4

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6729] opened 2021-09-22 15:47 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PythonNative-Debugging-not-available-in/1532054)._

---
I have installed Visual Studio 2022 Preview 4 with "Python native tools" and I don't see option "Python/Native Debuggin" like I had with VS 2019.
Attached screenshots of my settings.
! [Capture2.PNG] (https://aka.ms/dc/image?name=Bfccc9e6ba7a9420a80af49a06a8e7670637674052749418062_Capture2.PNG&tid=fccc9e6ba7a9420a80af49a06a8e7670637674052749418062)

! [Capture3.PNG] (https://aka.ms/dc/image?name=Be09de1d6623744358297151d3593f6df637674053607490479_Capture3.PNG&tid=e09de1d6623744358297151d3593f6df637674053607490479)

---
#### Feedback Bot on 9/17/2021, 00:56 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by bschnurr** [comment] 2021-09-27 16:25
closing due to duplicate of #6712

**Closed by bschnurr** 2021-09-27 16:25 UTC
Labels: Investigate
