### ISSUE TITLE
Unable to debug Python tests in mixed Python/C++ project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6857] opened 2022-01-19 21:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Unable-to-debug-Python-tests-in-mixed-Py/1631912)._

---
I am working on Microsoft DeepSpeed: https://github.com/microsoft/DeepSpeed
I opened the project as folder, and added a few configuration options for Visual Studio to get Python part recognized:

This is my PythonSettings.json:

```js
{
  "Interpreter": "CondaEnv| CondaEnv|deepspeed",
  "TestFramework": "pytest",
  "UnitTestRootDirectory": "tests\\unit",
  "UnitTestPattern": "test_*.py"
}
```

I can discover and run tests from Test Explorer no problem. However, when I try to debug them no breakpoints are getting hit. I suspect native debugger starts instead of Python debugger because the project has a C++ component.

---
#### Feedback Bot on 1/10/2022, 00:08 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-01-26 22:27
@int19h Do you have an idea about what's going on here?

**Comment by StellaHuang95** [comment] 2022-06-10 18:48
Seems related to #7034

**Comment by int19h** [comment] 2022-06-15 17:35
Almost certainly a dupe of https://github.com/microsoft/PTVS/issues/6796

**Closed by int19h** 2022-06-15 17:35 UTC
