### ISSUE TITLE
Imports are not resolved for reopened project

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#3660] opened 2018-01-29 20:51 UTC
1. Create new bottle project, create virtual environment.
1. Open `app.py`
1. Close VS
1. Reopen VS, open previously created project

**Actual**: imports aren't highlighted
![image](https://user-images.githubusercontent.com/8933858/35533622-f8681f8a-04f2-11e8-8945-b76bfae568fe.png)

If you close and reopen file, everything works.

**Comment by huguesv** [comment] 2018-01-29 20:58
I'm not seeing this with these exact steps, but after closing/reopening app.py and routes.py look at the colorization:
![image](https://user-images.githubusercontent.com/1696845/35534002-fef8382a-04f3-11e8-84dc-bf6859773b9f.png)

I did not to any editing at all, just open/close/reopen file.

**Comment by AlexanderSher** [comment] 2018-01-29 22:06
Another example of missing highlighting:
![image](https://user-images.githubusercontent.com/8933858/35537021-96afb55e-04fd-11e8-915d-94b4e0eb3d3e.png)

**Comment by zooba** [comment] 2018-01-31 23:39
So I'm not sure I have 100% fix, but it's certainly not trivially reproducible on my machine any more (which is all I have to test on right now).

Essentially, these are all caused by the text buffer not being correctly associated with the current analyzer, which largely occurs when a text view is opened before the project is loaded and we have to do the dance to switch analyzer. That had one or two places where it could lose a race, and then there was a case where we'd associate it correctly but the analyzer would hit a deadlock importing a module and never update the analysis (though that may only have occurred with the analyzer running in-proc).

So hopefully with those cleared up you should always get proper analysis after opening a file, regardless of when it's opened, though it may take a few seconds (or longer for large projects).

**Closed** 2018-02-02 05:00 UTC
Labels: area:Editor, bug, priority:P1
