### ISSUE TITLE
Support Macros in Python project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7884] opened 2024-04-29 14:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Support-Macros-in-Python-project/10628352)._

---
It would be handy to have the $(Platform) macro available in a python project's property page.

Platform is currently greyed out. Obviously, it doesn't apply to Python, but in the script arguments you can see one argument is "Win32", and for platform x64 the argument must then be "x64". I have to remember to manually change it when I change platforms. It is a place for mistakes.

![Capture3.jpg](https://aka.ms/dc/image?name=B397565add14a4c708d3674ac06beb425638475012960553723_Capture3.jpg&tid=397565add14a4c708d3674ac06beb425638475012960553723)

---
#### Feedback Bot on 4/1/2024, 05:38 PM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment] 2024-04-29 21:24
This is a dupe of https://github.com/microsoft/PTVS/issues/7292

**Closed by StellaHuang95** 2024-04-29 21:24 UTC
Labels: needs triage
