### ISSUE TITLE
Deletion of folded Python code crashes VS

### ISSUE THREAD

**Issue by cweining** [Microsoft/PTVS#446] opened 2015-06-16 22:49 UTC
This is from a Microsoft Connect bug, #1172214 file in TFS.

In open Python file, I fold the function, mark it with the mouse and press delete. This leads to a crash of VS. 
This is my setup: 
Microsoft Visual Studio Community 2015 RC 
Version 14.0.22823.1 D4REL 
Microsoft .NET Framework 
Version 4.6.00057 
Python Tools for Visual Studio 2.2.30427.00 
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers. 
Python Tools for Visual Studio - Profiling Support 2.2.30427.00 
Profiling support for Python projects.
 
---------------------
Callstack:
> KERNELBASE.dll!RaiseException(unsigned long dwExceptionCode, unsigned long dwExceptionFlags, unsigned long nNumberOfArguments, const unsigned long * lpArguments)  Line 828 C
  [Managed to Native Transition] 
  mscorlib.dll!System.ThrowHelper.ThrowArgumentException Line 72 + 0x2f bytes C#
  mscorlib.dll!System.Collections.Generic.Dictionary.Insert Line 336 + 0xa bytes C#
  Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.UpdateTextVisuals Line 91 + 0x6a bytes C#
  Microsoft.VisualStudio.Platform.VSEditor.dll!Microsoft.VisualStudio.Text.Editor.Implementation.TextContentLayer.ArrangeOverride Line 160 C#
  PresentationFramework.dll!System.Windows.FrameworkElement.ArrangeCore Line 4663 C#
  PresentationCore.dll!System.Windows.UIElement.Arrange Line 900 C#
  PresentationCore.dll!System.Windows.ContextLayoutManager.UpdateLayout Line 353 C#
  PresentationCore.dll!System.Windows.ContextLayoutManager.UpdateLayoutCallback Line 589 C#
  PresentationCore.dll!System.Windows.Media.MediaContext.InvokeOnRenderCallback.DoWork Line 1561 + 0xe bytes C#
  PresentationCore.dll!System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks Line 1949 + 0x1c bytes C#
  PresentationCore.dll!System.Windows.Media.MediaContext.RenderMessageHandlerCore Line 1826 C#
  PresentationCore.dll!System.Windows.Media.MediaContext.RenderMessageHandler Line 1721 C#
  WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall Line 104 + 0xa bytes C#
  WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen Line 37 + 0x11 bytes C#
  WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl Line 583 + 0x3c bytes C#
  WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext Line 526 + 0x25 bytes C#
  mscorlib.dll!System.Threading.ExecutionContext.RunInternal Line 954 + 0xd bytes C#
  mscorlib.dll!System.Threading.ExecutionContext.Run Line 901 + 0xd bytes C#
  mscorlib.dll!System.Threading.ExecutionContext.Run Line 890 + 0xe bytes C#
  WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke Line 441 C#
  WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue Line 2232 C#
  WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook Line 2485 C#
  WindowsBase.dll!MS.Win32.HwndWrapper.WndProc Line 341 + 0x81 bytes C#
  WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation Line 494 + 0x18 bytes C#
  WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall Line 104 + 0xa bytes C#
  WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen Line 37 + 0x11 bytes C#
  WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl Line 1445 + 0x2f bytes C#
  WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc Line 392 + 0x38 bytes C#
  [Native to Managed Transition] 
  user32.dll!__InternalCallWinProc@20()  Line 116 Asm
  user32.dll!UserCallWinProcCheckWow(_ACTIVATION_CONTEXT * pActCtx, void * pfn, HWND__ * hwnd, _WM_VALUE msg, unsigned int wParam, long lParam, void * pww, int fEnableLiteHooks)  Line 168 + 0x1b bytes C
  user32.dll!DispatchMessageWorker(tagMSG * pmsg, int fAnsi)  Line 2680 + 0x1f bytes C
  user32.dll!DispatchMessageW(const tagMSG * lpMsg)  Line 1000 + 0xa bytes C
  msenv.dll!MainMessageLoop::ProcessMessage(IMsoStdComponentMgr * pstdcm, IVsWindowManager * pIVsWindowManager, tagMSG & msg)  Line 1534 C++
  msenv.dll!CMsoCMHandler::EnvironmentMsgLoop()  Line 450 C++
  msenv.dll!CMsoCMHandler::FPushMessageLoop(unsigned long uReason)  Line 358 + 0x7 bytes C++
  msenv.dll!SCM::FPushMessageLoop(SCMI * pscmi, unsigned long uReason, void * pvLoopData)  Line 2260 + 0x7 bytes C++
  msenv.dll!SCM_MsoCompMgr::FPushMessageLoop(unsigned long dwComponentID, unsigned long uReason, void * pvLoopData)  Line 2996 C++
  msenv.dll!CMsoComponent::PushMsgLoop(unsigned long msgloop)  Line 705 C++
  msenv.dll!VStudioMainLogged()  Line 1191 C++
  msenv.dll!VStudioMain(MAINPARAM * pMainParam)  Line 1272 + 0x5 bytes C++
  devenv.exe!util_CallVsMain(MAINPARAM * pMainParam, int * piRes)  Line 1080 + 0x4 bytes C++
  devenv.exe!CDevEnvAppId::Run(wchar_t * wszCmdLine, int nCmdShow)  Line 746 + 0x10 bytes C++
  devenv.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * lpCmdLine, int nCmdShow)  Line 66 C++
  devenv.exe!__tmainCRTStartup()  Line 618 + 0xe bytes C
  kernel32.dll!BaseThreadInitThunk(unsigned long RunProcessInit, long (void *)* StartAddress, void * Argument)  Line 78 + 0x2 bytes C
  ntdll.dll!__RtlUserThreadStart(long (void *)* StartAddress, void * Argument)  Line 1029 C
  ntdll.dll!_RtlUserThreadStart(long (void *)* StartAddress, void * Argument)  Line 944 + 0xb bytes C

**Comment by zooba** [comment] 2015-06-17 16:45
Duplicate of #348

**Closed by zooba** 2015-06-17 16:45 UTC
Labels: duplicate
