### ISSUE TITLE
An Unexpected Error: Build 16.4

### ISSUE THREAD

**Issue by lefig** [microsoft/PTVS#6047] opened 2020-03-20 12:41 UTC
Hi there,

I have this infrequent exception to report:

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.4.19310.1

System.NotSupportedException: version 130 is no longer in memory
   at Microsoft.PythonTools.Intellisense.LocationTracker.GetLineLocations(Int32 version)
   at Microsoft.PythonTools.Intellisense.BufferParser.GetChanges(PythonTextBufferInfo buffer, ITextVersion curVersion)
   at Microsoft.PythonTools.Intellisense.BufferParser.<GetUpdatesForSnapshot>d__45.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Intellisense.BufferParser.<ParseBuffersAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
``

**Comment by huguesv** [comment] 2020-03-24 18:39
Thanks. The work part of https://github.com/microsoft/PTVS/issues/5210 will take care of this.

**Comment by lefig** [comment] 2020-03-26 22:17
Thank you too.

**Comment by huguesv** [comment] 2020-07-06 20:10
We have a few of these filed. I'll close this one as duplicate of https://github.com/microsoft/PTVS/issues/5725

**Closed by huguesv** 2020-07-06 20:10 UTC
Labels: area:IntelliSense, area:Legacy Language Support, bug
