### ISSUE TITLE
No autocompletion for Python keywords such as assert, sorted, class etc

### ISSUE THREAD

**Issue by AlexArcPy** [Microsoft/PTVS#2710] opened 2017-06-21 22:23 UTC
If you start typing `assert` in the Python module, you wouldn't get any suggestions. Many other Python IDEs support this out-of-the-box. Is there any configuration that has to be done or is it like this by design?

If you type `as` and then hit Ctrl-Space, you would see the list of suggestions but needing to press Ctrl-Space for this is a pain. Any way to fix that?

**Comment by zooba** [comment] 2017-06-21 22:25
Duplicate of #2709

**Closed by zooba** 2017-06-21 22:25 UTC
Labels: duplicate
