### ISSUE TITLE
Program can not end automatically with using debugger in remote debugger. 

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/PTVS#5808] opened 2019-10-10 08:09 UTC
VS Version: 16.4.0 Preview 3.0 [29409.183.master]
Python Tool Version: 16.4.19275.1

**Steps to Reproduce**
1.Create python application named PythonApplication2 and typing code
```py
input('>')
from math import cos, radians
def make_dot_string(x):
    rad = radians(x)                             # cos works with radians
    numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
    st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
    return st
	
def main():
    for i in range(0, 1800, 12):
        s = make_dot_string(i)
        print(s)
main()
```
2.Make sure you have installed the latest ptvsd 4.3.2
3.Add breakpoint for the code in the line "from math ....."
4.Open command prompt window for python3.7(64 bit) and execute command"
python -m ptvsd --host 127.0.0.1 --port 4022
C:\Users\vwazho\source\repos\PythonApplication2\PythonApplication2\PythonApplication2.py"
5.Launch VS and Debug > Attach to Process, in dialog:
  a.Select connection type with Python remote(ptvsd)
  b.Connection target with 127.0.0.1:4022
 c.In Available processes list, select the appropriate python.exe, click "Attach"
6.Type enter in the console
7.Press F5 after the program stop at the bp

video for steps:
[debug (2).zip](https://github.com/microsoft/PTVS/files/3711530/debug.2.zip)

**Expected behavior**
Program can end automatically after debug.

**Additional context and screenshots**
Program can not end automatically, and I need to stop it with click the stop debugging button.

**Comment by int19h** [comment] 2019-10-10 08:31
As described, this would result the program stopping at the breakpoint that you've set, after you press Enter. At that point debugger is paused, waiting for you to continue the app (or stop debugging), by design. Is there a missing step?

**Comment by zhouwangyang** [comment] 2019-10-10 09:20
after press F5 and run all the codes, it can't stop debugging automatically.
![image](https://user-images.githubusercontent.com/39871640/66556095-38a31b00-eb82-11e9-9160-030c9ced69d0.png)
I need to click the stop debugging button to stop the program.

**Comment by huguesv** [comment] 2019-10-10 16:31
This seems to be a duplicate of https://github.com/microsoft/ptvsd/issues/1571

**Closed** 2019-10-14 17:49 UTC
Labels: needs triage, resolution:duplicate
