### ISSUE TITLE
When I try to use Environment Menu python for both 2022 and 2019, visual studio crashes

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6957] opened 2022-04-13 16:09 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/When-I-try-to-use-Environment-Menu-pytho/1704962)._

---
[severity:I'm unable to use this version]
When I try to use Environment Menu python for both 2022 and 2019, visual studio crashes. It was working fine but I THINK (not sure) it tried to install Python 3.10 out of nowhere, and then everything stopped working. and doesn't work.

---
#### Feedback Bot on 3/29/2022, 03:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by twalsh55** [comment] 2022-05-05 19:55
I have a similar problem in VS 2022 Pro & Community versions. After installing Python 3.10, I open the Python Environment window and it crashes.

**Comment by StellaHuang95** [comment] 2022-06-13 21:09
Sounds like a duplicate of #6944

**Comment by cwebster-99** [comment] 2022-11-07 22:54
Closing stale issue and in favor of #6944.

**Closed by cwebster-99** 2022-11-07 22:54 UTC
