### ISSUE TITLE
python intaractive window inn't opening in microsoft visual studio

### ISSUE THREAD

**Issue by shubhankskg** [Microsoft/PTVS#2714] opened 2017-06-22 02:51 UTC
i've just downloaded python environment but it isn't opening python interactive window.

![screenshot 86](https://user-images.githubusercontent.com/29611676/27415267-ba6cb0d8-5723-11e7-9ace-14ec30636de4.png)

**Comment by zooba** [comment] 2017-06-22 15:54
Can you press Ctrl+C at the dialog and paste the info here? The screenshot doesn't help us, unfortunately.

**Comment by Blealtan** [comment] 2017-06-23 11:12
Same error here. Error message is as shown below; sorry for this Chinese version and if this troubles, please inform me.

[Window Title]
devenv.exe

[Main Instruction]
发生意外错误

[Content]
打开此交互窗口时出错。

请按 Ctrl+C 复制此对话框的内容并向我们的问题跟踪程序报告此错误。

[V] 显示详细信息(D)  [关闭(C)]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: 未能从程序集“Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35”中加载类型“Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2”。
   在 Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   在 Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   在 Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   在 Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by zooba** [comment] 2017-06-23 16:26
That's fine, it's enough for me to recognize this issue.

We think it's to do with certain packages that are in both VS 2017 and VS 2017 Preview - have you installed Preview at any time recently? If so, we know the underlying cause and it's going to be fixed soon (it's an installer bug, and it affects every single team here, so we can't just rush into the solution).

So far, everyone who has uninstalled and reinstalled VS has fixed the problem.

**Comment by Blealtan** [comment] 2017-06-29 12:52
Emm... In fact I've mentioned it in another issue that I'm suffering from this problem after reinstalling the VS 2017 (over the Preview edition published last year...). I've just reinstalled my Windows yesterday due to some other reasons and I'll have a really, really fresh installed VS 2017 for test soon. I'll post my condition here then. Thank you.

**Comment by Blealtan** [comment] 2017-06-30 12:42
I've just finished my brand new VS 2017 installation and it shows up working pretty well. But why reset the whole Windows works on this? Maybe I failed to uninstall VS 2017 Preview cleanly enough? What a mess...

After all, thank you so much for your help.

**Comment by zooba** [comment] 2017-07-03 17:10
The problem is due to files being left over when upgrading, and there are a couple of places where they may have been left. We're still not 100% sure which bug is causing this particular problem (and it could be multiple), but in any case a full Windows reinstall is going to clean up basically everything.

We're hoping to find a fix that isn't so drastic :)

**Comment by zooba** [comment] 2017-09-13 23:21
See #2534 - closing this as a duplicate.

**Closed by zooba** 2017-09-13 23:21 UTC
