### ISSUE TITLE
Install Cloud Explorer as part of Python & DS VS2017 workloads

### ISSUE THREAD

**Issue by eclectir** [Microsoft/PTVS#1973] opened 2016-12-12 20:43 UTC
Currently installed by .NET workloads, but directly relevant to Python developer scenarios.

**Comment by huguesv** [comment] 2016-12-13 00:44
Closing as duplicate of https://github.com/Microsoft/PTVS/issues/1924

**Closed by huguesv** 2016-12-13 00:44 UTC
Labels: Azure, enhancement, Installation
