### ISSUE TITLE
reportMissingModuleSource: Even if the module is successfully installed, a warning will still be displayed in the output.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6713] opened 2021-09-09 06:17 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/132629336-37e36f45-14db-4707-90f8-76e19ea5a87b.png)

**Steps to Reproduce**
1. Create a Flask Web Project.
2. Click ```Create virtual environment```( Make sure Flask was successfully installed ).
3. Reload the Project.

**Expected behavior**

After Flask is successfully installed, no errors or warnings will be displayed.

**Additional context and screenshots**

The Flask was successfully installed, but still got that warning. ```reportMissingModuleSource	Import "flask" could not be resolved from source```	

![image](https://user-images.githubusercontent.com/82852072/132631380-0179bf52-ad17-4eed-bba3-bd887817b1fb.png)

![reportMissingModuleSource](https://user-images.githubusercontent.com/82852072/132631673-8ed66117-c59b-45ad-9531-c4737a778c3f.gif)

**Output info**
<details>
<p>

```
Info: Info: Pylance language server 2021.8.3 (pyright fa4194fd) startingServer root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\dist

Info: Info: Info: Warning: Info: Info: Info: Info: Info: Info: No configuration file found.No pyproject.toml file found.Setting pythonPath for service "FlaskWebProject7": "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\python.exe"stubPath C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\typings is not a valid directory.Assuming Python version 3.9Assuming Python platform WindowsSearching for source filesFound 3 source filesBackground analysis(1) root directory: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\microsoft\python\core\pylance\distBackground analysis(1) started









Info: Searching for source files
Info: Auto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env
Info: Found 3 source files
Info: Searching for source filesInfo: Info: 
Auto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files

Info: Searching for source files
Info: Auto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env
Info: Found 3 source files
Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env

Info: Found 3 source files
Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Warning: Info: Info: No configuration file found.No pyproject.toml file found.Setting pythonPath for service "FlaskWebProject7": "C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env\Scripts\python.exe"stubPath C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\typings is not a valid directory.Assuming Python version 3.9Assuming Python platform Windows





Info: Searching for source files
Info: Auto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env
Info: Found 3 source files
Info: Searching for source files
Info: Auto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\env
Info: Found 3 source files
Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envFound 3 source files


Info: Info: Searching for source filesAuto-excluding C:\Users\vting\source\repos\FlaskWebProject7\FlaskWebProject7\envInfo: 

Found 3 source files
```

</p>
</details>

**Comment by ttSpace** [comment] 2021-09-10 05:51
In today's build I got this warning ```reportMissingImports	Import "bottle" could not be resolved``` in Bottle Web Project.
BTW, The bottle was successfully installed.

![image](https://user-images.githubusercontent.com/82852072/132806149-54e7313d-2113-4cb9-bb9d-eb3c257255b6.png)

**Comment by linette-zyy** [comment] 2021-09-13 06:08
Environment
Pylance language server 2021.8.3
![image](https://user-images.githubusercontent.com/59192491/133031889-5659dabb-bf18-4973-9f03-efe5e86e5e36.png)
This issue also reproduced on my environment
I installed debugpy, but the wavy line still under debugpy.
![image](https://user-images.githubusercontent.com/59192491/133032151-d4c1a784-4482-40bd-999e-4381196cf876.png)
![image](https://user-images.githubusercontent.com/59192491/133032194-dbd324f1-9738-4cd8-9268-9783c2b01c1a.png)

**Comment by AdamYoblick** [comment] 2021-10-07 23:24
I was able to repro this after creating the environment and installing flask. But after I close the solution in VS and re-open it, there are no errors:

![image](https://user-images.githubusercontent.com/29436557/136475100-b17a2ada-0c94-466a-a8d0-109b2d820249.png)
![image](https://user-images.githubusercontent.com/29436557/136475115-396171c0-8af0-44d6-b800-b08551a4696d.png)

I'm thinking this is an issue with updating after the environment is changed. For example, I just manually UNINSTALLED flask from the virtual env, but I don't see any errors in the views.py file even though there should be.

Even unloading and reloading the project doesn't seem to update the error. But closing the solution and re-opening it does. I will look into what needs to be called to update the errors, maybe a call into the language server code.

**Comment by ttSpace** [comment] 2021-12-31 07:48
I can repro in toady's build ```17.1.0 Preview 3.0 [32030.14.main]```.

**Comment by ArchageXIII** [comment] 2022-05-03 07:47
This looks to still be an issue in preview 17.1.0 Preview 4.0 with python 3.10, restarting the solution does not force a re-evaluation for me for 3rd party packages.
to preproduce open default project set python environment to 3.10
from within vs manage python packages, I installed spookyhash
comes up as not resolved, restarting solution did not clear the warning (project runs just fine just intellisense not working for that package)
![image](https://user-images.githubusercontent.com/24798445/166419284-3bbbd1ac-904f-4614-b90a-d218e4350a2b.png)

**Comment by bschnurr** [comment] 2022-06-10 17:29
We need to refresh Pylance on env create/modify

**Comment by bschnurr** [comment] 2022-06-10 18:26
something like this.

```
     var interpreterOpts = project.Site.GetComponentModel().GetService<IInterpreterOptionsService>();
            _packageManager = interpreterOpts?.GetPackageManagers(factory).FirstOrDefault();
            if (_packageManager != null) {
                _packageManager.InstalledPackagesChanged += InstalledPackagesChanged;
                _packageManager.EnableNotifications();
            }

```

**Comment by bschnurr** [comment] 2022-06-17 16:46
vs 2022 Preview 4 will have a fix when its released

**Closed by bschnurr** 2022-06-17 16:46 UTC
Labels: P1, rel-note

**Comment by Yusseiin** [comment] 2022-10-22 03:22
Someone has find any solution?
I still have the same problem in VS 2022 17.3.6

**Comment by kubakolecki** [comment] 2022-11-08 20:28
Same for me. I have this problem in VS 2022 17.3.6.

**Comment by fuzzcan** [comment] 2022-11-10 21:56
Still hapenning in VS 2022 17.4.0

**Comment by Odin-son** [comment] 2022-11-24 03:39
same problem in VS 2022 17.4.1

<img width="802" alt="image" src="https://user-images.githubusercontent.com/33476636/203688757-87bdf827-46ab-4ecc-8550-dc1e458f7951.png">

**Comment by axelande** [comment] 2023-01-16 20:26
I have the feeling that the IntelliSense sometimes picks up information from the wrong Python installation

**Comment by axelande** [comment] 2023-01-17 11:46
> vs 2022 Preview 4 will have a fix when its released

@bschnurr the problem seems to be remaining...

**Comment by 19CMB94** [comment] 2023-01-24 13:06
I have the same problem in Version 17.4.3 when tring to import numpy (among other modules). Reloading the project or restarting VS does not help. The code can be exectued, but it's super annoying.

![tmp](https://user-images.githubusercontent.com/11294747/214299135-0acbedd6-0195-43d1-8d88-9af37debaa1f.png)

**Comment by ric394** [comment] 2023-05-04 04:36
I'm getting the same issue with vs community 17.5.5
Commonly mentioned fixes are not successful.

**Comment by Lyssimachia** [comment] 2023-05-07 16:08
Also getting the same issue. VS Community 17.5.5. In previous versions it used to affect only installed packages, now it also affects user folders with __include__.py.

**Comment by AliTasbihi** [comment] 2023-05-31 13:05
Yes, I have this problem, the program runs without problems, but the packages are not recognized in Visual Studio, please help me

**Comment by zorglob21** [comment] 2023-09-26 11:16
same problem...
