### ISSUE TITLE
No Longer Able to Set Python Editor for different file extensions in VS2022

### ISSUE THREAD

**Issue by mjanikas** [microsoft/PTVS#6926] opened 2022-03-16 16:31 UTC
**In past versions of the software I have always been able to set the Python Editor for a given file extension**
[The Python Editor is no longer in the "Editor" dropdown]

**Steps to Reproduce**
1. Tools -->
2. Options -->
3. Text Editor -->
4. File Extension -->
5. Enter new extension that you want to be treated like a py file
6. View the "Editor" dropdown list and the Python Editor is no longer there

I installed all the Python packages during installation as well as the Data Science Stuff.

**Comment by StellaHuang95** [comment] 2022-06-09 22:26
The option of Python Editor can be found in VS2019 but is not in the list in VS2022.
![image](https://user-images.githubusercontent.com/100439259/172955302-abaecc3d-f565-47aa-aa5b-105b50c26c17.png)

**Comment by StellaHuang95** [comment] 2022-06-13 16:59
duplicate of #6797

**Closed by StellaHuang95** 2022-06-13 16:59 UTC
Labels: enhancement
