### ISSUE TITLE
Error on opening Python Interactive Window

### ISSUE THREAD

**Issue by gnome71** [Microsoft/PTVS#2576] opened 2017-05-21 06:15 UTC
I get the following error when I try to open a Python Interactive Window. As requested in the Error Dialog I report it here:
--------------------------
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by huguesv** [comment] 2017-05-22 17:57
Closing as duplicate of https://github.com/Microsoft/PTVS/issues/2534

If you have more information that can help us repro, please post it in the above bug. For example, was this an upgrade from a previous build of VS 2017. If so, which build did you upgrade from?

Unfortunately, the only successful workaround that has been reported it uninstall/reinstall of VS.

**Closed by huguesv** 2017-05-22 17:57 UTC
