### ISSUE TITLE
Couldn't Install CPython 3.9 x64 ReturnCode:1603

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7249] opened 2022-11-30 16:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Couldnt-Install-CPython-39-x64-ReturnC/10196368)._

---
[severity:I'm unable to use this version] [regression] [worked-in:Before 17.4.0]
Couldn't Install CPython 3.9 x64 - received ReturnCode:1603.
  
  
===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 11/10/2022, 01:05 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 17:58
duplicate of https://github.com/microsoft/PTVS/issues/7238

**Closed by StellaHuang95** 2022-11-30 17:58 UTC
Labels: duplicate
