### ISSUE TITLE
Error when attaching mixed-mode debugger

### ISSUE THREAD

**Issue by Artfunkel** [Microsoft/PTVS#481] opened 2015-06-19 10:10 UTC
This appears every time I try to attach in mixed debugging mode to an application with an embedded interpreter:

> Process: modo.exe
> The requested attach was not completely successful.
> 
> Successfully attached these type(s) of code:
> Native
> 
> Failed to attach to these type(s) of code:
> Python: An operation is not legal in the current state.

This happens with Blender (Python 3 x64) as well as Modo (Python 2 x64).

Everything seems to work correctly despite the error.

**Comment by DominikGrabiec** [comment] 2015-10-01 05:49
This does not happen if you only select either Native or Python debugging, but only when you select to debug both. (I.e. the debugging steps in https://msdn.microsoft.com/en-us/library/8dbb3we5%28v=vs.85%29.aspx do not give any more information because it works correctly when only one is specified).

**Comment by tafify** [comment] 2015-12-16 12:04
I'm facing same issue. Anyone found a resolution for this?
I'm doing MMD for C++ & CPython 2.7.8

**Comment by tafify** [comment] 2016-03-05 01:14
@zooba can we get some traction here? this one is hurting us the most. Let me know if any trace is needed.

**Comment by denfromufa** [comment] 2016-03-05 02:03
I believe you need .pdb debug symbols for CPython in order to be able to do
mixed-mode cross-language debugging. Not sure if blender or modo provide
this, if not, then recompiling with debug mode is necessary.

**Comment by tafify** [comment] 2016-03-05 08:48
Hi @denfromufa,
PDBs has to match (generated from the same build of) the python build you use. I have recompiled CPython 2.7.11 release to generate its PDBs and added the symbols to VS debug settings.
If symbols do not match or not provided, VS (in mixed mode) will show a dialog requesting to update the symbols paths. That isn't what we are facing here.

**Comment by Artfunkel** [comment] 2016-03-05 12:25
@tafify, is this issue actually preventing you from debugging? I found that debugging worked normally in spite of the error message.

**Comment by zooba** [comment] 2016-03-07 15:46
@Artfunkel When you say "normally", could you set breakpoints in Python code? It looks like that should not have been possible from the error message.

@tafify Thanks for the reminder. More traces would be very valuable, as we have a lot of bugs that we cannot easily reproduce, and we simply don't have the time or manpower to dedicate to trying to recreate each one. The more information we can collect in advance, the easier it will be to narrow it down to the underlying issue.

**Comment by tafify** [comment] 2016-03-08 07:41
@zooba I have here logs from "Devenv /log" with my dxdiag log:
[vs_logs.zip](https://github.com/Microsoft/PTVS/files/162709/vs_logs.zip)

Not sure what other logs I can provide. Can I attach another debugger to debug the "attach to process" of PTVS? if so, can you wiki me how to build PTVS and install it in VS2015? maybe I can provide you with some stack trace.

**Comment by zooba** [comment] 2016-03-08 17:55
@tafify We have [build instructions](https://github.com/Microsoft/PTVS/wiki/Build-Instructions-for-PTVS) on the wiki already. You really only need to do a few prerequisites and then build and run the solution.

It seems like an `InvalidOperationException` is being raised somewhere, so if you break on those then you'll likely hit the right place when reproing the issue.

**Comment by Artfunkel** [comment] 2016-04-14 15:38
@zooba I've hit this problem again.

Breakpoints are hit, but when I hit them a window appears with the title "foo.py not found". There's a "browse and find" option, but clicking it doesn't do anything. However, the call stack and locals window are both correct. They even show the line number.

I don't recall the "file not found" problem from last time. That has probably been introduced since I opened this bug.

I'm using VS2015 and PTVS 2.2.3. I'm debugging Python 2 embedded in an x64 program.

**Comment by zooba** [comment] 2016-04-14 15:51
@Artfunkel What happens if you just open the file normally (Ctrl+O)? Do we show the breakpoint then?

I don't recall what the logic is here for mapping filenames, but maybe @int19h knows?

**Comment by Artfunkel** [comment] 2016-04-14 15:52
No, the breakpoint doesn't appear. If I create one in the file it immediately disappears.

**Comment by int19h** [comment] 2016-04-14 16:46
This is where mapping is handled - pretty similar to what we do for regular debugging:
https://github.com/Microsoft/PTVS/blob/master/Python/Product/Debugger/DkmDebugger/ModuleManager.cs#L30

**Comment by int19h** [comment] 2016-04-14 16:48
@Artfunkel, can you see foo.py in the Modules window, and what path does it have there (if any)?

**Comment by Artfunkel** [comment] 2016-04-14 17:02
I've discovered that the file not appearing was down to some script security we had in place. To answer your question, the module does appear and the path is the one I quoted above. Presumably it's the forward slash that causes problems.

The error on mixed mode attach persists, but doesn't apparently cause any problems. It just makes newbies think everything is broken. :)

**Comment by zooba** [comment] 2017-08-29 23:09
I'm 99% sure we fixed the InvalidOperationException in another issue, so I'm closing this for cleanliness reasons. If it occurs again, we can reopen or start a new bug.

**Closed by zooba** 2017-08-29 23:09 UTC
Labels: bug, Debugger
