### ISSUE TITLE
Task list is not working in VS2022

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7254] opened 2022-11-30 16:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Task-list-is-not-working-in-VS2022/10192598)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:VS2019]
The task list feature is not working in VS2022. I just installed VS2022 on a new machine and imported my settings from VS2019 from my old machine. However, none of the commented tasks register as tasks; even the TODOs don't show up.

---
#### Tracy Wang [MSFT] on 11/7/2022, 11:27 PM: 

(private comment, text removed)
#### Abhimanyu Venkatraman Sheshashayee on 11/7/2022, 11:35 PM: 

(private comment, text removed)
#### Feedback Bot on 11/8/2022, 00:08 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 17:54
duplicate of https://github.com/microsoft/PTVS/issues/7151

**Closed by StellaHuang95** 2022-11-30 17:54 UTC
Labels: needs triage
