### ISSUE TITLE
Cannot build C# library project referenced by IronPython project

### ISSUE THREAD

**Issue by suoranta** [microsoft/PTVS#2541] opened 2017-05-12 08:03 UTC
I have a solution with an IronPython project and a C# library project. IronPython project has reference to C# project. Unfortunately, C# project won't build because the Python project apparently locks the DLL. Only workaround seems to be to unload Python project, restart Visual Studio and then build.

Output (relevant part):
> error MSB3027: Could not copy "obj\Debug\TradingToolsLib.dll" to "bin\Debug\TradingToolsLib.dll". Exceeded retry count of 10. Failed.
>error MSB3021: Unable to copy file "obj\Debug\TradingToolsLib.dll" to "bin\Debug\TradingToolsLib.dll". The process cannot access the file 'bin\Debug\TradingToolsLib.dll' because it is being used by another process.

Background: Windows 10, Visual Studio Pro 2015 (14.0.25431.01 Update 3), IronPython 2.7.7.

**Comment by zooba** [comment] 2017-05-12 17:12
Yes, we load the DLL into its own AppDomain to provide Intellisense, but it is supposed to automatically destroy the appdomain when you rebuild.

It's been a while since I looked at that code - @DinoV may have a better idea what may be going wrong here or if there are any workarounds. (We are not releasing updating for VS 2015 anymore, but it may still be broken in VS 2017 and we'll want to fix it there.)

**Comment by JoshHeitzman** [comment] 2017-05-13 21:42
I'm hitting the same issue with VS 2015 as well.  It isn't necessary to even have a reference to the C# project.  It is also caused by a runtime only reference such as:
clr.AddReferenceToFileAndPath(assembly_filepath)

**Comment by suoranta** [comment] 2017-05-16 13:44
I can now confirm that this affects VS 2017 as well.

**Comment by gramster** [comment] 2019-11-20 17:56
Closing this issue; we are not investing any more in IronPython support due to low usage and high cost.

**Closed by gramster** 2019-11-20 17:56 UTC
Labels: area:Code Intelligence, bug, priority:P2
