### ISSUE TITLE
VS 2022: Interactive window doesn't work properly

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7895] opened 2024-05-08 19:14 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VS-2022:-Interactive-window-doesnt-work/10642776)._

---
After opening the interactive window (Extra | Python | Interactive window)  I entered a simple calculation:
>>> 3+5
From now on there was no obvious reaction except the processor was busy but provided no result

---
#### Feedback Bot on 4/21/2024, 07:45 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-05-08 19:15
Thanks for reporting the issue! I am closing this issue as dupe of https://github.com/microsoft/PTVS/issues/7868, please check the linked issue for progress. Thanks!

**Closed by StellaHuang95** 2024-05-08 19:15 UTC
Labels: duplicate
