### ISSUE TITLE
Django functions in context menu can only be used once

### ISSUE THREAD

**Issue by baylf2000** [microsoft/PTVS#6842] opened 2022-01-05 05:25 UTC
**Describe the bug**
When selecting Django commands from the Python contextual menu in a Django project, only one of these commands (Check, Make Migration, Migrate etc) can be run. The Django Management Console window opens, and the command is run successfully. After that, subsequent commands have no effect. The console window must be closed. Then a new django command can be run.

**Steps to Reproduce**
1. Run any of the Python Django commands from the contextual menu.
2. Try and run any of them for a second time. It will fail.
3. Close the management console output window.
4. Try again. It will work.
5. Try again. It will fail.
6. Close management console window.
7. Try again. It will work.
etc etc

**Expected behavior**
Commands should work every time without having to manually close the management console window every time.

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 
PTVS version: `Microsoft Visual Studio Community 2022 (64-bit) - Version 17.0.4`
Python version:
```
Python - Django support   17.0.21293.2
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.21293.2
Profiling support for Python projects.

Python - VC Project Support   17.0.21153.2
Provides support for launching C++ projects with Python debugging enabled.

Python with Pylance   17.0.21293.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.```

Python version: 3.8, 3.9, 3.10 all tested and confirmed affected.
```

**Comment by StellaHuang95** [comment] 2023-01-18 01:24
dupe of https://github.com/microsoft/PTVS/issues/6750

**Closed by StellaHuang95** 2023-01-18 01:24 UTC
Labels: P2
