### ISSUE TITLE
VisualStudio＋Pythonを使っているが、Intellisenseが邪魔。

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7030] opened 2022-06-08 16:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/VisualStudio＋Pythonを使っているが、Intellisenseが/10056378)._

---
入力の妨げになるので、OFFにして欲しい、または、OFFにすることができるようにして欲しい。

０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９
０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９０１２３４５６７８９

---
#### Tracy Wang [MSFT] on 5/29/2022, 07:14 PM: 

(private comment, text removed)
#### drbrains on 6/2/2022, 11:38 AM: 

(private comment, text removed)
#### Feedback Bot on 6/5/2022, 05:48 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-06-08 17:17
- Translation:

Since it will interfere with input, I want it to be turned OFF or OFF so that it can be turned off.

- Translation of response on 6/2/2022:

Thank you for contacting us.
It's reproducible right away, but I've been looking for an opportunity to get no unnecessary information into my Redacted shots and it's slow.

When you try to change a parameter as in an attachment. When 1 of =10 is changed to 2, intellisense does not appear, but if you erase 10 and make it 5, etc. Intellisense display comes out as attached, and unless you press the ESC key to erase it, you can not change the parameter of the next line with the ↓ key. This is the problem.

Please consider improvements. If possible, it would be nice to be able to switch ON / OFF with shortcut keys.

**Comment by StellaHuang95** [comment] 2022-06-09 20:51
Hi, thanks for your feedback. We are going to close this out since it's a duplicate of #6881. Please comment and track it at this [link](https://github.com/microsoft/PTVS/issues/6881). Thank you.

**Closed by StellaHuang95** 2022-06-09 20:51 UTC
Labels: enhancement
