### ISSUE TITLE
Interactive Window debugging after updating to Visual Studio 16.3.5

### ISSUE THREAD

**Issue by mrtflln** [microsoft/PTVS#5826] opened 2019-10-17 13:59 UTC
**Describe the bug**
I recently updated Visual Studio to v.16.3.5 and encountered a lot of trouble working with my Python project, which I was happily coding in Visual Studio for a long time - until now. 
The main issue is debugging with Interactive Window. It suddenly breaks the whole process if I enter a faulty command! 
Is there some incompatibility with the most recent update, or is there something wrong on my end?
Thanks in advance!

**Steps to Reproduce**
1. start debugging a script
2. open Interactive Window with Environment: Debug
3. type random letters in the Interactive Window ```>>> jhsgdfj```

**Expected behavior**
1. ```NameError: name 'jhsgdfj' is not defined``` appears in the Interactive Window
2. script continues to run!

**Additional context and screenshots**
The whole process exits.
![image](https://user-images.githubusercontent.com/34242162/67015163-647c4e80-f0f6-11e9-8d5e-1bfa7ffa0580.png)

**Sample Code**
```
>>> jhsgdfj
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: 16.3.5
PTVS version: 16.3.19252.1
Python version: 3.7

**Comment by huguesv** [comment] 2019-10-17 20:41
Thanks! Duplicate of https://github.com/microsoft/PTVS/issues/5827

**Closed by huguesv** 2019-10-17 20:41 UTC
Labels: needs triage, resolution:duplicate
