### ISSUE TITLE
Tabs/spaces are inserted after text when you paste the text after starting a new line using Enter.

### ISSUE THREAD

**Issue by Ark-kun** [Microsoft/PTVS#2574] opened 2017-05-19 10:59 UTC
Repro steps:
Copy some text e.g. "abcd"
Go inside some function.
Press Enter, Enter, Ctrl+V to insert a blank line and paste the text.
Observe that the cursor moved long way after the text. You can start typing and there is a 4-8-space gap between the pasted text and the typed text.

    def someFunc: #Press Enter here
        pasted    typed

**Comment by huguesv** [comment] 2017-05-19 13:59
Thanks! Closing as a duplicate of https://github.com/Microsoft/PTVS/issues/2398

**Closed by huguesv** 2017-05-19 13:59 UTC
