### ISSUE TITLE
Visual Studio IPython Interactive

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7227] opened 2022-11-30 16:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-IPython-Interactive/10211803)._

---
Hi Team,

There's no output when I run Python in IPython Interactive mode.

**Document for reference:**

https://learn.microsoft.com/en-us/visualstudio/python/interactive-repl-ipython?view=vs-2022

**Steps to reproduce:**

1. Follow the document to open Python Environments window in VS > examine the ipython and matpoltlib have been installed.
2. Click Overview tab > select Use IPython interactive mode > select Open interactive window to bring up the Interactive window.
3. Press Enter > type sample codes like 

```
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 5, 10)
y = x ** 2
plt.plot(x, y, 'r', x, x ** 3, 'g', x, x ** 4, 'b')
```
into the Interactive window and run it, you should see no output.

Besides, please note I tested with VS 2022 and VS 2019, Python 3.9, 3.10, 3.11 (64-bit) all didn't work(didn't test with Anaconda). 

**A similar issue:**

https://learn.microsoft.com/en-us/answers/questions/1102411/visual-studio-ipython-interactive.html

Please let me know if I miss something or if this a potential issue, please fix it.

Thanks

---
#### Feedback Bot on 11/24/2022, 01:10 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 18:04
duplicate of https://github.com/microsoft/PTVS/issues/7118

**Closed by StellaHuang95** 2022-11-30 18:04 UTC
Labels: needs triage
