### ISSUE TITLE
python issue using version 0.0?

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6996] opened 2022-05-11 16:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-issue-using-version-00/10025180)._

---
[severity:It's more difficult to complete my work]
What is wrong here you using version 0.0 some features might not works since visual studio no longer support this version url to more info did not give anything i use version 3.10 64 bits.

---
#### Feedback Bot on 4/27/2022, 08:17 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-05-11 18:16
This is a dupe of https://github.com/microsoft/PTVS/issues/6795

**Closed by AdamYoblick** 2022-05-11 18:16 UTC
Labels: needs triage
