### ISSUE TITLE
No output when execute file in Python interactive.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7770] opened 2023-12-01 05:35 UTC
**Environment**
![image](https://github.com/microsoft/PTVS/assets/59192491/f22a0578-f540-45c3-9880-0cf116080733)

**Steps to Reproduce**
Execute File in interactive window without any project open, just File->Open a python file, Debug->Execute File in Python interactive

**Expected behavior**
The file was executed and output result displayed on the interactive window.

**Additional context and screenshots**
No output when execute file in Python interactive.
![image](https://github.com/microsoft/PTVS/assets/59192491/e7f8cf76-c1c4-4dd4-aade-6af42ff93c36)

**Comment by StellaHuang95** [comment] 2023-12-01 19:50
That's a dupe of https://github.com/microsoft/PTVS/issues/7367

**Closed by StellaHuang95** 2023-12-01 19:50 UTC
Labels: needs triage
