### ISSUE TITLE
Unable to load numpy and pandas

### ISSUE THREAD

**Issue by udayguntupalli** [Microsoft/PTVS#5070] opened 2019-02-08 00:27 UTC
All, 
    I am trying something really simple. Import 2 simple modules which are already in my python environment. 

`import os 
import sys 
import numpy as np 
import pandas as pd
`
![image](https://user-images.githubusercontent.com/16611561/52451614-f4481280-2afc-11e9-9762-948813dfc537.png)

It gives me the following error. I have tried to uninstall and reinstall both packages multiple times. 
![image](https://user-images.githubusercontent.com/16611561/52451731-6b7da680-2afd-11e9-8b39-abab640f65c4.png)

![image](https://user-images.githubusercontent.com/16611561/52451777-9b2cae80-2afd-11e9-81cb-f48d31de20b9.png)

Any help is greatly appreciated

**Comment by huguesv** [comment] 2019-02-08 00:35
Duplicate of https://github.com/Microsoft/PTVS/issues/4820
There's a workaround of activating the environment from command prompt and starting VS from that prompt. See #4874 for details.

**Closed by huguesv** 2019-02-08 00:35 UTC
