### ISSUE TITLE
Undo after Extract Method causes Buffer content mismatch

### ISSUE THREAD

**Issue by AlexanderSher** [Microsoft/PTVS#3639] opened 2018-01-25 20:48 UTC
Build from 15.6rel, commit 0e2df20

1. Open `test_userdict.py` from `python2.7\test`
2. Select lines 63-70
3. Apply 'Extract Method' from light bulb, proceed with wizard
4. Undo (Ctrl-Z)

![image](https://user-images.githubusercontent.com/8933858/35411512-a623f742-01de-11e8-883c-19a4c93fc057.png)

May be related to #3634

**Comment by zooba** [comment] 2018-01-25 21:52
Given there's only one underlying cause here (unless you can provide the JSON logs and they show a different cause), I consider this a duplicate of #3634.

**Closed by zooba** 2018-01-25 21:52 UTC
