### ISSUE TITLE
Microsoft.Common.CurrentVersion.targets - The reference assemblies for . NETFramework,Version=v4.0 were not found

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6783] opened 2021-11-16 20:08 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/MicrosoftCommonCurrentVersiontargets-/1574872)._

---
[regression] [worked-in:17.0.0]
Since upgrading from VS2019 to VS2022, opening existing Python projects or creating new Python projects results in the following error:

```
The reference assemblies for . NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217	
```

There is no Developer Pack available for .NET Framework v4.0, and https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers indicates that it is no longer supported in VS2022.

I have confirmed that I have .NET Framework v4.8 installed, and I have uninstalled and reinstalled VS2022, but am still getting the same error.  The only Python packages that are installed are pip v21.3.1 and setuptools v58.5.3, both of which are up to date.  The issue itself does not prevent me from running the application.

---
#### Feedback Bot on 11/8/2021, 11:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Edward Talbot on 11/10/2021, 05:03 AM: 

<p>I also get this on a machine with a fresh Windows 11 install.</p>
<p>My folder at C:\Program Files\Reference Assemblies\Microsoft\Framework only contains v3.0 and v3.5, so it might be looking in there for a v4.0 folder that doesn’t exist.</p>
<p>I’m hesitant to install the original .NET Framework 4.0 on Windows 11.</p>
<p>Maybe it’s better to move to Visual Studio Code for Python projects.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2021-11-18 23:34
Dupe of https://github.com/microsoft/PTVS/issues/6747

**Closed by AdamYoblick** 2021-11-18 23:34 UTC
Labels: needs triage
