### ISSUE TITLE
VS 2017 15.9 Intellisense stop working when __init__.py file is added in a project

### ISSUE THREAD

**Issue by vermz99** [microsoft/PTVS#5370] opened 2019-06-13 16:04 UTC
The intellisense of some of my projects in my solution is not working at all. I don't even have color coding except on reserved keywords. I tried to reproduce the problem and what i think i found is that every time i have a `__init__.py` file in the project, the intellisense stops working. The `__init__.py ` files that i use have 4 lines:

```
from . import file1
from . import file2
from . import file3
from . import file4
```

The 4 files are in the same project as the `__init__.py` file. I use this `__init__.py` file to create my package. I have 5 projects in my solution. I managed to scope the problem by creating two projects with the same 10 .py files except that one has the `__init__.py` file and the other do not have it. 

Thanks.

**Comment by RaymonGulati1** [comment] 2019-06-13 16:18
Thank you for reporting this issue. PTVS is moving to a new language server which should hopefully fix this. If it doesn't, we will investigate deeper.

Would it be possible for you to share the files with us?

**Comment by vermz99** [comment] 2019-06-13 16:29
I scoped it to a new solution and a single project. Here's the files. In module1.py, the intellisense broke as soon as i added the `__init__.py` file.
[VS Bug.zip](https://github.com/microsoft/PTVS/files/3287154/VS.Bug.zip)

**Comment by RaymonGulati1** [comment] 2019-06-13 23:15
Thanks

**Comment by RaymonGulati1** [comment] 2019-06-25 00:05
@vermz99, I'm unable to reproduce this in VS 2019. Have you tried VS 2019? Can you still reproduce this in VS 2019?

**Comment by vermz99** [comment] 2019-06-25 00:11
I have only tried on 2017

**Comment by huguesv** [comment] 2019-07-02 22:36
Since we can't repro on 2019, we believe this may be fixed. If you can reproduce it on 2019, please reopen. Thanks.

**Closed by huguesv** 2019-07-02 22:36 UTC
