### ISSUE TITLE
vs studio 2022 collapse code hide class/function names

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7189] opened 2022-10-19 12:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/vs-studio-2022-collapse-code-hide-class/10167275)._

---
[severity:It's more difficult to complete my work]
In 2019, collapsing does not hide the class/function name and the contents of the parentheses after it。
Class Obj():
          def __init__(self):
                something here
                something here

after collapsing:
Class Obj():
          def __init__(self): ...

In 2022, the collapse hides the class/function name and the contents of the parentheses after it
after collapsing:
Class Obj():
          def...

---
#### Feedback Bot on 10/9/2022, 06:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-10-19 16:28
duplicate of https://github.com/microsoft/PTVS/issues/7032

**Closed** 2022-10-19 17:48 UTC
Labels: duplicate
