### ISSUE TITLE
Race condition getting plots from IPython mode

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#1163] opened 2016-03-17 19:20 UTC
Depending on how quickly data is displayed in the repl window, plots may end up in strange locations.

![image](https://cloud.githubusercontent.com/assets/1693688/13858103/554451ac-ec3a-11e5-9ed2-5f2a32a443a1.png)

This is because we insert the plot at the current caret location, but it's being marshalled from a background thread at the same time as the UI thread is writing each coloured span to the output (the image is at a boundary between Number coloured text and plain text).

We probably need to force some synchronization to ensure that the plot is inserted after all the printed output, but before the following input.

**Comment by huguesv** [comment] 2017-12-14 19:43
Duplicate of #601

**Closed by huguesv** 2017-12-14 19:43 UTC
Labels: area:REPL, bug, resolution:duplicate
