### ISSUE TITLE
python environment view can not show packages

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7811] opened 2024-01-24 18:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-environment-view-can-not-show-pac/10564951)._

---
In python environment view, when I change ths selection of overview/PyPI some time or upgrade a package, in PyPI mode I will see nothing....

---
#### Feedback Bot on 1/18/2024, 10:22 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2024-01-24 18:40
Close as dupe of #7715

**Closed by StellaHuang95** 2024-01-24 18:40 UTC
Labels: needs triage
