### ISSUE TITLE
Pylance Language server does not support Python 2.x. Type checking will be performed as in Python 3.x

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6858] opened 2022-01-19 21:28 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Pylance-Language-server-does-not-support/1632278)._

---
I have windows 10, and updated Python to 3.10.1 and now Visual Studio gives me the above problem whenever I start the program.

---
#### Feedback Bot on 1/10/2022, 00:23 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-01-24 23:05
Dupe of #6795

**Closed by AdamYoblick** 2022-01-24 23:05 UTC
Labels: needs triage

**Comment by alphgh** [comment] 2022-03-23 10:42
Same problem. Any solutions?

**Comment by razelbazil** [comment] 2022-04-18 22:57
Im having the same issue and "Pylance language server does not support python 2.x type checking will be performed as in python 3.x" popping up as soon as I start the project .

**Comment by Bosnianflajter2** [comment] 2022-04-23 11:11
I do have the same issue: "Pylance language server does not support python 2.x type checking will be performed as in python 3.x"
And after clicking on "OK" it aperas again. And then I can use VS.
Does anybody know how it can be solved?
