### ISSUE TITLE
The Solution Configurations and Solution Platforms are empty.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7345] opened 2023-01-20 06:22 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/213630136-c2b52755-aef2-4984-9f0d-3b98e4f7bacc.png)

**Steps to Reproduce**

1. Open folder in SE.
2. Add a new python file in folder.

**Expected behavior**

![image](https://user-images.githubusercontent.com/82852072/213630295-730cbb62-8512-4349-baad-993c21df9ea8.png)

**Additional context and screenshots**

The Solution Configurations and Solution Platforms are empty.

![image](https://user-images.githubusercontent.com/82852072/213630525-88f8db98-d022-4d65-aaf0-bdd813d5af2f.png)

![image](https://user-images.githubusercontent.com/82852072/213630615-56caf9d4-5bf4-4011-86fa-75b1537ae395.png)

![image](https://user-images.githubusercontent.com/82852072/213630675-282586bb-8030-411c-89ee-362c7d67d4fc.png)

**Comment by StellaHuang95** [comment] 2023-01-23 18:24
Were you referring to the navigation bar? If so, it should be a dupe of https://github.com/microsoft/PTVS/issues/6551

**Comment by ttSpace** [comment] 2023-01-29 06:09
@StellaHuang95 I'm not referring to the navigation bar.
I can repro this in today's build ```17.6.0 Preview 1.0 [33328.24.main]```, Python Package ```17.0.23005.2```.

![image](https://user-images.githubusercontent.com/82852072/215308307-9f701f45-89d3-4501-bf02-21bfad260b90.png)

BTW, In the Python Application template they are not empty.

![image](https://user-images.githubusercontent.com/82852072/215308408-1016e4d2-1838-4d32-a34f-263242038b04.png)

**Comment by int19h** [comment] 2023-01-29 23:26
Platform- and architecture-specific configs come from MSBuild project files, so in the absence of one they won't be present.

Given that Python itself doesn't really use either of those concepts, they're only useful in MSBuild context (e.g. to perform some config-specific actions when running the app, packaging etc), and even there it's very rarely used. So I think it would be reasonable to say that it's not a supported feature for non-MSBuild Python projects in VS.

**Comment by StellaHuang95** [comment] 2023-01-31 21:47
Close it according to the above.

**Closed by StellaHuang95** 2023-01-31 21:47 UTC
Labels: waiting for response
