### ISSUE TITLE
Immediate Window in Python projects prints too much data

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6361] opened 2021-01-21 21:11 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Immediate-Window-in-Python-projects-prin/1269198)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.7]
If I debug a Python project and hit a breakpoint, I often use the Immediate Window to display different values. For instance, if I type `'s'` and press the Enter key, it prints `'s'`. However, if I type `1, 2, 3` and press the Enter key, it prints `(1, 2, 3)` but also prints 37 lines of useless data and I must to scroll up to see that first line:
```
    count: <built-in method count of tuple object at 0x0000015347C1E688>
    index: <built-in method index of tuple object at 0x0000015347C1E688>
    __add__: <method-wrapper '__add__' of tuple object at 0x0000015347C1E688>
    __class__: <class 'tuple'>
    __contains__: <method-wrapper '__contains__' of tuple object at 0x0000015347C1E688>
    __delattr__: <method-wrapper '__delattr__' of tuple object at 0x0000015347C1E688>
    __dir__: <built-in method __dir__ of tuple object at 0x0000015347C1E688>
    __doc__: "Built-in immutable sequence.\n\nIf no argument is given, the constructor returns an empty tuple.\nIf iterable is specified the tuple is initialized from iterable's items.\n\nIf the argument is a tuple, the return value is the same object."
    __eq__: <method-wrapper '__eq__' of tuple object at 0x0000015347C1E688>
    __format__: <built-in method __format__ of tuple object at 0x0000015347C1E688>
    __ge__: <method-wrapper '__ge__' of tuple object at 0x0000015347C1E688>
    __getattribute__: <method-wrapper '__getattribute__' of tuple object at 0x0000015347C1E688>
    __getitem__: <method-wrapper '__getitem__' of tuple object at 0x0000015347C1E688>
    __getnewargs__: <built-in method __getnewargs__ of tuple object at 0x0000015347C1E688>
    __gt__: <method-wrapper '__gt__' of tuple object at 0x0000015347C1E688>
    __hash__: <method-wrapper '__hash__' of tuple object at 0x0000015347C1E688>
    __init__: <method-wrapper '__init__' of tuple object at 0x0000015347C1E688>
    __init_subclass__: <built-in method __init_subclass__ of type object at 0x00007FFBE48B6810>
    __iter__: <method-wrapper '__iter__' of tuple object at 0x0000015347C1E688>
    __le__: <method-wrapper '__le__' of tuple object at 0x0000015347C1E688>
    __len__: <method-wrapper '__len__' of tuple object at 0x0000015347C1E688>
    __lt__: <method-wrapper '__lt__' of tuple object at 0x0000015347C1E688>
    __mul__: <method-wrapper '__mul__' of tuple object at 0x0000015347C1E688>
    __ne__: <method-wrapper '__ne__' of tuple object at 0x0000015347C1E688>
    __new__: <built-in method __new__ of type object at 0x00007FFBE48B6810>
    __reduce__: <built-in method __reduce__ of tuple object at 0x0000015347C1E688>
    __reduce_ex__: <built-in method __reduce_ex__ of tuple object at 0x0000015347C1E688>
    __repr__: <method-wrapper '__repr__' of tuple object at 0x0000015347C1E688>
    __rmul__: <method-wrapper '__rmul__' of tuple object at 0x0000015347C1E688>
    __setattr__: <method-wrapper '__setattr__' of tuple object at 0x0000015347C1E688>
    __sizeof__: <built-in method __sizeof__ of tuple object at 0x0000015347C1E688>
    __str__: <method-wrapper '__str__' of tuple object at 0x0000015347C1E688>
    __subclasshook__: <built-in method __subclasshook__ of type object at 0x00007FFBE48B6810>
    0: 1
    1: 2
    2: 3
    len(): 3
```
While it's true it prints the items of a tuple at the end also, they are arranged vertically so long tuples scroll out of view and it will print only those items it knows how to convert to a string. If I import numpy with `import numpy as np` and type `1, np.ndarray` in the Immediate Window and press the Enter key, it prints the following as the last two lines.
```
    0: 1
    len(): 2
```
Although I highlighted the behavior with tuples, it happens with all non-primitive values. For instance, if I type `np.ndarray` in the Immediate Window and press the Enter key, it prints `<class 'numpy.ndarray'>`, which is useful and expected, followed by 105 lines of useless, unexpected data.
```
    T: <attribute 'T' of 'numpy.ndarray' objects>
    all: <method 'all' of 'numpy.ndarray' objects>
    any: <method 'any' of 'numpy.ndarray' objects>
    argmax: <method 'argmax' of 'numpy.ndarray' objects>
    argmin: <method 'argmin' of 'numpy.ndarray' objects>
    argpartition: <method 'argpartition' of 'numpy.ndarray' objects>
    argsort: <method 'argsort' of 'numpy.ndarray' objects>
    astype: <method 'astype' of 'numpy.ndarray' objects>
    base: <attribute 'base' of 'numpy.ndarray' objects>
    byteswap: <method 'byteswap' of 'numpy.ndarray' objects>
    choose: <method 'choose' of 'numpy.ndarray' objects>
    clip: <method 'clip' of 'numpy.ndarray' objects>
    compress: <method 'compress' of 'numpy.ndarray' objects>
    conj: <method 'conj' of 'numpy.ndarray' objects>
    conjugate: <method 'conjugate' of 'numpy.ndarray' objects>
    copy: <method 'copy' of 'numpy.ndarray' objects>
    ctypes: <attribute 'ctypes' of 'numpy.ndarray' objects>
    cumprod: <method 'cumprod' of 'numpy.ndarray' objects>
    cumsum: <method 'cumsum' of 'numpy.ndarray' objects>
    data: <attribute 'data' of 'numpy.ndarray' objects>
    diagonal: <method 'diagonal' of 'numpy.ndarray' objects>
    dot: <method 'dot' of 'numpy.ndarray' objects>
    dtype: <attribute 'dtype' of 'numpy.ndarray' objects>
    dump: <method 'dump' of 'numpy.ndarray' objects>
    dumps: <method 'dumps' of 'numpy.ndarray' objects>
    fill: <method 'fill' of 'numpy.ndarray' objects>
    flags: <attribute 'flags' of 'numpy.ndarray' objects>
    flat: <attribute 'flat' of 'numpy.ndarray' objects>
    flatten: <method 'flatten' of 'numpy.ndarray' objects>
    getfield: <method 'getfield' of 'numpy.ndarray' objects>
    imag: <attribute 'imag' of 'numpy.ndarray' objects>
    item: <method 'item' of 'numpy.ndarray' objects>
    itemset: <method 'itemset' of 'numpy.ndarray' objects>
    itemsize: <attribute 'itemsize' of 'numpy.ndarray' objects>
    max: <method 'max' of 'numpy.ndarray' objects>
    mean: <method 'mean' of 'numpy.ndarray' objects>
    min: <method 'min' of 'numpy.ndarray' objects>
    nbytes: <attribute 'nbytes' of 'numpy.ndarray' objects>
    ndim: <attribute 'ndim' of 'numpy.ndarray' objects>
    newbyteorder: <method 'newbyteorder' of 'numpy.ndarray' objects>
    nonzero: <method 'nonzero' of 'numpy.ndarray' objects>
    partition: <method 'partition' of 'numpy.ndarray' objects>
    prod: <method 'prod' of 'numpy.ndarray' objects>
    ptp: <method 'ptp' of 'numpy.ndarray' objects>
    put: <method 'put' of 'numpy.ndarray' objects>
    ravel: <method 'ravel' of 'numpy.ndarray' objects>
    real: <attribute 'real' of 'numpy.ndarray' objects>
    repeat: <method 'repeat' of 'numpy.ndarray' objects>
    reshape: <method 'reshape' of 'numpy.ndarray' objects>
    resize: <method 'resize' of 'numpy.ndarray' objects>
    round: <method 'round' of 'numpy.ndarray' objects>
    searchsorted: <method 'searchsorted' of 'numpy.ndarray' objects>
    setfield: <method 'setfield' of 'numpy.ndarray' objects>
    setflags: <method 'setflags' of 'numpy.ndarray' objects>
    shape: <attribute 'shape' of 'numpy.ndarray' objects>
    size: <attribute 'size' of 'numpy.ndarray' objects>
    sort: <method 'sort' of 'numpy.ndarray' objects>
    squeeze: <method 'squeeze' of 'numpy.ndarray' objects>
    std: <method 'std' of 'numpy.ndarray' objects>
    strides: <attribute 'strides' of 'numpy.ndarray' objects>
    sum: <method 'sum' of 'numpy.ndarray' objects>
    swapaxes: <method 'swapaxes' of 'numpy.ndarray' objects>
    take: <method 'take' of 'numpy.ndarray' objects>
    tobytes: <method 'tobytes' of 'numpy.ndarray' objects>
    tofile: <method 'tofile' of 'numpy.ndarray' objects>
    tolist: <method 'tolist' of 'numpy.ndarray' objects>
    tostring: <method 'tostring' of 'numpy.ndarray' objects>
    trace: <method 'trace' of 'numpy.ndarray' objects>
    transpose: <method 'transpose' of 'numpy.ndarray' objects>
    var: <method 'var' of 'numpy.ndarray' objects>
    view: <method 'view' of 'numpy.ndarray' objects>
    __abs__: <slot wrapper '__abs__' of 'numpy.ndarray' objects>
    __add__: <slot wrapper '__add__' of 'numpy.ndarray' objects>
    __and__: <slot wrapper '__and__' of 'numpy.ndarray' objects>
    __array__: <method '__array__' of 'numpy.ndarray' objects>
    __array_finalize__: <attribute '__array_finalize__' of 'numpy.ndarray' objects>
    __array_function__: <method '__array_function__' of 'numpy.ndarray' objects>
    __array_interface__: <attribute '__array_interface__' of 'numpy.ndarray' objects>
    __array_prepare__: <method '__array_prepare__' of 'numpy.ndarray' objects>
    __array_priority__: <attribute '__array_priority__' of 'numpy.ndarray' objects>
    __array_struct__: <attribute '__array_struct__' of 'numpy.ndarray' objects>
    __array_ufunc__: <method '__array_ufunc__' of 'numpy.ndarray' objects>
    __array_wrap__: <method '__array_wrap__' of 'numpy.ndarray' objects>
    __bool__: <slot wrapper '__bool__' of 'numpy.ndarray' objects>
    __class__: <class 'type'>
    __complex__: <method '__complex__' of 'numpy.ndarray' objects>
    __contains__: <slot wrapper '__contains__' of 'numpy.ndarray' objects>
    __copy__: <method '__copy__' of 'numpy.ndarray' objects>
    __deepcopy__: <method '__deepcopy__' of 'numpy.ndarray' objects>
    __delattr__: <slot wrapper '__delattr__' of 'object' objects>
    __delitem__: <slot wrapper '__delitem__' of 'numpy.ndarray' objects>
    __dir__: <method '__dir__' of 'object' objects>
    __divmod__: <slot wrapper '__divmod__' of 'numpy.ndarray' objects>
    __doc__: 'ndarray(shape, dtype=float, buffer=None, offset=0,\n            strides=None, order=None)\n\n    An array object represents a multidimensional, homogeneous array\n    of fixed-size items.  An associated data-type object describes the\n    format of each element in the array (its byte-order, how many bytes it\n    occupies in memory, whether it is an integer, a floating point number,\n    or something else, etc.)\n\n    Arrays should be constructed using `array`, `zeros` or `empty` (refer\n    to the See Also section below).  The parameters given here refer to\n    a low-level method (`ndarray(...)`) for instantiating an array.\n\n    For more information, refer to the `numpy` module and examine the\n    methods and attributes of an array.\n\n    Parameters\n    ----------\n    (for the __new__ method; see Notes below)\n\n    shape : tuple of ints\n        Shape of created array.\n    dtype : data-type, optional\n        Any object that can be interpreted as a numpy data type.\n    buffer : object
 exposing buffer interface, optional\n        Used to fill the array with data.\n    offset : int, optional\n        Offset of array data in buffer.\n    strides : tuple of ints, optional\n        Strides of data in memory.\n    order : {\'C\', \'F\'}, optional\n        Row-major (C-style) or column-major (Fortran-style) order.\n\n    Attributes\n    ----------\n    T : ndarray\n        Transpose of the array.\n    data : buffer\n        The array\'s elements, in memory.\n    dtype : dtype object\n        Describes the format of the elements in the array.\n    flags : dict\n        Dictionary containing information related to memory use, e.g.,\n        \'C_CONTIGUOUS\', \'OWNDATA\', \'WRITEABLE\', etc.\n    flat : numpy.flatiter object\n        Flattened version of the array as an iterator.  The iterator\n        allows assignments, e.g., ``x.flat = 3`` (See `ndarray.flat` for\n        assignment examples; TODO).\n    imag : ndarray\n        Imaginary part of the array.\n    real : ndarray\n        Real part o
f the array.\n    size : int\n        Number of elements in the array.\n    itemsize : int\n        The memory use of each array element in bytes.\n    nbytes : int\n        The total number of bytes required to store the array data,\n        i.e., ``itemsize * size``.\n    ndim : int\n        The array\'s number of dimensions.\n    shape : tuple of ints\n        Shape of the array.\n    strides : tuple of ints\n        The step-size required to move from one element to the next in\n        memory. For example, a contiguous ``(3, 4)`` array of type\n        ``int16`` in C-order has strides ``(8, 2)``.  This implies that\n        to move from element to element in memory requires jumps of 2 bytes.\n        To move from row-to-row, one needs to jump 8 bytes at a time\n        (``2 * 4``).\n    ctypes : ctypes object\n        Class containing properties of the array needed for interaction\n        with ctypes.\n    base : ndarray\n        If the array is a view into another array, that array is its `base`\n      
  (unless that array is also a view).  The `base` array is where the\n        array data is actually stored.\n\n    See Also\n    --------\n    array : Construct an array.\n    zeros : Create an array, each element of which is zero.\n    empty : Create an array, but leave its allocated memory unchanged (i.e.,\n            it contains "garbage").\n    dtype : Create a data-type.\n\n    Notes\n    -----\n    There are two modes of creating an array using ``__new__``:\n\n    1. If `buffer` is None, then only `shape`, `dtype`, and `order`\n       are used.\n    2. If `buffer` is an object exposing the buffer interface, then\n       all keywords are interpreted.\n\n    No ``__init__`` method is needed because the array is fully initialized\n    after the ``__new__`` method.\n\n    Examples\n    --------\n    These examples illustrate the low-level `ndarray` constructor.  Refer\n    to the `See Also` section above for easier ways of constructing an\n    ndarray.\n\n    First mode, `buffer` is None:\n\n    >>> np.nda
rray(shape=(2,2), dtype=float, order=\'F\')\n    array([[ -1.13698227e+002,   4.25087011e-303],\n           [  2.88528414e-306,   3.27025015e-309]])         #random\n\n    Second mode:\n\n    >>> np.ndarray((2,), buffer=np.array([1,2,3]),\n    ...            offset=np.int_().itemsize,\n    ...            dtype=int) # offset = 1*itemsize, i.e. skip first element\n    array([2, 3])'
    __eq__: <slot wrapper '__eq__' of 'numpy.ndarray' objects>
    __float__: <slot wrapper '__float__' of 'numpy.ndarray' objects>
    __floordiv__: <slot wrapper '__floordiv__' of 'numpy.ndarray' objects>
    __format__: <method '__format__' of 'numpy.ndarray' objects>
    __ge__: <slot wrapper '__ge__' of 'numpy.ndarray' objects>
    __getattribute__: <slot wrapper '__getattribute__' of 'object' objects>
    < More... (The first 100 of 162 items were displayed.) >
```
While this new behavior might be useful to some in some situations, I has not yet proven useful to me in any situation. I'd like to at least have the option for the Immediate Window to display only the value of what I type, excluding all of the additional data about that value.

---
#### Feedback Bot on 11/25/2020, 09:00 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Yingying Zhang [MSFT] on 12/16/2020, 09:10 PM: 

<p>Sorry, we don’t know what you want to do through the window.<br>
The Immediate window is used to debug and evaluate expressions, execute statements, and print variable values.<br>
If you want to print variable values, you can use “&gt;Debug.Print varA” or “? varA”<br>
If you want execute some command, please enter the greater than sign (&gt;).<br>
Here is the doc about how to use Immediate window:<br>
<a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/reference/immediate-window?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/reference/immediate-window?view=vs-2019</a></p>

#### Feedback Bot on 12/29/2020, 08:56 PM: 

We will close this report in 14 days because we don’t have enough information to investigate further. To keep the problem open, please provide the requested details.

#### Mark Kotwicz Herniczek on 1/5/2021, 02:23 PM: 

<p>I'm having the same issue. It doesn't occur when checking the value of simple variables but it is very inconvenient when dealing with structures such as lists or numpy arrays. For example, if I have an array and I want to display it using "arrA" or "? arrA", much more than just the array values are printed.</p><p>The situation is even worse when checking attributes of arrays ("arrA.shape" for example), where every built-in method is first printed before the desired information is shown. The immediate window worked as desired in the past as the author mentioned.</p><p><br></p><p>An example of interaction with the immediate window is shown below:</p><p>input:</p><pre>x = [1,2]<br>? x</pre><p>output:</p><pre>[1, 2]
    append: &lt;built-in method append of list object at 0x0000028034B8CE48&gt;
    clear: &lt;built-in method clear of list object at 0x0000028034B8CE48&gt;
    copy: &lt;built-in method copy of list object at 0x0000028034B8CE48&gt;
    count: &lt;built-in method count of list object at 0x0000028034B8CE48&gt;
    extend: &lt;built-in method extend of list object at 0x0000028034B8CE48&gt;
    index: &lt;built-in method index of list object at 0x0000028034B8CE48&gt;
    insert: &lt;built-in method insert of list object at 0x0000028034B8CE48&gt;
    pop: &lt;built-in method pop of list object at 0x0000028034B8CE48&gt;
    remove: &lt;built-in method remove of list object at 0x0000028034B8CE48&gt;
    reverse: &lt;built-in method reverse of list object at 0x0000028034B8CE48&gt;
    sort: &lt;built-in method sort of list object at 0x0000028034B8CE48&gt;
    __add__: &lt;method-wrapper '__add__' of list object at 0x0000028034B8CE48&gt;
    __class__: &lt;class 'list'&gt;
    __contains__: &lt;method-wrapper '__contains__' of list object at 0x0000028034B8CE48&gt;
    __delattr__: &lt;method-wrapper '__delattr__' of list object at 0x0000028034B8CE48&gt;
    __delitem__: &lt;method-wrapper '__delitem__' of list object at 0x0000028034B8CE48&gt;
    __dir__: &lt;built-in method __dir__ of list object at 0x0000028034B8CE48&gt;
    __doc__: 'Built-in mutable sequence.\n\nIf no argument is given, the constructor creates a new empty list.\nThe argument must be an iterable if specified.'
    __eq__: &lt;method-wrapper '__eq__' of list object at 0x0000028034B8CE48&gt;
    __format__: &lt;built-in method __format__ of list object at 0x0000028034B8CE48&gt;
    __ge__: &lt;method-wrapper '__ge__' of list object at 0x0000028034B8CE48&gt;
    __getattribute__: &lt;method-wrapper '__getattribute__' of list object at 0x0000028034B8CE48&gt;
    __getitem__: &lt;built-in method __getitem__ of list object at 0x0000028034B8CE48&gt;
    __gt__: &lt;method-wrapper '__gt__' of list object at 0x0000028034B8CE48&gt;
    __hash__: None
    __iadd__: &lt;method-wrapper '__iadd__' of list object at 0x0000028034B8CE48&gt;
    __imul__: &lt;method-wrapper '__imul__' of list object at 0x0000028034B8CE48&gt;
    __init__: &lt;method-wrapper '__init__' of list object at 0x0000028034B8CE48&gt;
    __init_subclass__: &lt;built-in method __init_subclass__ of type object at 0x00007FFF2B954D30&gt;
    __iter__: &lt;method-wrapper '__iter__' of list object at 0x0000028034B8CE48&gt;
    __le__: &lt;method-wrapper '__le__' of list object at 0x0000028034B8CE48&gt;
    __len__: &lt;method-wrapper '__len__' of list object at 0x0000028034B8CE48&gt;
    __lt__: &lt;method-wrapper '__lt__' of list object at 0x0000028034B8CE48&gt;
    __mul__: &lt;method-wrapper '__mul__' of list object at 0x0000028034B8CE48&gt;
    __ne__: &lt;method-wrapper '__ne__' of list object at 0x0000028034B8CE48&gt;
    __new__: &lt;built-in method __new__ of type object at 0x00007FFF2B954D30&gt;
    __reduce__: &lt;built-in method __reduce__ of list object at 0x0000028034B8CE48&gt;
    __reduce_ex__: &lt;built-in method __reduce_ex__ of list object at 0x0000028034B8CE48&gt;
    __repr__: &lt;method-wrapper '__repr__' of list object at 0x0000028034B8CE48&gt;
    __reversed__: &lt;built-in method __reversed__ of list object at 0x0000028034B8CE48&gt;
    __rmul__: &lt;method-wrapper '__rmul__' of list object at 0x0000028034B8CE48&gt;
    __setattr__: &lt;method-wrapper '__setattr__' of list object at 0x0000028034B8CE48&gt;
    __setitem__: &lt;method-wrapper '__setitem__' of list object at 0x0000028034B8CE48&gt;
    __sizeof__: &lt;built-in method __sizeof__ of list object at 0x0000028034B8CE48&gt;
    __str__: &lt;method-wrapper '__str__' of list object at 0x0000028034B8CE48&gt;
    __subclasshook__: &lt;built-in method __subclasshook__ of type object at 0x00007FFF2B954D30&gt;
    0: 1
    1: 2
    len(): 2
<br></pre>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2021-01-21 21:13
Duplicate of #6342

**Closed by AdamYoblick** 2021-01-21 21:13 UTC
