### ISSUE TITLE
Django completions in html file does not work.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#6629] opened 2021-08-02 06:08 UTC
**Environment**
![image](https://user-images.githubusercontent.com/59192491/127811105-94379af3-ccce-452e-99db-d23f66f7b9f3.png)

**Actual result**
![html](https://user-images.githubusercontent.com/59192491/127812006-66117314-cd74-4144-8265-5f2a143e6da0.gif)

**Expected result**
1. Open the app/about.html in Django Web Project
2. Typing a vertical bar '|' character after a variable brings up completions for filters including 'upper', and each one has a tooltip
![image](https://user-images.githubusercontent.com/59192491/127811322-81a361b6-6379-49cc-b9e1-dc69d0349bc1.png)
3. Typing opening brace and percent '{%'  brings up completions for tags including 'if' and 'extends', they currently don't have tooltips
![image](https://user-images.githubusercontent.com/59192491/127811462-537c7e35-6b21-4028-b635-971af5ddbe7b.png)
4. Typing double opening brace '{{' brings up completions for variables passed in to the template (see views.py).
![image](https://user-images.githubusercontent.com/59192491/127811528-dd0d591e-bf46-4568-bb2f-514f8a2e2555.png)

**Comment by rchiodo** [comment] 2021-08-02 15:53
Django (html) completions is owned by another team. This should be transferred to that team (internal DevDiv bug)

**Comment by greazer** [comment] 2021-08-04 23:06
It's possible that we accidentally removed this support after hugues left. So if there are complaints we can try bringing it back. See https://github.com/microsoft/PTVS/commits/main/Python/Product/Django.

**Comment by rchiodo** [comment] 2021-08-04 23:35
Probably easy to add stuff back. Should do this sooner rather than later so we can see if there's more work to account for changes from the HTML LS.

**Comment by rchiodo** [comment] 2021-08-11 21:22
This might not work. Django intellisense is hooking into the old engine. There's no good way to hook into pylance for the same thing

**Comment by rchiodo** [comment] 2021-08-11 21:27
Readding this isn't going to be trivial.

**Comment by rchiodo** [comment] 2021-08-11 21:29
Here's a branch indicating all the stuff that won't work:
https://github.com/rchiodo/PTVS/tree/rchiodo/django_intellisense_readd

**Comment by judej** [comment] 2023-01-17 23:29
Closing as a dupe of https://github.com/microsoft/pylance-release/issues/3701

**Closed by judej** 2023-01-17 23:29 UTC
Labels: enhancement
