### ISSUE TITLE
error: Python Environments -> Open Interactive Window 

### ISSUE THREAD

**Issue by totpero** [Microsoft/PTVS#2549] opened 2017-05-13 14:38 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
An error occurred opening this interactive window.

Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 3.0.17114.1

System.TypeLoadException: Could not load type 'Microsoft.VisualStudio.InteractiveWindow.Shell.IVsInteractiveWindowFactory2' from assembly 'Microsoft.VisualStudio.VsInteractiveWindow, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.CreateInteractiveWindowInternal(IInteractiveEvaluator evaluator, IContentType contentType, Boolean alwaysCreate, Int32 id, String title, Guid languageServiceGuid, String replId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.Create(String replId, Int32 curId)
   at Microsoft.PythonTools.Repl.InteractiveWindowProvider.OpenOrCreate(String replId)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.OpenInteractiveWindow_Executed(Object sender, ExecutedRoutedEventArgs e)
```

**Comment by mwindowshz** [comment] 2017-05-15 19:53
Hi I also have this problem. It started after updating from visual 2017 RC to official visual 2017
Cannot open Python Interactive window
or python debug interactive
![image](https://cloud.githubusercontent.com/assets/17617515/26076368/38c4836e-39c1-11e7-81ef-13eb3eb2746f.png)

Is there a workaround?

**Comment by huguesv** [comment] 2017-05-15 20:15
Closing as duplicate of https://github.com/Microsoft/PTVS/issues/2534

**Closed by huguesv** 2017-05-15 20:15 UTC
