### ISSUE TITLE
exception in child process

### ISSUE THREAD

**Issue by 22sam** [Microsoft/PTVS#849] opened 2015-09-27 17:08 UTC
I am spawning working processes like this:

import multiprocessing as mp
proc = mp.Process(target=foo)
proc.start()

This process then hits a failed assertion and should throw an exception. However, I see nothing at all in Visual Studio -- no exception, no stack trace, nothing. I had to debug using print statements to locate the failed assert(). Visual Studio just sits there as though my application is still running properly. Am I missing a setting or does PTVS not support multiple python processes?

Nearly all of my application is run by child processes, the initial process just runs the GUI. Thanks.

**Comment by int19h** [comment] 2015-09-27 21:06
It does not currently support automatically attaching to spawned child processes. You can still debug them, if you can manually attach via Debug -> Attach to Process. The tricky part is doing it before it crashes...

**Comment by int19h** [comment] 2015-09-27 21:06
Dupe of #125

**Closed by int19h** 2015-09-27 21:06 UTC
