### ISSUE TITLE
Python editor not in tools menu -> options -> text editor -> file extensions

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6997] opened 2022-05-11 16:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-editor-not-in-tools-menu---optio/10028183)._

---
Some of my python files use the .FCMacro extension (for FreeCAD).  In VS19 I can use tools menu -> options -> text editor -> file extension dialog to add the .FCMacro extension and have it use the Python editor in order to get syntax color highlighting.  But the python editor isn't in the list in VS22.

---
#### Feedback Bot on 5/1/2022, 05:46 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-05-11 18:23
Duplicate of #6926

**Closed by AdamYoblick** 2022-05-11 18:23 UTC
Labels: needs triage
