### ISSUE TITLE
NumPy implementation not accessible 

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7719] opened 2023-09-06 17:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NumPy-implementation-not-accessible-/10451532)._

---
Hi,

I am having an issue implementing NumPy on my visual studio community 2022 platform. I had downloaded it and created a path for it and named it PYTHON_HOME. I had restarted my pc and still it is not working. But still it is saying that there no module as NumPy. 

---
#### Feedback Bot on 8/28/2023, 06:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-09-06 17:33
dupe of https://github.com/microsoft/PTVS/issues/7718

**Closed by StellaHuang95** 2023-09-06 17:33 UTC
Labels: duplicate
