### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by sureshmali** [Microsoft/PTVS#3896] opened 2018-03-16 19:05 UTC
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[V] Show details  [Close]

[Expanded Information]
```
Build: 3.0.17320.1

Microsoft.PythonTools.MissingInterpreterException: The environment "Global|ContinuumAnalytics|Anaconda27-64" appears to be incorrectly configured or missing. You may need to install it or re-create a virtual environment.
   at Microsoft.PythonTools.Project.PythonProjectNode.GetInterpreterFactoryOrThrow()
   at Microsoft.PythonTools.Project.PythonProjectNode.GetLaunchConfigurationOrThrow()
   at Microsoft.PythonTools.Project.DefaultLauncherProvider.CreateLauncher(IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.<>c__DisplayClass8_0.<GetLauncher>b__2()
   at Microsoft.VisualStudioTools.UIThread.Invoke[T](Func`1 func)
   at Microsoft.PythonTools.PythonToolsPackage.GetLauncher(IServiceProvider serviceProvider, IPythonProject project)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

**Comment by huguesv** [comment] 2018-03-16 20:18
Thanks! This has been fixed in VS 2017 version 15.6, which was released last week.

Duplicate of https://github.com/Microsoft/PTVS/issues/3176

**Closed by huguesv** 2018-03-16 20:18 UTC
Labels: resolution:duplicate
