### ISSUE TITLE
python editor code-folding for def and class code blocks not working properly in release 17.2.3

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7032] opened 2022-06-08 16:07 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/python-editor-code-folding-for-def-and-c/10060001)._

---
[severity:I'm unable to use this version] [regression] [worked-in:VS 2019]
The python editor code-folding for def and class code blocks does not work properly in release 17.2.3 for me:

[-] def funcname():  
                  x=3
                  y=4

when folded, collapses to

[+] def [...]

where [ ] = box around contents

In other words, the function name and arguments disappear completely, leaving the code-folding essentially useless for def blocks.  For example, take a look at the included screenshot to see what I mean.

Same result occurs with class classname blocks:  the classname itself is replaced by [...] leaving you with [+] class [...].  Again useless.

I've tried this with fresh VS 2022 17.2.3 installs on two Win10 computers, and same result on both of them.  After install, I created a new python project and in the myfile.py file, I added the above def block only.  With that simple project, code-folding was problematic as described above.  So no fancy settings or odd project types required to reproduce this problem.

A friend of mine has VS 2022 17.0.2 on his Win10 laptop (similar type to mine), and python code-folding for def funcname(): works perfectly fine and as expected on his system: it leaves the top-level def funcname() statement followed by [...]

I should also point out that code-folding on for and if blocks works as it should, leaving the top line intact followed by [...].  Only def and class blocks are showing this faulty behavior of erasing the entire top line and replacing it with [...] (at least in my limited testing - there may be other block types that suffer this problem as well).

Your help in resolving this problem would be much appreciated.

---
#### Feedback Bot on 6/1/2022, 11:33 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-06-08 17:58
duplicate of #7016

**Comment by niwax** [comment] 2022-06-10 08:30
Since this is now the replacement for #7016, I would like to add that the actual command "Collapse to definitions" is nonfunctional in the edit menu as well

**Comment by Dabendorf** [comment] 2022-11-04 14:10
Is this still a thing? It does not work on my computer either, nothing to collapse for python files (But for other programming languages)

**Comment by StellaHuang95** [comment] 2022-11-04 23:43
Hi @Dabendorf, yes it's in our backlog to fix. Filed another issue in pylance to track the issue. https://github.com/microsoft/pylance-release/issues/3580

**Closed** 2022-11-15 02:29 UTC
Labels: bug, P2

**Comment by Dabendorf** [comment] 2022-11-19 13:23
In which version was this solved? Already in 2022.18.2? (because it isn't working on my computer anyway)

**Comment by Dabendorf** [comment] 2023-05-25 19:04
Looks like it is fixed for me now. Did you actually find another bug or was waiting for the bug to disappear on my computer enough?

**Comment by VladisS-Vostok2000** [comment] 2023-05-25 19:53
Found another, thanks.

**Comment by PGTBoos** [comment] 2023-12-12 07:23
can't collapse C# code functions as well, missing the [+] 17.8.3

**Comment by SkierJa** [comment] 2024-06-17 10:21
Issue still occurs VS 2022 17.9.6, cannot collapse to definitions by the shortcut neither context menu

**Comment by Viamo** [comment] 2024-06-20 13:25
**It still doesn't work!**

![2024-06-20_161708](https://github.com/microsoft/PTVS/assets/10107442/4136311b-2cf8-45c0-922b-7ab295fe2c66)

**Comment by lholden2** [comment] 2025-03-11 21:24
I believe this issue should be reopened because "Collapse to Definitions" doesn't work from both the menu and the key combination in Visual Studio 2022 17.13.3.

But if you choose "Stop Outlining" from the Outlining, choose "Start Automatic Outlining", and then choose "Toggle All Outlining", you'll get the same effect as "Collapse to Definitions", but of course with more work.

**Comment by Viamo** [comment] 2025-03-11 21:33
> But if you choose "Stop Outlining" from the Outlining, choose "Start Automatic Outlining", and then choose "Toggle All Outlining", you'll get the same effect as "Collapse to Definitions", but of course with more work.

Thanks, it works, but collapses not only `def` but also `if`, `for`, `while`...

**But the issue should still be reopened so that Ctrl+M, Ctrl+O works.**

**Comment by KoenBooneWandelsport** [comment] 2025-06-02 08:07
yep, not fixed yet (Version 17.14.0)

**Comment by debonte** [comment] 2025-06-02 19:08
> yep, not fixed yet (Version 17.14.0)

The Collapse to Definitions issue (Ctrl+M Ctrl+O) is tracked by https://github.com/microsoft/PTVS/issues/7897.
