### ISSUE TITLE
multiprocessing debugging

### ISSUE THREAD

**Issue by sma202** [Microsoft/PTVS#983] opened 2015-11-09 21:33 UTC
I'm using the multiprocessing module.  Is there any to debug multiple processes, if I do "attach to process", it doesn't link to any code.  Stopping at a breakpoint doesn't show multiple processes in the "processes" window but I can two instances of python.exe in taskmgr.

If I attach to that 2nd process ctrl-alt-p, it doesn't link back to the code.

**Comment by zwn** [comment] 2017-07-07 11:12
Is this a duplicate of #125?

**Closed** 2017-09-21 00:28 UTC
Labels: area:Debugger, resolution:duplicate
