### ISSUE TITLE
Add '=' at end of parameter name suggestions

### ISSUE THREAD

**Issue by zooba** [Microsoft/PTVS#491] opened 2015-06-19 22:37 UTC
When parameter names are suggested in code completions, it isn't obvious that they are parameter names and not variables.

We should find them a better icon, and include the equals sign that must follow them.

**Comment by huguesv** [comment] 2017-12-09 00:40
This was done in https://github.com/Microsoft/PTVS/pull/3425 (duplicate of https://github.com/Microsoft/PTVS/issues/679)

**Closed by huguesv** 2017-12-09 00:40 UTC
Labels: area:IntelliSense, enhancement
