### ISSUE TITLE
reportMissingImports error.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7455] opened 2023-03-15 18:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/reportMissingImports-error/10304024)._

---
I am at my wits end, I have tried everything I can find but no luck with anything at all and I have had to deal with this for about 6 months straight. I also see it's been an issue for like 7 years for others online and there is absolutely no recognition by Microsoft that it can't be fixed or is being fixed.
I use python in Visual Studio 2022 and for as long as I can remember my imports have been "missing" or "couldn't be resolved". I want to upgrade and start paying for visual studio but I just can't justify it.
Error isn't there when I initially open a solution, but the second something changes or I run/debug my code the issue returns.
Any help would be insanely appreciated, Thanks! Chase.

---
#### Feedback Bot on 3/8/2023, 05:12 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-03-15 18:50
Duplicate of https://github.com/microsoft/PTVS/issues/7068. Fix is here: https://github.com/microsoft/PTVS/pull/7401

The issue should be fixed in the next version.

**Closed by StellaHuang95** 2023-03-15 18:50 UTC
Labels: needs triage
