### ISSUE TITLE
System.NullReferenceException when attempting to paste text in highlighted block

### ISSUE THREAD

**Issue by GitBlanton** [microsoft/PTVS#5881] opened 2019-11-13 21:35 UTC
**Describe the bug**
When attempting to paste text from the clipboard to highlighted block of text (ie, hold ALT and then left-click the mouse to highlight a block of text that spans several rows and columns), an "unexpected error" occurred.

**Steps to Reproduce**
1.  Select a snippet of text (1 row, 10 characters, for example) and copy to the clipboard with Ctrl-C.
2.  Hold ALT, then left-click the mouse to highlight a section of text that will be replaced by the clipboard contents.
3.  Paste text with Ctrl-V.  At this point the error occurred.

**Expected behavior**
Expected behavior is that each row of the highlighted text would be replaced by the contents of the clipboard.

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.9.18254.1

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Intellisense.CompletionSessionExtensions.SetTriggerCharacter(IIntellisenseSession session, Char triggerChar)
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TriggerCompletionSession>d__43.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.ReThrowTaskException(Object state)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions.DoNotWait(Task task)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Sample 
![VisualStudio crash, editor view (2019-11-13)](https://user-images.githubusercontent.com/57730318/68805139-3294d400-0631-11ea-91a1-4e8de7e90c18.png)
Code**
```
N/A, error occurred during editing of code.  See attached image for more info.
```

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```
[Diagnostic Info 2019-11-13T161846.txt](https://github.com/microsoft/PTVS/files/3843568/Diagnostic.Info.2019-11-13T161846.txt)

**Comment by bschnurr** [comment] 2019-11-13 22:54
this issue seems to be a duplicate of https://github.com/microsoft/PTVS/issues/4762 

Please update to VS 2019

**Closed by bschnurr** 2019-11-13 22:54 UTC
Labels: resolution:duplicate
