### ISSUE TITLE
PackageId:CPython3.Exe.x64;PackageAction:DownloadPackage;ReturnCode:0x80072ee2;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7241] opened 2022-11-30 16:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython3Exex64;PackageAction/10202540)._

---
[severity:It bothers me. A fix would be nice]
下载python时特别慢每次只有几kb甚至是几b，而且下载完还出现无法下载CPython3.Exe.x64的情况，但是我测试了我的网速，发现不是网的问题，我甚至还修改了hosts，但是还是没用。等到我更新完成了，我登录vs的时候，发现之前的设置都恢复了，还需要重新配置

---
#### Feedback Bot on 11/16/2022, 00:06 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-11-30 17:57
duplicate of https://github.com/microsoft/PTVS/issues/7228

**Closed by StellaHuang95** 2022-11-30 17:57 UTC
Labels: duplicate
