### ISSUE TITLE
lxml code completion

### ISSUE THREAD

**Issue by ibocon** [Microsoft/PTVS#2942] opened 2017-08-25 19:06 UTC
I am trying to use lxml package to parse XML file.
Simple code work well in python interpreter. 
But,  PTVS code completion does not show anything about package.

```
from lxml import etree
etree.parse(path)

```

Is this a usual things? or may I miss something to import package?

Versions:  
Windows 10 & VS2017 & Anaconda 4.4.0 & Python 3.6 & lxml 3.8.0

**Comment by huguesv** [comment] 2017-08-30 23:41
Thanks. I can't confirm it at the moment but I can test again later when my development build isn't so broken.

You can check the Python Environments window to see if the database is up to date. If there's a checkmark next to lxml, and it doesn't work, then there's probably nothing you can do.

Are you on VS 2017 15.3?

![image](https://user-images.githubusercontent.com/1696845/29899651-96f2c82c-8da1-11e7-95f8-372521088ddd.png)


Note: that etree comes from a .pyd, here's the file list for lxml:
```
__init__.py
__pycache__
_elementpath.py
builder.py
cssselect.py
doctestcompare.py
ElementInclude.py
etree.cp36-win32.pyd
html
includes
isoschematron
lxml.etree.h
lxml.etree_api.h
objectify.cp36-win32.pyd
pyclasslookup.py
sax.py
usedoctest.py
```

**Comment by ibocon** [comment] 2017-08-31 14:27
My Current Visual Studio Version is 

**Microsoft Visual Studio Community 2017 
Version 15.3.2
Python   3.0.17208.1**

_lxml_ package is recognized well to database. I already try _Refresh DB_

![lxml](https://user-images.githubusercontent.com/9730869/29927828-6e15639a-8ea2-11e7-9d86-e80d98a80667.PNG)

Here is _Continuum\Anaconda3\Lib\site-packages\lxml_ folder

![filestruct](https://user-images.githubusercontent.com/9730869/29928077-01089672-8ea3-11e7-8615-31aaa5f35e8b.PNG)

I think I figure it out. The problem was environment settings.  

** Python 3.6 & lxml 3.8.0 ** does not show and code completion for C based python package.

After I change to ** Python 3.5.3 & lxml 3.7.3 **, code completion now works well.

Thanks @huguesv for replying my issue!

**Comment by huguesv** [comment] 2017-09-18 20:24
I wasn't able to get completions on `lxml.etree`, on either 3.5 or 3.6 venvs. I also tried an lxml 3.7.3.

**Comment by huguesv** [comment] 2017-09-18 20:27
Closing as duplicate of https://github.com/Microsoft/PTVS/issues/3046

**Closed by huguesv** 2017-09-18 20:27 UTC
Labels: resolution:duplicate
