### ISSUE TITLE
Missing information of what more is needed to get Python intellisense to work

### ISSUE THREAD

**Issue by WilliamAntonRohm** [microsoft/PTVS#7332] opened 2023-01-17 22:35 UTC
Moved from https://github.com/MicrosoftDocs/visualstudio-docs/issues/8858.

The autocomplete (and the intellisense) does not work just out of the box for me:
![image](https://user-images.githubusercontent.com/25315785/212822350-67d8c10f-25ca-450c-9a33-3505727aba0b.png)

It is strange, some suggestion works but other doesn't, I have installed tqdm in my global python3.9 which it found (but in the same time not found..) it didn't find the `pyaisdb` (one of my own packages) from the global python3.9 installation.
![image](https://user-images.githubusercontent.com/25315785/212823393-4f6b9ceb-e73d-4b2a-b747-444820c73fbc.png)

Could be a missing option or a missing package?
my .vsconfig:
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Microsoft.Component.PythonTools",
    "Component.CPython39.x64",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Graphics.Tools",
    "Microsoft.VisualStudio.Component.VC.DiagnosticTools",
    "Microsoft.VisualStudio.Component.Windows11SDK.22000",
    "Microsoft.ComponentGroup.PythonTools.NativeDevelopment",
    "Microsoft.VisualStudio.Workload.Python",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.Windows10SDK.19041",
    "Microsoft.VisualStudio.Component.Windows10SDK.18362",
    "Microsoft.VisualStudio.Workload.NativeDesktop",
    "Microsoft.Net.Component.4.6.TargetingPack",
    "Microsoft.VisualStudio.Component.VSSDK"
  ]
}

[Skriv din feedback här]

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för learn.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 9057b789-9e00-502a-42de-bf4c097779b4
* Version Independent ID: c1419fe1-1dd0-902d-f6c9-e73f55ecf92c
* Content: [Edit Python code - Visual Studio (Windows)](https://learn.microsoft.com/sv-se/visualstudio/python/editing-python-code-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/editing-python-code-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/editing-python-code-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by axelande** [comment] 2023-01-18 08:39
It works in vscode but not in visual studio (version 17.4.4)

**Comment by StellaHuang95** [comment] 2023-02-24 00:23
That should be a duplicate of #7154

**Closed by StellaHuang95** 2023-02-24 00:23 UTC
Labels: needs investigation
