### ISSUE TITLE
"import clr" results in "no module named 'clr'"

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6167] opened 2020-07-02 10:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1088423/import-clr-results-in-no-module-named-clr.html)._

---
"import clr" results in "no module named 'clr'"

I am trying to study IronPython by the book. 
Installed VS 2019 Community "Python" distribution vs_community__1798533193.1590451443__rid.30001.exe.
It should be inside according to microsoft's directions. 
There is a Python 3.7 x64 environment active.
I can execute there "2+2" simple strings. 
But "import clr" does not work. Autocomplete works in that place. That's weird.
Should VS2019 "IronPython" installer install IronPython, or CPython?

Why Microsoft VS installer never works as described in Microsoft's own manuals?

---
#### Visual Studio Feedback System on 2020/6/23, 06:27 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huguesv** [comment] 2020-07-02 16:55
Duplicate of https://github.com/microsoft/PTVS/issues/5027

**Closed by huguesv** 2020-07-02 16:55 UTC
