### ISSUE TITLE
Checking "Automatically add brackets to functions" has no effect.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7831] opened 2024-02-18 07:40 UTC
**Describe the bug**

<img width="381" alt="image" src="https://github.com/microsoft/PTVS/assets/82852072/256f4e50-72f2-4958-bb24-49a9a30a600d">

**Steps to Reproduce**

1. Check  "Automatically add brackets for functions" (Tools/Options/Text Editor/Python/Advanced)
2. Add "import os" to python file.
3. Write "os.getc", you'll see autocomplete for os.getcwd, selecting it, ensure:
            a. Auto-complete adds os.getcwd() to the source code.

**Additional context and screenshots**

Only **os.getcwd** is added to the file.

![image](https://user-images.githubusercontent.com/82852072/220553174-9e2172b0-e059-4cd4-b535-3d53c4f0f0c7.png)

**Comment by StellaHuang95** [comment] 2024-02-20 21:16
#7827 , #7830 , #7831 , #7832 repro with pylance version >= 2023.12.103, which indicates the bugs might be caused by one of the pyrx commits from 1/4/2024 - 1/10/2024.

**Comment by StellaHuang95** [comment] 2024-02-20 23:07
The commit that caused all these regressions has been narrowed down to https://github.com/microsoft/pyrx/commit/bad397c6c7a04e40ec917e3da412cd7b04e74f2d

**Comment by StellaHuang95** [comment] 2024-02-29 01:33
Update: this bug is probably not caused by any changes in pylance, it also repros with pylance 12.1. Seems like something broken in the upstream.

**Comment by StellaHuang95** [comment] 2024-03-05 21:06
Verified this has been fixed in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.10.0 Preview 2.0 [34701.24.main]

**Closed by StellaHuang95** 2024-03-05 21:06 UTC
Labels: bug
