### ISSUE TITLE
PackageId:CPython2.Exe.x64;PackageAction:Install;ReturnCode:1;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7339] opened 2023-01-18 17:16 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython2Exex64;PackageAction/10250333)._

---
[severity:It bothers me. A fix would be nice]
I was try to install Python, but i get that message. I want to make some apps with Visual Studio 2017, use Python.

---
#### Feedback Bot on 1/11/2023, 06:26 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-18 18:27
duplicate of #7342

**Closed by StellaHuang95** 2023-01-18 18:27 UTC
Labels: needs triage
