### ISSUE TITLE
Error when add virtual environment in py project

### ISSUE THREAD

**Issue by qaqz111** [microsoft/PTVS#7396] opened 2023-02-10 02:25 UTC
The output gives error message `Error: missing params.textDocument.text` while
adding virtual env in py project(a new created empty py project), no matter the venv set to Global available or not.

**But after close the solution and then add venv in VS2022 with no sln loaded, the error will not occur.**

I tried the following steps but the error still came out:
1. Add a venv when no sln loaded
2. Remove the venv just added when no sln loaded (no files deleted on disk)
3. Open a py project and add existing env using dir left in step 2 to the project not setting the venv global available
4. Do anything in Python environment pane Packages(PyPI) group (install or upgrade) the same error came out

The py project used above is a new created one, with only one empty .py file.

I searched old issues here and found #7093 #7326 mentioned the same error message above, but their situation were different from what I encountered. 

This is the error message I got:
```
Error: missing params.textDocument.text
    at _0x37bf59.<computed>.handleOpen (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pylance-langserver.bundle.js:1:293473)
    at _0x2ed90e.onDidOpenTextDocument (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pylance-langserver.bundle.js:1:353494)
    at notificationHandler (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\src\languageServerBase.ts:514:71)
    at handleNotification (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:606:25)
    at processMessageQueue (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:324:17)
    at Immediate.<anonymous> (c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\pylance\dist\pyright-internal\node_modules\vscode-jsonrpc\lib\common\connection.js:311:13)
    at processImmediate (node:internal/timers:466:21)
```

**Configuration information**
VS Version: 17.4.4
PTVS version: 17.0.22263.6
Python version: 3.11.2x64 (I tried 3.9.7x64 still the same error)

**Comment by StellaHuang95** [comment] 2023-02-10 17:52
Thanks for your report. It probably has to do with LSP client not sending us the right data. It's in our backlog to fix. I will mark it as duplicate of #7093 and #7326 for now, and make sure this is fixed once we have a fix for the other two issues. Thanks! 😊

**Closed by StellaHuang95** 2023-02-10 17:52 UTC
Labels: bug

**Comment by qaqz111** [comment] 2023-02-10 21:03
Thanks for your works.

BTW, the temporary solution I found is to change the venv to a global one, thus the error disappeared at least on my machine.
For those who are bothering by this bug can consider giving a try.
