### ISSUE TITLE
Provide richer highlight rendering for the python editor

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7558] opened 2023-04-28 19:03 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-richer-highlight-rendering-for-t/10275105)._

---
When writing python code in vs2022, the code highlighting function is not good enough. I hope it can be as good as vscode.
code in vs2022:
![image.png](https://aka.ms/dc/image?name=B2ec35741e5514e1eaf656429c2df0b1c638115121755375555_20230209-120253-image.png&tid=2ec35741e5514e1eaf656429c2df0b1c638115121755375555)
same code in vscode:
![image.png](https://aka.ms/dc/image?name=Ba91652b726e842639ec2cdc7c7677755638115122343823316_20230209-120353-image.png&tid=a91652b726e842639ec2cdc7c7677755638115122343823316)

---
#### Feedback Bot on 2/9/2023, 00:53 AM: 

(private comment, text removed)

**Comment by StellaHuang95** [comment] 2023-05-02 22:56
duplicate of https://github.com/microsoft/PTVS/issues/7082. We will look into bringing some color customizations back in VS2022.

**Closed by StellaHuang95** 2023-05-02 22:56 UTC
Labels: enhancement, needs investigation
