### ISSUE TITLE
Error when launching Visual Studio Python debug session "One or more Errors occurred. Failed to launch debug adapter..."

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7479] opened 2023-03-29 18:23 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-when-launching-Visual-Studio-Pytho/10316596)._

---
[severity:It's more difficult to complete my work] [regression] [worked-in:17.3]
This is the image as you see in the image below.

![image.png](https://aka.ms/dc/image?name=B34838c4cc707464f82c1aba0fe1b57ee638150101219539675_20230321-174200-image.png&tid=34838c4cc707464f82c1aba0fe1b57ee638150101219539675)

This exists for my global windows 3.6.6 environment and for my python project that has a venv (3.6.6 based).

This started to happen when I upgraded my Visual Studio minor version yesterday.

At this stage, I can't launch Python programs in VS.
How do I solve this?

PS.
"Start without Debugging" works fine.

---
#### Feedback Bot on 3/21/2023, 06:44 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-03-29 19:52
![image](https://user-images.githubusercontent.com/100439259/228652107-757d5347-05ca-4371-897e-2aa2bebd5ff5.png)

**Comment by StellaHuang95** [comment] 2023-03-29 19:54
Thanks for reporting this. This is a duplicate of https://github.com/microsoft/PTVS/issues/7392. "We do not support Python 3.6, as it has been out of support upstream since 2022."

**Closed by StellaHuang95** 2023-03-29 19:54 UTC
Labels: duplicate
