### ISSUE TITLE
PackageId:Microsoft.VisualC.140.Tools.HostX64.TargetARM.Msi.Resources;PackageAction:Install;ReturnCode:2902;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6949] opened 2022-04-04 16:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:MicrosoftVisualC140ToolsHo/10003916)._

---
未能安装包“Microsoft.VisualC.140.Tools.HostX64.TargetARM.Msi.Resources,version=14.0.24234,chip=x64,language=en-US”。
    搜索 URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualC.140.Tools.HostX64.TargetARM.Msi.Resources;PackageAction=Install;ReturnCode=2902
    详细信息
        MSI: D:\VS2017\Packages\Microsoft.VisualC.140.Tools.HostX64.TargetARM.Msi.Resources,version=14.0.24234,chip=x64,language=en-US\VC_Tools.X64.ARM.Res.msi，属性:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7"  VSEXTUI="1"  VS7.3643236F_FC70_11D3_A536_0090278A1BB8="D:\\Program Files (x86)\Microsoft Visual Studio 14.0\" 
        返回代码: 1603
        返回代码详细信息: 安装时发生严重错误
        消息 ID: 2902
        消息详细信息: The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2902. 
    日志
        C:\Users\Administrator\AppData\Local\Temp\dd_setup_20220403223704_004_Microsoft.VisualC.140.Tools.HostX64.TargetARM.Msi.Resources.log
    工作负荷受到影响
        Python 开发 (Microsoft.VisualStudio.Workload.Python,version=15.9.28307.1758)
        使用 C++ 的桌面开发 (Microsoft.VisualStudio.Workload.NativeDesktop,version=15.9.28307.102)
    组件受到影响
        Python 本机开发工具 (Microsoft.ComponentGroup.PythonTools.NativeDevelopment,version=15.9.28307.102)
        适用于桌面的 VC++ 2015.3 v14.00 (v140) 工具集 (Microsoft.

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2022-04-19 17:38
Thanks for your report. The 2902 error may be caused by windows system files damage. Could you try cleaning up any invalid files, uninstalling the program completely, and reinstalling it to see if that works. Thank you!

**Comment by StellaHuang95** [comment] 2022-05-13 17:10
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.

**Closed by StellaHuang95** 2022-05-13 17:10 UTC
Labels: waiting for response
