### ISSUE TITLE
Request to Type Hints similar to PyCharm's

### ISSUE THREAD

**Issue by EdStone** [Microsoft/PTVS#2243] opened 2017-03-07 19:27 UTC
Hi all:

One of the main reasons we're not switching from PyCharm to PVTS is PyCharm's Type Hints (extremely useful in python).
https://www.jetbrains.com/help/pycharm/2016.3/type-hinting-in-pycharm.html
Any possibility of you implementing the same?
I think this would make a lot more people switch to PTVS.
Thanks
E

**Comment by zooba** [comment] 2017-03-07 20:01
As you noticed, duplicate of #82. I'll comment there.

**Closed by zooba** 2017-03-07 20:01 UTC
Labels: duplicate
