### ISSUE TITLE
Add newer Python versions to the PTVS Python installer 

### ISSUE THREAD

**Issue by cwebster-99** [microsoft/PTVS#7804] opened 2024-01-09 17:49 UTC
We currently bundle Python 3.9 with the PTVS Python installer. We should update this to add newer versions of Python as options to install.

**Comment by StellaHuang95** [comment] 2024-01-09 18:16
dupe of #7786

**Closed by StellaHuang95** 2024-01-09 18:16 UTC
Labels: enhancement, needs triage

**Comment by RobertRobertRobert** [comment] 2024-01-23 23:18
What version of python should be installed in Visual studio 22.. i am getting a message i have 3.12? Not fully supported?

**Comment by cwebster-99** [comment] 2024-01-24 16:37
@RobertRobertRobert If you would like full feature support in PTVS, we recommend you use Python 3.9. You can also use newer Python versions, 3.10 or 3.11, but some features such as mixed-mode debugging and profiling will not be supported.

**Comment by RobertRobertRobert** [comment] 2024-01-24 23:04
I have 3.9.

On Jan 24, 2024, at 8:37 AM, Courtney Webster ***@***.***> wrote:

﻿

@RobertRobertRobert<https://github.com/RobertRobertRobert> If you would like full feature support in PTVS, we recommend you use Python 3.9. You can also use newer Python versions, 3.10 or 3.11, but some features such as mixed-mode debugging and profiling will not be supported.
