### ISSUE TITLE
Django Management Console not importing correctly

### ISSUE THREAD

**Issue by skilfulcoding** [Microsoft/PTVS#2444] opened 2017-04-26 08:22 UTC
I've followed the tutorial on MVA (https://mva.microsoft.com/en-US/training-courses/developing-websites-using-python-and-django-11415?l=uw7LHeEJB_5304300477). 

In the tutorial they open the DMC and import as follows: 

`from app.models import Artist`

This generates an error however: 

```
env (Python 3.6 (32-bit)) interactive window [PTVS 3.0.17109.1-15.0]
Type $help for a list of commands.
Starting Django 1.11 shell
>>> from app.models import Artist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".\app\models.py", line 13, in <module>
    class Video(models.Model):
  File ".\app\models.py", line 14, in Video
    filename = models.CharField("File Name", max_length=100)
  File "C:\Users\Gary\documents\visual studio 2017\Projects\Database Fun\Database Fun\env\lib\site-packages\django\db\models\fields\__init__.py", line 1057, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "C:\Users\Gary\documents\visual studio 2017\Projects\Database Fun\Database Fun\env\lib\site-packages\django\db\models\fields\__init__.py", line 172, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "C:\Users\Gary\documents\visual studio 2017\Projects\Database Fun\Database Fun\env\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\Gary\documents\visual studio 2017\Projects\Database Fun\Database Fun\env\lib\site-packages\django\conf\__init__.py", line 39, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```

But if I open a command prompt by right clicking on the project --> 
     Python --> Open Command Prompt here. 

Then:

At the command prompt execute: `python manage.py shell`
and then inside the shell type: `from app.models import Artist`

This imports fine.

The project is setup in a virtualenv, but to check if this made any difference, I also activated the virtualenv at the command prompt and then opened the django shell and it still imported fine.

**Comment by zooba** [comment] 2017-04-26 23:53
I think this is a known issue where we are not setting the environment variables correctly when opening this console. (I don't recall the issue number though...)

**Comment by huguesv** [comment] 2017-09-18 19:50
It's a duplicate of https://github.com/Microsoft/PTVS/issues/2305

**Closed by huguesv** 2017-09-18 19:50 UTC
Labels: bug, resolution:duplicate
