### ISSUE TITLE
Attached to legacy debugger when doing local attach to process with debugger

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#4967] opened 2019-01-08 09:45 UTC
VS Version: 28507.158.d16.0stg
Python Tool Version: 16.0.18354.1
Repro steps:
1. Create a python project
2. Write below code and set a breakpoint:

Input('>')
from math import cos, radians 
def make_dot_string(x): 
    rad = radians(x) 
    numspaces = int(20 * cos(radians(x)) + 20) 
    st = ' ' * numspaces + 'o' 
    return st 
def main(): 
    for i in range(0, 1800, 12): 
        s=make_dot_string(i) 
        print(s) 
main()
3. Start WITHOUT debugging
4. Debug > Attach to Process, select the appropriate python.exe
5.Type enter in the console

**Actual Result:**
It attach to legacy debugger, call stack window is like below:
![image](https://user-images.githubusercontent.com/39871640/50822574-02273e00-136d-11e9-9560-1c239fc6efac.png)

**Expect Result:**
It should attach to debugger,call stack window should like below:
![image](https://user-images.githubusercontent.com/39871640/50822614-1834fe80-136d-11e9-9171-22b18aeb73da.png)

**Comment by huguesv** [comment] 2019-01-08 21:06
Duplicate of https://github.com/Microsoft/PTVS/issues/4738

**Closed by huguesv** 2019-01-08 21:06 UTC
