### ISSUE TITLE
Checking "Automatically add brackets to functions" has no effect.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/PTVS#7958] opened 2024-07-22 07:40 UTC
**Environment**
![image](https://github.com/user-attachments/assets/5ed0b87d-76f5-4acb-89ae-08e754a0e070)

**Steps to Reproduce**
1.Check "Automatically add brackets for functions" (Tools/Options/Text Editor/Python/Advanced)
2.Add "import os" to python file.
3.Write "os.getc", you'll see autocomplete for os.getcwd, selecting it, ensure:

**Expected behavior**
Auto-complete adds os.getcwd() to the source code.

**Additional context and screenshots**

Only os.getcwd is added to the file.

![image](https://github.com/user-attachments/assets/e8560a7a-4209-4763-9a00-97099388ccd8)

**Comment by StellaHuang95** [comment] 2024-08-01 00:37
@linette-zyy I can't repro in Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.12.0 Preview 1.0 [35130.250.main]. Could you verify?

**Comment by linette-zyy** [comment] 2024-08-01 06:21
I can repro in today's build. Python installed from VS.
![image](https://github.com/user-attachments/assets/c83a11e7-442e-4858-adad-3ecda3c7154d)
Only os.getcwd is added to the file.
![13](https://github.com/user-attachments/assets/ae222ce0-183b-44d0-bd0b-9e639b793b95)

**Comment by StellaHuang95** [comment] 2024-08-01 19:52
Might be the pylance version that's making a difference. What's your pylance version?

**Comment by linette-zyy** [comment] 2024-08-07 08:16
I can repro in today's build. Python installed from VS.
![image](https://github.com/user-attachments/assets/6761b50d-1ac1-40c1-aee6-29a22994cff8)

**Comment by StellaHuang95** [comment] 2024-08-13 23:22
I can repro, this is also a regression since pylance 2024.7.104. Might have the same root cause as https://github.com/microsoft/PTVS/issues/7974

**Comment by StellaHuang95** [comment] 2024-09-10 22:42
@linette-zyy can you check if it still repros? Thanks!

**Comment by linette-zyy** [comment] 2024-09-11 06:00
I can repro in today's build. Python installed from VS.
![image](https://github.com/user-attachments/assets/a22b9f6b-a5c5-4e8b-87eb-7a4c3ae066e6)

**Comment by StellaHuang95** [comment] 2024-10-28 21:59
Can't repro with Pylance 2024.10.102. It should be fixed once the latest Pylance is shipped and consumed by PTVS.

**Closed by StellaHuang95** 2024-10-28 21:59 UTC
Labels: bug, P2, fixed in next version
