### ISSUE TITLE
python vesion is 3.12.3 but in vs2022(17.10.0) show 3.1

### ISSUE THREAD

**Issue by zlm166** [microsoft/PTVS#7913] opened 2024-05-29 10:38 UTC
![Uploading QQ截图20240529183216.png…]()

**Comment by StellaHuang95** [comment] 2024-06-05 17:19
Thanks for reporting the issue. Your attached screenshot is corrupted, but I believe it's a duplicate of https://github.com/microsoft/PTVS/issues/7923. Closing as duplicate.

**Closed by StellaHuang95** 2024-06-05 17:19 UTC
Labels: duplicate
