### ISSUE TITLE
Failed to Run Tests and Debug Test from Solution Explorer window.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#7028] opened 2022-06-07 07:13 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/172317340-39ee48a4-a59e-4d47-ab2f-92b918b21a2c.png)

**Steps to Reproduce**

1. Set breakpoints in the test which you want to debug.
2. In SE, right-click to select Debug Selected tests.
3. Check that breakpoints are hit.

![image](https://user-images.githubusercontent.com/82852072/172319106-e677d90b-e5fc-480d-bb5b-fc428015630c.png)

**Additional context and screenshots**
Failed to Run Tests and Debug Test from Solution Explorer window.
On Test output window, it show No tests found to run.

![image](https://user-images.githubusercontent.com/82852072/172318674-57d5e5f6-6d31-4542-bffc-1af18488c96d.png)

**Comment by StellaHuang95** [comment] 2022-06-07 17:07
I am seeing different behavior. The breakpoint did not get hit when debugging the test, but the test was able to run.
![Animation2 - debug test](https://user-images.githubusercontent.com/100439259/172441549-f0d57fc2-aba3-4a17-8b71-0bfb4957bf73.gif)

**Comment by judej** [comment] 2022-06-08 18:34
Dupe of 7034 - which has more info

**Closed by judej** 2022-06-08 18:34 UTC
Labels: needs investigation
