### ISSUE TITLE
Go To Definition doesn't work

### ISSUE THREAD

**Issue by ttSpace** [microsoft/PTVS#6561] opened 2021-06-08 07:01 UTC
**Describe the bug**

![image](https://user-images.githubusercontent.com/82852072/121135810-741a4f00-c867-11eb-8862-7569d10a4c6d.png)

**Steps to Reproduce**

1. Create a Python Application project.
2. Type the code as following or the code you are desiring.
```
from math import cos, radians
import decimal
d = Decimal('0')

# Create a string with spaces proportional to a cosine of x in degrees
def make_dot_string(x):
	rad = radians(x)                             # cos works with radians
	numspaces = int(20 * cos(radians(x)) + 20)   # scale to 0-40 spaces
	st = ' ' * numspaces + 'o'                   # place 'o' after the spaces
	return st
	
def main():
	for i in range(0, 1800, 12):
	    s = make_dot_string(i)
	    print(s)
	
main()

```
3. Move mouse to "decimal", then press F12 or select Go To Definition by right-clicking.

**Actual behavior**

It shows nothing and no output appear in the pylance tab.
![image](https://user-images.githubusercontent.com/82852072/121137962-d1af9b00-c869-11eb-816e-239c130d29e2.png)

**Comment by rchiodo** [comment] 2021-06-08 15:23
Dupe of #6541

**Closed by rchiodo** 2021-06-08 15:23 UTC
Labels: needs triage
