### ISSUE TITLE
Couldnt Install CPython39.Exe.x64

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7119] opened 2022-08-10 17:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Couldnt-Install-CPython39Exex64/10102635)._

---
[regression]
Hi Adam Yoblick

I have followed your instructions and still the error. This time, i have also included Visual Studio Screenshot and logs. Kindly have a look.

---
#### Feedback Bot on 7/24/2022, 07:42 PM: 

(private comment, text removed)
#### Adam Yoblick [MSFT] on 8/3/2022, 11:42 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by judej** [comment] 2022-08-10 18:18
Dupe of 
![image](https://user-images.githubusercontent.com/547753/183987202-21750230-e0b7-4deb-b92d-698267ba9d59.png)

**Comment by AdamYoblick** [comment] 2022-08-10 18:20
Hello,

Could please run VSCollect and send us the setup logs that are bundled by the tool? 

[Download Microsoft Visual Studio and .NET Log Collection Tool from Official Microsoft Download Center](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fdetails.aspx%3Fid%3D12493&data=05%7C01%7CAdam.Yoblick%40microsoft.com%7Cbe166bb14dd04dc8915508da7564f11b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637951373653440202%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8HBNmFnQMGieGBTr%2Bbz3j2thJyRkNIoFMW7KQYkyMsE%3D&reserved=0)

**Comment by StellaHuang95** [comment] 2022-09-06 19:12
Going to close this out. If the issue still persists, please reopen with the information requested. Thanks.😊

**Closed by StellaHuang95** 2022-09-06 19:12 UTC
Labels: waiting for response
