### ISSUE TITLE
Visual Studio 2022 Community prompted weird ".NETFramework,Version=v4.0 were not found." error on python project.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#6882] opened 2022-02-09 17:22 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Visual-Studio-2022-Community-prompted-we/1644660)._

---
In  "Error List" windows, it always prompted:

![image.png](https://aka.ms/dc/image?name=B94781f66d052402bb37e57417644704d637784720989937667_20220122-101458-image.png&tid=94781f66d052402bb37e57417644704d637784720989937667)

Severity	Code	Description	Project	File	Line	Suppression State
Error		The reference assemblies for .NETFramework,Version=v4.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	py1	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1217	

I've tried 1) repair. 2)Uninstall and reinstall. None worked.
OS: Win10 Ent 21H2

Thanks.

---
#### Feedback Bot on 1/23/2022, 10:35 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by AdamYoblick** [comment] 2022-02-09 23:21
Dupe of #6747. This has been fixed locally and will be released in the next version, or the version after that if it didn't make it in in time. If you need a workaround, please see #6747

**Closed by AdamYoblick** 2022-02-09 23:21 UTC
Labels: needs triage
