### ISSUE TITLE
debug pd.read_sql_query

### ISSUE THREAD

**Issue by dmlan** [Microsoft/PTVS#2911] opened 2017-08-15 02:23 UTC
when I debug pd.read_sql_query .If there is Chinese in result .When I use F5 ,it's good.
But when I use F10 or Shift+F9 ,vs return me "error: " ,Just this only. 
And I can't catch the exception ! The debug stopped. 
the same code,when i use vs code ,it's good.
thank you!

**Comment by zooba** [comment] 2017-08-15 16:38
What version of Python are you using? Is it 2.7 or 3.x?

**Comment by zooba** [comment] 2017-08-16 18:09
Sounds like we have a Python 2.7 Unicode bug in our debugger somewhere. Thanks!

**Comment by int19h** [comment] 2017-08-16 20:36
I can't repro this on Anaconda 4.4.0 2.7 with the following code:
```py
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cur = conn.cursor()

cur.execute('''CREATE TABLE foo (s TEXT)''')
cur.execute('''INSERT INTO foo VALUES ('bar')''')
cur.execute(u'''INSERT INTO foo VALUES ('\u4E00')''')
conn.commit()

df = pd.read_sql_query('SELECT * FROM foo', conn)
print(df)
```
Stepping over the line with `read_sql_query` does not trigger any error messages, nor does inspecting `df`. The Unicode symbol is shown correctly in `df` repr, and in expanded children.

Can you provide some sample code to reproduce the error?

**Comment by dmlan** [comment] 2017-08-17 02:49
@int19h 
Try this, please. Thanks!
`import sys
reload(sys)
sys.setdefaultencoding('utf8')

import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cur = conn.cursor()

cur.execute('''CREATE TABLE foo (s TEXT)''')
cur.execute('''INSERT INTO foo VALUES ('bar')''')
cur.execute(u'''INSERT INTO foo VALUES ('\u4E80')''')
conn.commit()

df = pd.read_sql_query('SELECT * FROM foo', conn)
print(df)`

**Comment by zooba** [comment] 2017-08-17 15:29
FWIW, `sys.setdefaultencoding` is a hack (according to Guido himself) and should be avoided wherever possible.

In this case, because the encoding is changed after we have loaded the debugger, it's probably not possible to handle it. You may have more luck importing `ptvsd` as a module after changing the default encoding and using Debug-Attach to connect to the running process.

I don't think we need to support this scenario, but if @int19h thinks there's a relatively easy way to do it then he can go ahead.

**Comment by int19h** [comment] 2017-08-17 20:48
FWIW, with the sample code above, I'm still not getting an error. The only difference is that repr of `df` now shows a question mark for the Unicode symbol (but if you expand it and look at the values inside individually, you see proper Unicode string literals with escapes there). And the question mark is already there in the repr as soon as it returns - it's not something that we introduce in our own string handling.

**Comment by zooba** [comment] 2017-08-17 22:28
@dmlan What is your actual default encoding?

**Comment by dmlan** [comment] 2017-08-18 10:51
![image](https://user-images.githubusercontent.com/29965978/29455785-1eb01ad2-8445-11e7-8809-0470c6be1327.png)
![image](https://user-images.githubusercontent.com/29965978/29455845-578f3144-8445-11e7-8d58-35186909def3.png)
sys.version
'2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]'
pd.__version__
u'0.20.0rc1'

@zooba Thank you so much！ I removed sys.setdefaultencoding ,everything looks like ok. 
I'm new to git and python. Should I close this issue?

**Comment by zooba** [comment] 2017-08-18 16:44
I'll close it.

If you want proper Unicode support, you should move to Python 3 as soon as you can. There is simply no way to achieve it in Python 2.

**Closed by zooba** 2017-08-18 16:44 UTC
Labels: bug, Debugger
