### ISSUE TITLE
API to get type-annotated AST

### ISSUE THREAD

**Issue by lostmsu** [microsoft/PTVS#2948] opened 2017-08-26 19:05 UTC
Is there an existing API, that would let me programmatically analyze my Python project?

If there's not one yet, I could work on one if only team can point which classes could provide such a thing, and, if possible, what to do to have a minimal setup to get them up and running on a specific Python module.

To give some background: I was already able to get `PythonInterpreterFactoryWithDatabase.GenerateDatabase` complete successfully from a console app (exitCode == 0) on my Python 3.6 installation without passing path to the module I want to analyze yet.

**Comment by zooba** [comment] 2017-08-28 17:18
Right now it exists, but we are in the process of reworking it significantly and the existing API is likely to become unsupported in favour of running our analyzer and using the JSON protocol (which will eventually be the [language server protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md)).

I can't stop right now to do a full write-up of the current API, unfortunately (and I can't find any of our existing ones), but if you look through the AnalysisTests project you'll see plenty of examples where we analyze small snippets of code and examine the results. You should be able to do the same thing from your own application requiring only `Microsoft.PythonTools.Analysis.dll` and `Microsoft.PythonTools.Common.dll` (and if your application is a VS extension, then add a prerequisite for Python support and you won't even need to install those DLLs).

**Comment by lostmsu** [comment] 2017-09-10 22:16
@zooba , I was able to get AnalysisValue(s) for top-level module members. However, I got stuck in a dumbest thing: getting AnalysisValue for function parameters. I can obtain IAnalysisVariable for their occurrences, but then to go from it to AnalysisValue I'd need SourceLocation, but IAnalysisVariable.Location lacks seemingly required Index property.

In tests this index is mostly obtained by simple "source code".IndexOf("parameter-reference line text"), which is barely applicable, and very inefficient.

**Comment by zooba** [comment] 2017-09-11 19:18
Can you share some of your code? I think you don't need the exact index of the parameter - you just need some point within the scope that the name should be resolved within, but it depends on exactly what functions you are using.

And as I said, it's entirely possible that we've missed making something public that needs to be, and we should fix that :)

**Comment by lostmsu** [comment] 2017-09-13 04:52
@zooba, here you go

```csharp
string testModule = Path.GetFullPath(@"sample.py");
var interpreter = InterpreterFactoryCreator.CreateAnalysisInterpreterFactory(PythonLanguageVersion.V36.ToVersion()).CreateInterpreter();
var testModuleData = AstPythonModule.FromFile(interpreter, testModule, PythonLanguageVersion.V36);
IPythonProjectEntry module = analyzer.AddModule("sample", testModule);
//module.Analyze(CancellationToken.None, enqueueOnly: true);
//analyzer.AnalyzeQueuedEntries(CancellationToken.None);
var errorSink = new CollectingErrorSink();
using (var reader = new StreamReader(testModule))
using (Parser parser = Parser.CreateParser(reader, analyzer.LanguageVersion,
                        new ParserOptions { BindReferences = true, ErrorSink = errorSink })) {
    PythonAst ast = parser.ParseFile();
    module.UpdateTree(ast, null);
}
foreach (ErrorResult error in errorSink.Errors) {
    Console.Error.WriteLine(error.ToString());
}
module.Analyze(CancellationToken.None);
analyzer.AnalyzeQueuedEntries(CancellationToken.None);
MemberResult[] members = module.Analysis.GetAllAvailableMembersByIndex(0).ToArray();
AnalysisValue f = module.Analysis.GetValuesByIndex(nameof(f), 0).Single();
ParameterResult aParameter = f.Overloads.Last().Parameters.First();
IAnalysisVariable aReference = aParameter.Variables.First(v => v.Type == VariableType.Reference);
var parameterLocation = new SourceLocation(0, aReference.Location.StartLine, aReference.Location.StartColumn);
int parameterReferenceIndex = File.ReadAllText(testModule).IndexOf("print");
AnalysisValue[] aValues = module.Analysis.GetValues("a", parameterLocation).ToArray();
AnalysisValue[] aValuesByIndex = module.Analysis.GetValuesByIndex("a", parameterReferenceIndex).ToArray();
```

sample.py:
```python
def f(a, b):
    print(a)

f(1, "2")
```

Gives back: aValues.Length == 0; aValuesByIndex.Length == 1 (expected).
Notice how I have to do index of to find a location inside f(...)

**Comment by zooba** [comment] 2017-09-13 18:07
Ah, I see. We rely on SourceLocation.Index to be set correctly when using it to resolve the lookup scope, but we don't actually make the index available anywhere - we have private methods on the AST to figure it out.

I think the problem is leaking out the `LocationInfo` class, which seems to be meant to be internal only. `SourceLocation` should be the only public one (the difference is that `LocationInfo` knows which file the location is within, and has internal mechanisms for lazy resolution).

We do have a likely big breaking change coming up (#2846) when we can also make `LocationInfo` private and update the other APIs to return and accept `SourceLocation` (since in most cases the file they belong to is known). Looking at this use case, we probably also need to add a better public API for requesting specific locations (e.g. location of name, location within scope, etc.).

The best way I can see to get the information you need is to use an AST walker (`PythonWalker` subclass and `ast.Walk(walker)`) to find the function, rather than the ModuleAnalysis APIs. This will give you access to the `FunctionDefinition` object, which has the `SourceLocation` values you need in order to query analysis in a particular scope. Our [`QualifiedFunctionNameWalker`](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/QualifiedFunctionNameWalker.cs) is a fairly simple example of locating a specific function and generating its full name (though in most cases you'll want to override `Walk` rather than `PostWalk`). If you provide the ModuleAnalysis object when constructing your walker, you can call into it as you walk each function to get whatever info you need.

Hope that helps!

**Closed** 2021-07-28 22:12 UTC
Labels: question
