### ISSUE TITLE
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7307] opened 2023-01-11 19:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/PackageId:CPython39Exex64;PackageActio/10235223)._

---
[severity:I'm unable to use this version]
**Describe your issue here**  
  Any attempt to install or reinstall this package always fails. I removed everything and reinstalled but the error persists. My Windows has all the latest updates installed.

===DO NOT EDIT BELOW THIS LINE===  
PackageId:CPython39.Exe.x64;PackageAction:Install;ReturnCode:1603;

---
#### Feedback Bot on 12/20/2022, 06:50 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by StellaHuang95** [comment] 2023-01-11 20:07
duplicate of #7320

**Closed by StellaHuang95** 2023-01-11 20:07 UTC
Labels: needs triage
