### ISSUE TITLE
Python Autocomplete Does Not Disable.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7128] opened 2022-08-17 18:49 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Python-Autocomplete-Does-Not-Disable/10114080)._

---
After unchecking every box related to "Intelli", disabling autocomplete, and scouring the settings page I still cannot get autocomplete to disable.  Please let me know how to disable this thing as it gets in the way, recommending gems like "__import__" when trying to type a simple if statement.

---
#### Feedback Bot on 8/9/2022, 00:22 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by therealzoomgod** [comment] 2022-08-19 14:48
I'm having same issue vsfeedback is.  The intellisense in VS2022 is an absolute wrestling match to write python code with but I can't find a way to disable it.  Just want to turn it off and go about my work in peace lol

**Comment by StellaHuang95** [comment] 2022-08-22 17:01
That would an enhancement. Duplicate of #6881

**Closed** 2022-08-22 17:39 UTC
Labels: duplicate
