### ISSUE TITLE
Intellisense issues and crashes with Python 2.7 in VS2017 Enterprise

### ISSUE THREAD

**Issue by tamasoz** [Microsoft/PTVS#4701] opened 2018-09-05 07:02 UTC
I have recently installed VS2017 Enterprise at work. We not only use it for standard .NET dev but for Python too. Anyhow, whilst with previous VS versions I managed to make the Python intellisense work (DB refresh, trial-and-error and the rest), this time all I get is an error message and some encouraging words to report this issue on the issue tracker - so here it is:

My VS 2017 Enterprise version number is 15.8.2

This issue only happens if I try to use the Python2.7 under the standard ArcGIS installation path (C:\Python27\ArcGIS10.5) if I use the Python 3.6 (C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\) things seem working fine in the interactive window. 

This problem did not exists neither in VS2013 nor VS2015...

Well - the prinout from the as follows:

`
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.8.18201.1

System.InvalidOperationException: Failed to initialize analyzer
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<InitializeAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<CreateForProjectAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateAnalyzerAsync>d__134.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProjectHelper>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

`

**Comment by huguesv** [comment] 2018-09-05 21:53
Thanks!

This is a duplicate of #4660

This is fixed in 15.8.3, which will be released very soon (this week).

**Closed by huguesv** 2018-09-05 21:53 UTC
Labels: resolution:duplicate
