### ISSUE TITLE
An unexpected error occurred evaluating python expression

### ISSUE THREAD

**Issue by a-j-albert** [microsoft/PTVS#6014] opened 2020-02-10 10:36 UTC
**Describe the bug**
I was evaluating a python expression in the python debugger and devenv didn't respond for about 60 seconds

[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 16.4.19310.1

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.PythonTools.Repl.PythonDebugProcessReplEvaluator..ctor(IServiceProvider serviceProvider, PythonProcess process, IThreadIdMapper threadIdMapper)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<AttachProcessAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.<OnReadyForInputAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

**Comment by huguesv** [comment] 2020-02-18 22:50
Looks like a duplicate of https://github.com/microsoft/PTVS/issues/4957

I would suggest disabling the legacy debugger in tools/options/python/debugging.
Note that you might end up running into https://github.com/microsoft/PTVS/issues/5827, we've fixed that one for 16.5.

**Closed by huguesv** 2020-02-18 22:50 UTC
Labels: needs triage
