### ISSUE TITLE
An unexpected error occurred (after changing a python environment)

### ISSUE THREAD

**Issue by fmarionpoll** [Microsoft/PTVS#4699] opened 2018-09-03 08:47 UTC
The error occurred after I loaded a project from bitbucket, created a visual studio from the existing code and selected a conda environment designed to work with this program.
My machine is:
- Windows 10 Pro
- Visual Community 15.8.2
- Anaconda2 (installed outside visual studio)
- Selection of a conda Python environment derived from Python2.7 (64 bits)

Here is the content of the error dialog:
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.8.18201.1

System.InvalidOperationException: Failed to initialize analyzer
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<InitializeAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<CreateForProjectAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateAnalyzerAsync>d__134.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProjectHelper>d__147.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.PythonProjectNode.<ReanalyzeProject>d__146.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by huguesv** [comment] 2018-09-05 21:52
Thanks!

This is a duplicate of https://github.com/Microsoft/PTVS/issues/4660

This is fixed in 15.8.3, which will be released very soon (this week).

**Closed by huguesv** 2018-09-05 21:52 UTC
Labels: resolution:duplicate
