### ISSUE TITLE
VS 15.7 becomes unresponsive when setup.py is open

### ISSUE THREAD

**Issue by marcelvb** [Microsoft/PTVS#4181] opened 2018-05-08 17:28 UTC
I installed Microsoft Visual Studio Enterprise 2017, Version 15.7.0+27703.1 with Python 15.7.18116.1 and Python 3.6.5. When I open setup.py VS becomes unresponsive and I can't do anything anymore, except kill with the task manager. 

It looks like a mouse focus problem, maybe due to hover with the mouse causes a very large mouse over window on the setup() call with parameters spread over the whole window.

**Comment by huguesv** [comment] 2018-05-08 22:07
Thanks for the report.

We've had issues with quick info tooltip in 15.6 and also 15.7 previews, but we thought those were resolved when we switched to the quick info async api.

You're saying it hangs when you pause the cursor over the code. Is it before the tooltip appears? Is it every time?

There's a small chance that having your setup.py may help us reproduce the bug. If you can share it, please do. You can send it by email to ptvshelp at microsoft dot com if you'd rather not post it here.

It would be helpful to attach a debugger and see what the main thread is doing.
- Start another instance of VS 
- Uncheck the "Enable Just My Code" debugging option (Debug->Options).
- Debug->Attach to Process, select the unresponsive devenv.exe process.
- Pick the main thread from the thread window or toolbar
- Open the call stack window, select all (CTRL+A), copy (CTRL+C) then paste it here.

It's also possible to submit dumps using Send Feedback->Report a Problem.

**Comment by marcelvb** [comment] 2018-05-09 08:29
The offending file:
[setup.py.txt](https://github.com/Microsoft/PTVS/files/1986959/setup.py.txt)

Since the stacktrace looked different (to me) each time, I tried 4 times. Results:

[vs-python-bug-stacktraces.txt](https://github.com/Microsoft/PTVS/files/1986956/vs-python-bug-stacktraces.txt)

**Comment by huguesv** [comment] 2018-05-09 16:58
Thank you very much. I'm able to reproduce the issue.

**Comment by huguesv** [comment] 2018-05-10 00:17
Internal bug 613925. It's a bug in the editor, due to the contents of the quick info tooltip being too large to fit the screen. The repro is to put the mouse cursor on `codecs`.

**Comment by huguesv** [comment] 2018-06-08 15:58
Internal bug has been resolved. Fixed in next 15.8 update.

**Closed by huguesv** 2018-06-08 15:58 UTC
Labels: area:Editor, bug, priority:P0, resolution:external, tenet:Reliability
