### ISSUE TITLE
import ptvsd throws NameError exception

### ISSUE THREAD

**Issue by joneal** [Microsoft/PTVS#2127] opened 2017-02-08 16:38 UTC
I have a .NET/C# application that hosts various Python scripts that are loaded at run time.  I use both Visual Studio and VS Code to do remote debugging on these scripts via ptvsd.  Everything has been working great.

I am switching to a new workstation.  Code has been copied over.  Scripts have been copied over, including the ptvsd directory.

When I run my application on my new machine, the "import ptvsd" line is now throwing a NameError exception.  I verified that the ptvsd directory lives in the same place as on the machine in which it is working.  (I even copied the whole script directory tree from my working machine to my new machine).

Here is the script that is throwing the exception (script is a text resource in the .NET application):

    try:
	print 'Configuring PTVSD...one moment please'
	try:
		import ptvsd
		ptvsd.enable_attach("Anduin", address=('localhost', 6677))
		print 'PTVSD configured'
	except ptvsd.AttachAlreadyEnabledError:
		print 'PTVSD already configured for this process...continuing'
	print 'Waiting for remote debugger to attach...'
	ptvsd.wait_for_attach()
	print 'Remote debugger attached!  Running script...'
	execfile(r'{0}')	
    except Exception, e:
	if str.find(str(sys.exc_info()[1]),'Thread was being aborted.') == -1:
		print CommonTestUtilities.createExceptionOutputString(sys.exc_info())
	raise e
    finally:
	ptvsd.visualstudio_py_debugger.detach_process_and_notify_debugger()

The 

    import ptvsd

is apparently throwing the NameError exception

Again, all of this works on my old machine, and I am trying to get it to work on my new machine, so I suspect an environmental issue.  However, I have copied the source and scripts from the old machine to the new machine.  I thought the 'ptvsd' folder was essentially an XCOPY deployment, which is how I am treating it.

Is there anything obviously missing, or something I should investigate?  Thanks.

**Comment by zooba** [comment] 2017-02-10 20:28
Does the error show what name it is expecting? And the code that is trying to access it?

If you're running in a hosted IronPython environment, it's possible that names have changed or are simply missing.

**Comment by joneal** [comment] 2017-02-13 15:49
It was choking on 'ptvsd' in the 'import ptvsd' statement in the code above, which caused the NameError exception.

I messed around with some of my paths on the new machine (PATH environment variable, Windows 10) and suddenly the exception went away.  No idea why, other than I removed the Python 2.5 path.  (It is present on the old machine and still works).  Our application is using IronPython.

**Comment by zooba** [comment] 2017-02-13 16:41
Well, glad you got it working. It's certainly possible for the PATH variable to affect things, though I don't know what would have been the cause here. If you happen to figure out exactly which change made the difference, please let us know, otherwise I'll close this one out.

**Closed by zooba** 2017-02-13 16:41 UTC
