### ISSUE TITLE
IntelliSense in .py file of IronPython WPF Application does not work

### ISSUE THREAD

**Issue by zhouwangyang** [Microsoft/PTVS#5121] opened 2019-02-25 09:44 UTC
VS Version: 28622.103.d16.0
Python Tool Version: 16.0.19051.1
Repro step:
1.Make sure IronPython installed in your machine
2.Create IronPython WPF Application 
3.Drag & drop a button to the Design view
4.Double click on it
5.Default .py file launched, and event handler is generated in code
6.Add MessageBox to import(From System.Windows import MessageBox)
7.In the Button_Click handler, add a call to MessageBox.Show()

Except result:
1.Code coloring with MessageBox 
2.Signature info tooltip shows all overloads
![image](https://user-images.githubusercontent.com/39871640/53328272-8c7b2f80-3924-11e9-81c3-0534465f2b04.png)

Actual result:
1.No Code coloring with MessageBox 
2.No Signature info tooltip shows all overloads
3.unresolved import 'System.Windows' in code
![image](https://user-images.githubusercontent.com/39871640/53328462-fe537900-3924-11e9-9eab-a72d7424f03f.png)

**Comment by huguesv** [comment] 2019-02-25 18:12
duplicate of https://github.com/Microsoft/PTVS/issues/5027

**Closed by huguesv** 2019-02-25 18:12 UTC
