### ISSUE TITLE
Tons of exception spam in the output window

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#5] opened 2015-04-06 19:50 UTC
**Pre-requisites:**
* Mixed mode debugging enabled
* Debug Python 2.7 environment

You can repro this with any script.  You can just have a one-line script with `import sys` and put a breakpoint on the first line.  By the time the breakpoint has hit, there are already hundreds of lines of exceptions in the output window, making it hard to get any useful information from the debug window if you are using OutputDebugString or otherwise trying to read the contents of the debug window.

Short sample output:
```
Short snippet:
exceptions.AttributeError
exceptions.TypeError
exceptions.AttributeError
exceptions.AttributeError
exceptions.AttributeError
exceptions.TypeError
exceptions.AttributeError
exceptions.AttributeError
exceptions.TypeError
exceptions.TypeError
exceptions.TypeError
exceptions.TypeError
exceptions.TypeError
exceptions.TypeError
exceptions.AttributeError
exceptions.AttributeError
'python_d.exe' (Python): Loaded 'D:\python_src\Python-2.7.8\lib\sysconfig.py'. Module was built without symbols.
exceptions.AttributeError
exceptions.TypeError
exceptions.TypeError
exceptions.TypeError
exceptions.AttributeError
'python_d.exe' (Python): Loaded 'D:\python_src\Python-2.7.8\lib\re.py'. Module was built without symbols.
'python_d.exe' (Python): Loaded 'D:\python_src\Python-2.7.8\lib\sre_compile.py'. Module was built without symbols.
'python_d.exe' (Python): Loaded 'D:\python_src\Python-2.7.8\lib\sre_parse.py'. Module was built without symbols.
'python_d.exe' (Python): Loaded 'D:\python_src\Python-2.7.8\lib\sre_constants.py'. Module was built without symbols.
```

Over the normal course of running my application, I counted that ~3,000 out of ~3,500 lines were just these exception messages.  It would be nice if these could be silenced.  If the issue is by design, then maybe there's a way to silence it only for exceptions that are thrown by the interpreter?

**Comment by burhop** [comment] 2015-04-08 15:58
I'm getting the same thing in VS2012 with python33.dll  (python 3.3.2 64 bit) mixed mode.   Its a significant pause before you can start debugging.

**Comment by int19h** [comment] 2015-04-08 20:02
Copying the explanation of the issue from our email discussion about this.

"We report an exception as raised as soon as someone calls `PyErr_Set`. This covers `raise` in Python, and various other ways to get an exception, but this also covers any C code that reports an error. The thinking there was that if an exception is raised by your C extension, you would want it to be reported right away, when you still have the native stack etc, rather than when it crosses the boundary to Python and loses all native context. Unfortunately, this means that we report a lot of exceptions that are “thrown” and “caught” entirely in native code during regular execution – since a lot of Python extensibility API uses it for routine things (e.g. when determining operator implementation to call, or when importing modules).  

It also makes debugging slower, because every time that exception is reported, we have to freeze and then unfreeze the debugged process. This is especially noticeable if you import a lot of stuff (http://pytools.codeplex.com/workitem/2670). Really, we shouldn’t be doing that nor printing anything out if you are not set to break on any exception type. We should probably also make it a choice whether exceptions should be reported at `PyErr_Set` or at Python boundary."

**Comment by zooba** [comment] 2015-04-20 19:17
We probably don't have to print anything out at all, though this is sometimes nice.

How efficiently can we check the call stack to see whether the exception is being set from Python code vs. native code vs. builtin module?

**Comment by int19h** [comment] 2015-04-20 19:21
We don't actually handle the printing in mixed-mode, we just report the exception (or not).

I don't think we can reliably distinguish exceptions originating from Python vs native (the problem is that raising from Python ultimately also goes to the same place as native). What we can do is distinguish between PyErr_Set, and exception crossing into Python (only the latter will trigger settrace hook). So if exception is raised and caught entirely in native, which is the case for most of these, only reporting on the boundary would filter out most of them.

OTOH, reporting at PyErr_Set is also occasionally useful, so this should be a switch.

**Comment by zooba** [comment] 2015-04-23 18:27
Sounds like a valuable switch to have. Maybe we can also introduce a breakpoint at startup and disable exceptions before that to avoid the load delay?

**Comment by int19h** [comment] 2015-04-23 19:09
This would help for the initial imports from builtins, but not when you start importing your own stuff explicitly (and usually the worst delay comes from that, e.g. if you import numpy...). I think that making it so that exceptions are not reported at all when nothing in checked in the Exceptions dialog (which is the default for mixed mode) should adequately cover this scenario.

**Closed** 2015-05-27 23:51 UTC
Labels: bug, Debugger, Native Modules

**Comment by yuanms2** [comment] 2016-01-31 03:20
I met with this issue again.
The setting:
Microsoft Visual Studio Ultimate 2013, version 12.0.40629.00 Update 5.
PTVS: 2.2.31124.00

In mixed python/c++ debugging.
@int19h told me some way to work around the issue:
"check your exception settings
Debug -> Exceptions when attached
make sure you don't have any checked in the "Unhandled" column
it should not be printing out any exceptions if you have all of them unchecked"

However, even when all the checkboxes are cleared, the issue still exists.
Could you please figure out why the issue re-occur in the PTVS? Thanks.

**Comment by zooba** [comment] 2016-02-01 21:46
@yuanms2 It would help if you could show the output you are seeing and the code that is causing it. Right now we don't have enough info to follow up on.
