### ISSUE TITLE
REPL not working, *.sln load fails

### ISSUE THREAD

**Issue by pyuser00** [Microsoft/PTVS#1573] opened 2016-08-31 00:03 UTC
My Python interactive window is not working in VS2015 with PTVS 2.2.40623 using Anaconda v3.5. Every key stroke I enter produces double the input; for example typing 'i' writes 'ii' to the interactive console. I have tried both Python and IPython, both with the same. There are several errors in the ActivityLog.xml; but I am not sure how to read them.

Maybe related; every *.sln I open return and error that the project failed to load and then loads if I right click on the solution and reload. Also, the automatic outlining is not working.

**Comment by zooba** [comment] 2016-09-01 16:46
You can attach the whole ActivityLog.xml if you like, but first try deleting the files in `%LocalAppData%\Microsoft\VisualStudio\14.0\ComponentModelCache` and restarting VS to see if that fixes it.

**Comment by pyuser00** [comment] 2016-09-02 00:29
Proposed solution had no impact. Solution failed to load after restart and REPL incorrectly translates key strokes. Notice the following keys are translated correctly (1,2,3,4,5,6,7,8,9,0,-,\,/,[,],.,') to Python interpreter while all others create double entries, i.e. type 'a' produces 'aa' in REPL. 

The output window shows the following error when trying to load a project:
error  : Object reference not set to an instance of an object.

Some of the *.py source files in the solution are not even recognized as Python because no syntax highlighting is present.

**Comment by huguesv** [comment] 2016-09-02 16:56
Hi!  If you rename the ActivityLog.xml to ActivityLog.txt, you should be able to drag & drop it in this issue. Some parts of PTVS are not loading correctly, and the log will hopefully help in seeing where it's failing. Thanks!

**Comment by pyuser00** [comment] 2016-09-06 12:19
Also thought it may be a conversion error from VS2013 to VS215; but I get the same issue when creating a new project.

I copied all entries from ActivityLog.xml with type error:

<entry>
    <record>379</record>
    <time>2016/09/02 11:27:37.828</time>
    <type>Error</type>
    <source>Extension Manager</source>
    <description>Extension will not be loaded because an extension with the same ID &apos;Microsoft.VisualStudio.TeamFoundation.TeamExplorer.Extensions&apos; is already loaded at C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\4NDYSCFD.VN2\...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TEAMFOUNDATION\TEAM EXPLORER\</path>
  </entry>
  <entry>
    <record>380</record>
    <time>2016/09/02 11:27:38.432</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifier..ctor(PythonClassifierProvider provider, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifierProvider.GetClassifier(ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>
  <entry>
    <record>381</record>
    <time>2016/09/02 11:27:38.437</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.OutliningTaggerProvider.OutliningTagger..ctor(PythonToolsService pyService, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.PythonTools.OutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
  <entry>
    <record>382</record>
    <time>2016/09/02 11:27:38.451</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.PythonTools.Extensions.GetAnalyzer(ITextView textView, IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.PythonTools.Intellisense.IntellisenseControllerProvider.TryCreateIntellisenseController(ITextView textView, IList`1 subjectBuffers)&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.IntellisenseManagerConnectionListener.&lt;&gt;c__DisplayClass8_1.&lt;SubjectBuffersConnected&gt;b__1(IIntellisenseControllerProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InstantiateExtension[TExtension,TMetadata,TExtensionInstance](Object errorSource, Lazy`2 provider, Func`2 getter)</description>
  </entry>
  <entry>
    <record>383</record>
    <time>2016/09/02 11:27:38.908</time>
    <type>Error</type>
    <source>Color Theme Service</source>
    <description>The color &apos;Popup&apos; in category &apos;de7b1121-99a4-4708-aedf-15f40c9b332f&apos; does not exist.</description>
  </entry>
  <entry>
    <record>384</record>
    <time>2016/09/02 11:27:38.917</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.PythonTools.Extensions.GetAnalyzer(ITextBuffer buffer, IServiceProvider serviceProvider)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifier..ctor(PythonClassifierProvider provider, ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.PythonTools.PythonClassifierProvider.GetClassifier(ITextBuffer buffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass12_0`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeEligibleFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, IContentTypeRegistryService contentTypeRegistryService, Object errorSource)</description>
  </entry>
</activity>

**Comment by huguesv** [comment] 2016-09-07 18:00
It could be a configuration issue.

Can you please copy the results from Tools/Python Tools/Diagnostic Info, and email it to us at: ptvshelp at microsoft.com

**Comment by azuric** [comment] 2016-09-09 16:33
Hi I am having exactly the same issue.

double key strokes and the error in the activity log

**Comment by zooba** [comment] 2016-09-12 21:06
I see in the diagnostic info that was emailed there is a custom environment that isn't set up properly. It's likely that one is being selected for some reason and we're not handling this properly (from the error, somewhere deep inside the classification stack).

I'd suggest opening the Python Environments window (Ctrl+K, Ctrl+`), selecting "New Environment 1", choosing "Configure" from the dropdown below it and then "Remove" to delete it. You may need to close and reopen some windows (that is to say, you _shouldn't_, but since things are already broken I'm going to assume they may be broken :) ).

If that doesn't help, we're going to have to dig a little deeper, but hopefully the problem is the environment configuration.

**Comment by pyuser00** [comment] 2016-09-13 09:56
That seems to have fixed the REPL, but I still get the 'error object reference not set to an instance of the object' every time I open a solution.

**Comment by zooba** [comment] 2016-10-18 18:52
Sorry for the long delay - that error is likely due to a bug in 2.2.4 that was fixed in 2.2.5, so upgrading should fix it. You should have seen a notification in VS already, so chances are you are already up to date.

**Closed by zooba** 2016-10-18 18:52 UTC
