### ISSUE TITLE
It seems that Visual Studio 2022 Python program cannot print Traditional Chinese characters.   But same code on Visual Studio 2019, It is OK?  

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/PTVS#7542] opened 2023-04-28 18:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/It-seems-that-Visual-Studio-2022-Python-/1600675)._

---
[regression]
# Python code on Visual Studio 2019, it is OK.

# But same code on Visual Studio 2022, It fails !  

SyntaxError: Non-UTF-8 code starting with '\xc1' in file , but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

```
import numpy as np 
import matplotlib as plt 

y = 'ABC  繁體中文'  
print(y, end = '\n\n') 
```

---
#### Feedback Bot on 12/1/2021, 08:45 PM: 

(private comment, text removed)

**Comment by cwebster-99** [comment] 2023-05-02 20:28
Dupe of https://github.com/microsoft/PTVS/issues/6784. The fix is being implemented by the VS Editor team.

**Closed by cwebster-99** 2023-05-02 20:28 UTC
Labels: needs triage
