### ISSUE TITLE
Ability to run a single test function in a unittest class, using context menu.

### ISSUE THREAD

**Issue by HHest** [Microsoft/PTVS#2040] opened 2017-01-09 12:45 UTC
Hi,

A feature request please. I used to use a tool that allowed me to run any particular test function in a unittest suit, simply by right clicking in that function. Doing so would bring up a menu, with run/debug this function as a choice. 

Being able to run a test directly, without switching to an additional framework (like Test Explorer), and without any further code modification, would be a very handy feature for me.

Regards!

**Comment by huguesv** [comment] 2017-01-09 17:44
Hi HHest,

Thanks for the feedback.

Run Tests and Debug Tests commands should appear in the editor context menu when the Test Explorer window is opened (test explorer opened => test discovery process is running).

![image](https://cloud.githubusercontent.com/assets/1696845/21776388/059ffb56-d64f-11e6-8e78-84ac23a74a5c.png)

The commands are designed to be "location sensitive" so that you can run or debug an individual test or all tests in the file, depending on where your caret is located.

However, it looks like it's having trouble running the correct tests in Python projects (when right-clicking on a single test). I checked that the feature works fine in C# projects.

Hopefully this is something that we can fix.

**Comment by huguesv** [comment] 2017-01-09 17:50
Looks like the issue is a partial duplicate of the issue described here: https://github.com/Microsoft/PTVS/issues/1919

**Comment by huguesv** [comment] 2017-01-09 18:10
One more note: The feature seems to work well on VS 2015 Update 3.  The issues I ran into are isolated to VS 2017.

**Comment by HHest** [comment] 2017-01-10 11:26
Hi huguesv,

Thanks for your messages about Test Explorer, which I used in the past on VS 2013 but stopped because it was too CPU intensive: it keep on trying to discover tests and slowed my computer down. (This request for a standalone right-clickable test launcher was actually based on this experience.)

I am giving it a try again, now that we have VS 2015. Will report back.

Regards.

**Comment by HHest** [comment] 2017-01-11 13:09
As before, I find that the Test Explorer is a cumbersome tool for us. One big problem is, every time I save a change, the Test Explorer would take about 30 seconds to run the "discover test" process on our code base. During this time, I cannot run any tests via TE, even tests that were previously "discovered". This delay is quite annoying and counterproductive. What's worse, sometimes it gets stuck with something, and even a restart of VS does not help.

It also has some other quirks in how it runs tests, such that some of my tests which would run fine in py.test, or nosetests, or python, suddenly fail to run. However, I guessing this is some configuration setting that I haven't had the time to figure out.

I have updated the original comment to take TE into account.

**Comment by zooba** [comment] 2017-01-11 17:07
So that delay will go away in VS 2017, though it may be replaced by some more annoying behavior (such as #1865), as we now discover tests as part of normal code analysis instead of separately.

The most likely configuration setting to be causing trouble is search paths, or possibly working directory. Both of these _should_ be taken from the project containing the tests, but let us know if you figure out what isn't working here. Quite a few similar issues have been fixed for VS 2017, but we'll be able to check and let you know for sure.

**Comment by huguesv** [comment] 2017-09-18 19:44
Closing, since we have the functionality, and we have a bug open for the issue I've described https://github.com/Microsoft/PTVS/issues/1919

**Closed by huguesv** 2017-09-18 19:44 UTC
