### ISSUE TITLE
Visual Studio becomes unbearably slow after debugging

### ISSUE THREAD

**Issue by zjturner** [Microsoft/PTVS#953] opened 2015-11-05 00:13 UTC
I searched and found some similar performance related issues, but most of the ones I could find were related to a debugging session.  I regularly experience severe performance degredation even outside of a debugging session.

It always seems to be ok for a while, even across a few debugging sessions, after first opening Visual Studio.  Something happens after a while, and then performance becomes really choppy.  For example, a moment ago I double clicked a word inside of a comment to select the word.  And then I clicked somewhere else in the editor window to deselect the text.  The IDE hung during this time for about 10 seconds, at which point finally the text became unselected and I could use the IDE again.  After this happens, the only way for me to get a usable environment again is to close Visual Studio and reopen it.

Is there any way to provide a useful profile?

**Comment by zooba** [comment] 2015-11-05 00:21
The best thing I can think of is quickly attaching another VS instance and breaking to see where each stack is. Our usual escape-hatch for race conditions we can't repro or track down is to use 10s timeouts on most locks, so you're probably hitting one of these.

Visual Studio also has a number of issues like this that are independent of PTVS, so it's not necessarily us (which unfortunately makes it harder to fix), but we really need the callstack.

In theory, PerfWatson should be detecting these hangs and sending information back if you've enabled that, so we may already have the details. Nothing has jumped out of there to me yet, but I'll take another look.

**Comment by zjturner** [comment] 2015-11-05 01:05
I used [UIForETW](https://github.com/google/UIforETW/releases) and was able to get some potentially useful information.  It seems like it could be the garbage collector thrashing.  Every 5 or 6 seconds on my profile I see the gc kick in for a good 3 seconds.

I'm not sure if that's the real cause because I don't have any symbols for `Microsoft.PythonTools.Analysis.ni.dll`, and a lot of time is spent in there which I have no visibility into.

**Comment by zooba** [comment] 2015-11-05 01:12
We publish our symbols on the Microsoft symbol server, but they may not be available for a `.ni.dll`, as we don't eagerly generate those. I'm not entirely sure how they are created - @int19h may know.

**Comment by int19h** [comment] 2015-11-05 01:15
Yes, I don't think you will get symbols for NGEN'd binaries. You can suppress loading them by setting the environment variable `COMPLUS_ZapDisable` to 1 before starting VS.

**Comment by zjturner** [comment] 2015-11-06 00:00
I think PTVS is eating up the entire address space of the process.  
![address_space](https://cloud.githubusercontent.com/assets/11823433/10985353/6f334da2-83d5-11e5-8a1c-3e021afc64e4.png)

This is leading to constant garbage collections.  Can you think of a good way for me to get memory information about the devenv process to find out what objects are using up so much memory?

**Comment by zooba** [comment] 2015-11-06 00:20
Yep, it almost certainly is us.

When dealing with a large project there are a few places where our analysis design isn't able to release memory. To fix this requires a fundamental design change to the core of our code analysis that we haven't had the time/devs to be able do. As a result, when editing one code file, other open code files could accumulate multiple analysis versions that they aren't able to release (because, according to the current design, they are all necessary).

Making null edits to other open files (e.g. add/remove a space) may trigger a reanalysis that will free this memory, and closing/reopening the solution is guaranteed to get it. Unfortunately, we don't currently have any easier or automatic way to do this reset. We're working on it, but it won't be available for a while yet.

**Comment by zjturner** [comment] 2015-11-06 18:11
Hmm, that's interesting, because closing and re-opening the solution didn't decrease my overall memory usage.  it's possible that I just didn't continue using VS long enough to trigger a GC though, but even with the solution closed.

When I originally reported this problem, I don't know for sure that it was the same issue because at that time I didn't check the memory usage.  Next time it happens I'll close and reopen the solution and see if performance gets better (even if task manager reports the same memory usage).

**Comment by zooba** [comment] 2015-11-06 18:31
This is speculation, but I can think of one or two ways that closing the solution won't get it, especially if you have any interactive windows open. My approach to these problems has been to ensure that the live references always go away when you close the solution, but I can't promise I haven't missed anything.

One early design decision was to share state between as many places as possible, so that you'd get good IntelliSense between projects. Unfortunately, this really doesn't scale, but we haven't been prepared to remove it without a replacement and haven't yet developed an alternative way of sharing IntelliSense between projects.

To answer an earlier question that I missed, you can get information about the memory usage by capturing a full process dump and debugging it, either with VS or windbg. But this is generally not helpful and very rarely actually reveals any root causes in our analysis at this stage - the last time I resolved a memory issue it took days of trial and error, with the only useful information from the dumps being that "it's not fixed yet". (The last time it *was* helpful we had a few event handlers not being unhooked, but those are fairly easy to diagnose and there seem to be none left.)

**Comment by zjturner** [comment] 2015-11-17 01:42
So yea, I can confirm that closing the solution doesn't get it.  A couple of things that may or may not be related.  I don't have any interactive windows open, and I associate 2 Python Environments with my project.  One is a 2.7 debug interpreter, one is a 3.5 debug interpreter.  I frequently switch back and forth between the two, and I also frequently change whether or not Native code debugging is enabled.  I can't really think of anything else I'm doing that might be unusual.  Are there any immediate window commands or other types of debugging commands I could use that might help pinpoint what kind of data is taking up the memory?  Like telling Visual Studio to reset all of its intellisense data or something?

Or maybe something like that could be added to PTVS Options dialog for diagnostic purposes?

I was unable to use most .NET memory diagnostics tools because they can't map 3GB of memory into their address space for obvious reasons, but WinDbg seems to be able to handle this ok, albeit very slowly.  I followed [these instructions](http://blogs.msdn.com/b/paullou/archive/2011/06/28/debugging-managed-code-memory-leak-with-memory-dump-using-windbg.aspx): and this is what I get.

     MT        Count      Bytes    Type
    529e2208   219654     10543392 System.Collections.Generic.Dictionary`2[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Parsing.Ast.Expression, Microsoft.PythonTools.Analysis]]
    52c43c64   352253     10543956 Microsoft.PythonTools.Interpreter.IPythonType[]
    52c4c644   219760     10548480 Microsoft.PythonTools.Analysis.Values.StarArgsSequenceInfo
    52c50e30   170215     10893760 Microsoft.PythonTools.Analysis.Values.ListInfo
    52c2ab34   213004     10983768 Microsoft.PythonTools.Analysis.AnalysisDictionary`2+Bucket[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope, Microsoft.PythonTools.Analysis]][]
    529e7008   473207     11356968 System.Collections.Generic.List`1[[Microsoft.PythonTools.Interpreter.IPythonType, Microsoft.PythonTools.Analysis]]
    52c48c84   219654     11422008 Microsoft.PythonTools.Analysis.Values.FunctionInfo
    52c2f334   175051     12064436 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.PythonTools.Analysis.IProjectEntry, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Values.ReferenceList, Microsoft.PythonTools.Analysis]][]
    52c3b7c4   667236     12670196 Microsoft.PythonTools.Analysis.VariableDef[]
    52c28880     2192     12764704 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[System.Collections.Generic.Dictionary`2[[System.Object, mscorlib],[System.Object, mscorlib]], mscorlib]][]
    52c35060   168258     13044120 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.PythonTools.Analysis.AnalysisValue, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.IAnalysisSet, Microsoft.PythonTools.Analysis]][]
    72c92824    55524     13450057 System.Byte[]
    52c4783c   916328     14661248 Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisSetTwoObject
    52c29b5c   165308     14921712 System.Collections.Generic.Dictionary`2+Entry[[Microsoft.PythonTools.Analysis.Values.CallChain, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit, Microsoft.PythonTools.Analysis]][]
    52c4c8d8   321035     15409680 Microsoft.PythonTools.Analysis.Values.SequenceInfo
    52c4e4dc   804479     16089580 Microsoft.PythonTools.Parsing.Ast.NameExpression
    52c47734   810810     16216200 Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet
    52c3e5ec   229531     18724344 Microsoft.PythonTools.Analysis.AnalysisDictionary`2+Bucket[[System.String, mscorlib],[System.Collections.Generic.HashSet`1[[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]], System.Core]][]
    52c29ff8   317987     19217184 Microsoft.PythonTools.Analysis.AnalysisDictionary`2+Bucket[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.IAnalysisSet, Microsoft.PythonTools.Analysis]][]
    529f0358   970776     19415520 Microsoft.PythonTools.Analysis.AnalysisDictionary`2[[Microsoft.PythonTools.Analysis.IProjectEntry, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo`1[[Microsoft.PythonTools.Analysis.AnalysisValue, Microsoft.PythonTools.Analysis]], Microsoft.PythonTools.Analysis]]
    529e8384   516305     20652200 System.Collections.Generic.HashSet`1[[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]]
    52c2d830   516305     24782640 System.Collections.Generic.HashSet`1+Slot[[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]][]
    52c4c70c   204020     25298480 Microsoft.PythonTools.Analysis.Values.StarArgsDictionaryInfo
    52c3d350   945561     27350176 Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope[]
    7283fc88   583487     28007376 System.Collections.Generic.Dictionary`2[[System.Object, mscorlib],[System.Object, mscorlib]]
    52c55d04  1210182     29044368 Microsoft.PythonTools.Analysis.SetOfTwo`1[[Microsoft.PythonTools.Analysis.EncodedLocation, Microsoft.PythonTools.Analysis]]
    72cd0f34   581423     34885380 System.Collections.Generic.Dictionary`2+Entry[[System.Object, mscorlib],[System.Object, mscorlib]][]
    529f04a8  2139656     42793120 Microsoft.PythonTools.Analysis.AnalysisDictionary`2[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope, Microsoft.PythonTools.Analysis]]
    529f0458  2139656     42793120 Microsoft.PythonTools.Analysis.AnalysisDictionary`2[[System.String, mscorlib],[System.Collections.Generic.HashSet`1[[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]], System.Core]]
    529f02b4  2139656     42793120 Microsoft.PythonTools.Analysis.AnalysisDictionary`2[[System.String, mscorlib],[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]]
    529f0118  2139656     42793120 Microsoft.PythonTools.Analysis.AnalysisDictionary`2[[Microsoft.PythonTools.Parsing.Ast.Node, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.IAnalysisSet, Microsoft.PythonTools.Analysis]]
    52c4aed8   935699     44913552 Microsoft.PythonTools.Analysis.Analyzer.FunctionAnalysisUnit
    529e0df8  2141768     51402432 System.Collections.Generic.List`1[[Microsoft.PythonTools.Analysis.Analyzer.InterpreterScope, Microsoft.PythonTools.Analysis]]
    52c501ec  2019854     56555912 Microsoft.PythonTools.Analysis.LocatedVariableDef
    52c51978  1121619     58324188 Microsoft.PythonTools.Analysis.Analyzer.StatementScope
    52c55e40  3731430     59702880 Microsoft.PythonTools.Analysis.SetOfOne`1[[Microsoft.PythonTools.Analysis.EncodedLocation, Microsoft.PythonTools.Analysis]]
    52c4bd90   935699     59884736 Microsoft.PythonTools.Analysis.Analyzer.FunctionScope
    52c32898   970776     63333312 Microsoft.PythonTools.Analysis.AnalysisDictionary`2+Bucket[[Microsoft.PythonTools.Analysis.IProjectEntry, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo`1[[Microsoft.PythonTools.Analysis.AnalysisValue, Microsoft.PythonTools.Analysis]], Microsoft.PythonTools.Analysis]][]
    52c45484  4479185     71666960 Microsoft.PythonTools.Analysis.VariableDef
    72c8d588   989365     75926462 System.String
    52c49f10  1970252     78810080 System.Collections.Generic.HashSet`1[[Microsoft.PythonTools.Analysis.EncodedLocation, Microsoft.PythonTools.Analysis]]
    52c2e5e0   798717     85247908 Microsoft.PythonTools.Analysis.AnalysisSetDetails.AnalysisHashSet+Bucket[]
    52c53724  5614789    112295780 Microsoft.PythonTools.Analysis.SingleDict`2+SingleDependency[[Microsoft.PythonTools.Analysis.IProjectEntry, Microsoft.PythonTools.Analysis],[Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo`1[[Microsoft.PythonTools.Analysis.AnalysisValue, Microsoft.PythonTools.Analysis]], Microsoft.PythonTools.Analysis]]
    52c34d64  1011200    119434872 Microsoft.PythonTools.Analysis.AnalysisDictionary`2+Bucket[[System.String, mscorlib],[Microsoft.PythonTools.Analysis.VariableDef, Microsoft.PythonTools.Analysis]][]
    52c2ebc0   188868    119670048 System.Collections.Generic.HashSet`1+Slot[[Microsoft.PythonTools.Analysis.AnalysisUnit, Microsoft.PythonTools.Analysis]][]
    72c8f494  4131168    195328140 System.Int32[]
    52c47a10  8270415    231571620 Microsoft.PythonTools.Analysis.Analyzer.TypedDependencyInfo`1[[Microsoft.PythonTools.Analysis.AnalysisValue, Microsoft.PythonTools.Analysis]]
    00eade10  2040994    263782872      Free
    52c2ec1c  1970252    273220368 System.Collections.Generic.HashSet`1+Slot[[Microsoft.PythonTools.Analysis.EncodedLocation, Microsoft.PythonTools.Analysis]][]

I don't know if this helps or tells you anything you didn't already suspect.  I'm trying to get more information about some of the top items on the list, but WinDbg has been "*BUSY*" for 30 minutes with no response yet...

**Comment by zooba** [comment] 2015-11-17 16:17
Yeah, nothing new there, though I don't think I've ever seen `StarArgsSequenceInfo` so high up. There may be some ways we can improve handling for when `*args` are used, but given it basically matches the number of `FunctionInfo` instances (i.e. is not 2x or 10x) the problem is more likely explosive function growth - generally due to nested functions.

Other than this info, ideally with traces to the GC root, and a deep understanding of how our analyzer works, there's nothing else that can really help diagnose these. It might be interesting to expose the number of distinct entries we have for each function, but honestly I'd rather keep investing the time in rearchitecting the analyzer so we don't need to make so many entries at all.

**Comment by zjturner** [comment] 2015-11-17 17:40
Nested functions could be it.  I have a lot of decorators that look like this:

````python
def foo(arg):
    def fn(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            # Stuff goes here
        return wrapper
    return fn
````

And these can go a couple levels deep

**Comment by zjturner** [comment] 2015-11-17 18:48
I got a GCRoot for one of the objects
[GCRoot.txt](https://github.com/Microsoft/PTVS/files/37055/GCRoot.txt)
.  I'm attaching it here instead pasting it inline because it's kind of huge.  

Anyway, understand if you prefer to keep focusing on the analysis re-architecture instead of investing a lot of time to this.  But if something jumps out at you and succumbs to a quick fix, it would be really nice :)

Look at the top of the GCRoot, this stands out:

    44a7b474 Microsoft.PythonTools.EnvironmentsList.EnvironmentView

Maybe there could be a button in the PTVS Advanced Options dialog which basically just sets this thing to null, or to a new instance, as a temporary stopgap while the re-architecture is in progress.

In any case, I've taken this about as far as I can.  Thanks!

**Comment by zooba** [comment] 2015-11-17 19:42
Closing the Python Environments window may release those. Unfortunately, I can't see the event handlers that are keeping it alive on either side of it, so it's likely to be WPF internals. It's also highly likely that even if that window were disabled, there'd be another reference in that chain keeping things alive - at some point, legitimately. The problem is the tail of nested functions, which is obviously very deep (possibly even circular).

One way you can reduce the depth of analysis we do is to create a registry key at `HKCU\Software\Microsoft\PythonTools\14.0\Analysis\Project@CallDepth` and set it to 1. This should have a pretty significant impact performance-wise, though it's likely to cause all of your decorators to stop being analyzed correctly. You could alternatively add a value `DecreaseCallDepth` and set it to less than 30 for something less aggressive, or set `ProcessCustomDecorators` to 0 to disable processing of decorators completely. (There's a range of reasons we don't make these easily available through the UI, in large part because we see too many people change options and then wonder why things behave differently. Also, we _want_ to hear about these problems, and if a button makes them go away then we never find out just how bad things are.)

**Comment by zooba** [comment] 2015-11-17 19:42
(Note that the `14.0` should be `12.0` if you're on VS 2013.)

**Comment by zjturner** [comment] 2016-02-04 00:20
Just a quick update:

I'm not sure if it's the same issue or unrelated, but this is now causing Visual Studio to actually crash 3-4 times a day (presumably you have automatic upload of crash data, so maybe you're seeing these crashes come through?).

I've also set `ProcessCustomDecorators` to 0, and it seems to help the performance a little bit, but occasionally it still goes awry and hangs for a while and then triggers a crash.

I'm on Visual Studio 2015 Update 1 and I'm off of my Python 2.7 custom interpreter now and using a supported 3.5 Debug Interpreter for 100% of my work now, so we can rule out those issues.

**Comment by zooba** [comment] 2016-02-04 00:26
If you're hitting out of memory errors, the crash reports actually aren't all that helpful. We really just need to get the workaround in that I keep talking about and never get time for (or the rearchitect that I keep talking about and never get time for...)

I'd guess you've got more code now? That seems more likely than the bug getting worse without us touching the code :)

**Comment by zjturner** [comment] 2016-02-04 00:32
I don't have that much more code, but I suppose a little.  In order from least aggressive to most aggressive, what registry options can I set?  I know you mentioned a few up above but I'm sure how to rank them.  Right now I have `ProcessCustomDecorators=0`.  Maybe I can kick it up a notch one by one until I find the one that makes me stop having errors.

It's strange though because I used to be able to run Visual Studio for long periods of time and I would suffer through the slowdowns.  Now with `ProcessCustomDecorators=0` I'll be going along just fine for a few hours, then all of a sudden I get one major slowdown followed by a crash.  So the symptoms are similar, yet different enough that I wonder if something else is going on in parallel.

**Comment by zooba** [comment] 2016-02-04 00:44
That's entirely possible. If you can watch your RAM usage and see what happens there may be something interesting there. For example, if it stays low but then very sharply goes through the roof then we may be hitting a fixable problem. A repro would be ideal in this case (a full process dump is nearly as good), as we really need to dig through the live memory state to figure out what's causing it.

`CallDepth` is the most aggressive option - it is basically the analysis fanout depth. So `CallDepth` of 3 (the default) means we'll go much deeper than `CallDepth` of 1 (zero makes no sense here). Every other option is unlikely to have any significant impact, but you can see them all [here](https://github.com/Microsoft/PTVS/blob/master/Python/Product/Analysis/AnalysisLimits.cs).

**Closed** 2016-12-17 00:58 UTC
